Repository BabylonJS/Babylon.js, pull requests merged in 2021-06, with the labels that each got.

#10442 WebGPU: add support for offscreen canvas
  src/Engines/WebGPU/webgpuTextureHelper.ts
  src/Engines/webgpuEngine.ts
Labels: automerge

#10458 DeviceInputSystem - Fix issue where mouse is deregistered on MacOS
  dist/preview release/what's new.md
  src/DeviceInput/Implementations/webDeviceInputSystem.ts
Labels: automerge

#10443 [GE] Parenting System (Tree view)
  dist/preview release/what's new.md
  guiEditor/src/components/sceneExplorer/entities/gui/controlTreeItemComponent.tsx
  guiEditor/src/components/sceneExplorer/sceneExplorerComponent.tsx
  guiEditor/src/components/sceneExplorer/treeItemSelectableComponent.tsx
  guiEditor/src/diagram/workbench.tsx
  guiEditor/src/globalState.ts
  package.json
Labels: gui editor

#10455 Fix for disabledColor not working for Button
  dist/preview release/what's new.md
  gui/src/2D/controls/rectangle.ts
Labels: bug, gui

#10484 Set Material's 'metadata' property as serializable
  dist/preview release/what's new.md
  src/Materials/material.ts
Labels: automerge

#10476 feature: custom timeout
  dist/preview release/what's new.md
  src/Misc/webRequest.ts
Labels: automerge

#10498 [GE] Advance Texture Property Tab
  guiEditor/public/imgs/adtIcon.svg
  guiEditor/public/imgs/artboardColorIcon.svg
  guiEditor/public/imgs/canvasSizeIcon.svg
  guiEditor/public/imgs/dropdownArrowIcon.svg
  guiEditor/public/imgs/responsiveIcon.svg
  guiEditor/public/imgs/toggleOffIcon.svg
  guiEditor/public/imgs/toggleOnIcon.svg
  guiEditor/src/components/propertyTab/propertyTab.scss
  guiEditor/src/components/propertyTab/propertyTabComponent.tsx
  guiEditor/src/diagram/workbench.tsx
  sharedUiComponents/lines/checkBoxLineComponent.tsx
  sharedUiComponents/lines/optionsLineComponent.tsx
  sharedUiComponents/lines/textInputLineComponent.tsx
Labels: gui editor

#10519 Add mesh.visibility support to grid material
  dist/preview release/what's new.md
  materialsLibrary/src/grid/grid.fragment.fx
  materialsLibrary/src/grid/gridMaterial.ts
Labels: automerge

#10491 Support Base64 Encoded Data URL's generically
  dist/preview release/what's new.md
  loaders/src/STL/stlFileLoader.ts
  loaders/src/glTF/2.0/glTFLoader.ts
  loaders/src/glTF/glTFFileLoader.ts
  src/Loading/sceneLoader.ts
  src/Misc/fileTools.ts
  src/Misc/stringTools.ts
  src/Misc/tools.ts
  src/scene.ts
  tests/unit/babylon/src/Loading/babylon.sceneLoader.testData.ts
  tests/unit/babylon/src/Loading/babylon.sceneLoader.tests.ts
  tests/unit/karma.conf.js
Labels: automerge

#10533 [GE] Adding icons to line components
  guiEditor/src/components/propertyTab/propertyTab.scss
  guiEditor/src/components/sceneExplorer/sceneExplorer.scss
  guiEditor/src/diagram/workbenchCanvas.scss
  guiEditor/src/main.scss
  sharedUiComponents/lines/booleanLineComponent.tsx
  sharedUiComponents/lines/buttonLineComponent.tsx
  sharedUiComponents/lines/checkBoxLineComponent.tsx
  sharedUiComponents/lines/color3LineComponent.tsx
  sharedUiComponents/lines/color4LineComponent.tsx
  sharedUiComponents/lines/colorPickerComponent.tsx
  sharedUiComponents/lines/fileButtonLineComponent.tsx
  sharedUiComponents/lines/fileMultipleButtonLineComponent.tsx
  sharedUiComponents/lines/floatLineComponent.tsx
  sharedUiComponents/lines/hexLineComponent.tsx
  sharedUiComponents/lines/numericInputComponent.tsx
  sharedUiComponents/lines/radioLineComponent.tsx
  sharedUiComponents/lines/sliderLineComponent.tsx
  sharedUiComponents/lines/textLineComponent.tsx
  sharedUiComponents/lines/valueLineComponent.tsx
  sharedUiComponents/lines/vector2LineComponent.tsx
  sharedUiComponents/lines/vector3LineComponent.tsx
  sharedUiComponents/lines/vector4LineComponent.tsx
Labels: gui editor

#10537 glTF KHR_materials_transmission: Render the opaque scene with env intensity fixed
  loaders/src/glTF/2.0/Extensions/KHR_materials_transmission.ts
Labels: automerge

#10548 [GE] Copying property line files
  guiEditor/src/components/propertyTab/propertyGrids/gui/checkboxPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/colorPickerPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/commonControlPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/controlPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/ellipsePropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/gridPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/imageBasedSliderPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/imagePropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/inputTextPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/linePropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/radioButtonPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/rectanglePropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/scrollViewerPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/sliderPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/stackPanelPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyGrids/gui/textBlockPropertyGridComponent.tsx
  guiEditor/src/components/propertyTab/propertyTabComponent.tsx
Labels: gui editor

#10481 Refactor WebXRHandTracking
  dist/preview release/what's new.md
  src/Behaviors/Meshes/handConstraintBehavior.ts
  src/LibDeclarations/webxr.d.ts
  src/XR/features/WebXRHandTracking.ts
Labels: VR/AR/XR, automerge
