Repository BabylonJS/Babylon.js, pull requests merged in 2022-09, with the labels that each got.

#12905 Fix scene not clearing in some Default Rendering Pipeline with multicamera cases
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/Misc/arrayTools.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/defaultRenderingPipeline.ts
  packages/dev/core/src/scene.ts
Labels: bug, post-process

#12934 Time Factor for crowd agents update
  packages/dev/core/src/Navigation/Plugins/recastJSPlugin.ts
Labels: new feature

#12935 Fix #12931
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
Labels: bug, gui

#12933 Add Link offset properties to Gui Editor
  packages/dev/sharedUiComponents/src/imgs/linkedMeshOffsetIcon.svg
  packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/commonControlPropertyGridComponent.tsx
  packages/tools/guiEditor/src/diagram/coordinateHelper.tsx
Labels: enhancement, gui editor

#12937 Fix loading of base64 svgs
  packages/dev/core/src/Misc/fileTools.ts
Labels: bug

#12940 Fix reflection block empty output
  packages/dev/core/src/Materials/Node/Blocks/Dual/reflectionTextureBlock.ts
Labels: bug

#12941 switch to new PG
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#12943 Added AudioBuffer as parameter for Sound
  packages/dev/core/src/Audio/sound.ts
Labels: enhancement, audio

#12950 Improve optimize docstring.
  packages/dev/core/src/Meshes/groundMesh.ts
Labels: skip changelog

#12944 Animation perf improvments
  packages/dev/core/src/Bones/skeleton.ts
  packages/dev/core/src/Meshes/transformNode.ts
Labels: enhancement, animations

#12951 Fix some NME bugs.
  packages/dev/core/src/Materials/Node/Blocks/Fragment/perturbNormalBlock.ts
  packages/dev/sharedUiComponents/src/components/MessageDialog.tsx
  packages/tools/nodeEditor/src/graphEditor.tsx
Labels: bug, nme

#12953 Use the right function when reaching limits
  packages/dev/core/src/Misc/logger.ts
Labels: skip changelog

#12865 DeviceInputSystem: Pull browser specific code into WebDeviceInputSystem
  packages/dev/core/src/Cameras/Inputs/BaseCameraMouseWheelInput.ts
  packages/dev/core/src/Cameras/Inputs/BaseCameraPointersInput.ts
  packages/dev/core/src/Cameras/Inputs/arcRotateCameraMouseWheelInput.ts
  packages/dev/core/src/Cameras/Inputs/flyCameraMouseInput.ts
  packages/dev/core/src/Cameras/Inputs/followCameraMouseWheelInput.ts
  packages/dev/core/src/Cameras/Inputs/freeCameraMouseInput.ts
  packages/dev/core/src/DeviceInput/webDeviceInputSystem.ts
  packages/dev/core/src/Events/deviceInputEvents.ts
  packages/dev/core/src/Inputs/scene.inputManager.ts
  packages/dev/core/src/Offline/database.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
Labels: new feature

#12955 Fix quaternion blending math
  packages/dev/core/src/Animations/animatable.ts
Labels: bug

#12957 Fix stl loader right handed
  packages/dev/loaders/src/STL/stlFileLoader.ts
Labels: bug, loaders

#12961 Fix Rendering Pipeline cameras
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/defaultRenderingPipeline.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/postProcessRenderPipeline.ts
Labels: bug, post-process

#12948 Use CSS Modules in Graph System
  packages/dev/buildTools/src/webpackTools.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/common.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/frameNodePort.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphFrame.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphFrame.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/interfaces/displayManager.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodeLink.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodeLink.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/scss/graphCanvas.scss
  packages/tools/nodeEditor/src/graphSystem/display/clampDisplayManager.modules.scss
  packages/tools/nodeEditor/src/graphSystem/display/clampDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/display/common.modules.scss
  packages/tools/nodeEditor/src/graphSystem/display/elbowDisplayManager.modules.scss
  packages/tools/nodeEditor/src/graphSystem/display/elbowDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/display/gradientDisplayManager.modules.scss
  packages/tools/nodeEditor/src/graphSystem/display/gradientDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/display/imageSourceDisplayManager.modules.scss
  packages/tools/nodeEditor/src/graphSystem/display/imageSourceDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/display/inputDisplayManager.modules.scss
  packages/tools/nodeEditor/src/graphSystem/display/inputDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/display/outputDisplayManager.modules.scss
  packages/tools/nodeEditor/src/graphSystem/display/remapDisplayManager.modules.scss
  packages/tools/nodeEditor/src/graphSystem/display/remapDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/display/textureDisplayManager.modules.scss
  packages/tools/nodeEditor/src/graphSystem/display/textureDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/display/trigonometryDisplayManager.modules.scss
  packages/tools/nodeEditor/src/graphSystem/display/trigonometryDisplayManager.ts
  packages/tools/nodeEditor/webpack.config.js
Labels: skip changelog

#12969 Giz misc
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
Labels: enhancement

#12973 Fix WebGPU for mobile support.
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: bug, WebGPU

#12982 Fix Array Observers
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/Misc/arrayTools.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/defaultRenderingPipeline.ts
  packages/dev/core/src/scene.ts
  packages/dev/core/test/unit/Misc/babylon.arrayTools.test.ts
Labels: skip changelog

#12984 Fix billboard translation with parenting
  packages/dev/core/src/Meshes/transformNode.ts
Labels: bug

#12983 GeometryBufferRenderer: Allow setting the depth texture format
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/core/src/Rendering/geometryBufferRendererSceneComponent.ts
Labels: enhancement, rendering engine

#12985 Add maths polar export
  packages/dev/core/src/Maths/index.ts
Labels: skip changelog

#12978 Some fixes for NME CSS
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphFrame.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphFrame.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.modules.scss
  packages/tools/nodeEditor/src/graphSystem/blockNodeData.modules.scss
  packages/tools/nodeEditor/src/graphSystem/blockNodeData.ts
  packages/tools/nodeEditor/src/graphSystem/display/textureDisplayManager.modules.scss
Labels: bug

#12988 PrePass renderer: Fix engine current render pass id set too early
  packages/dev/core/src/Rendering/prePassRenderer.ts
Labels: bug, rendering engine

#12991 WebGPU: Fix geometry buffer renderer in WebGPU
  packages/dev/core/src/Shaders/geometry.fragment.fx
Labels: bug, WebGPU

#12996 Test babylon vertex buffer instance divisor
  packages/dev/core/src/Buffers/buffer.ts
  packages/dev/core/test/unit/Buffers/babylon.buffer.test.ts
Labels: skip changelog

#12990 Add operator functions to Polar and Spherical
  packages/dev/core/src/Maths/math.polar.ts
Labels: skip changelog

#12998 [XR] Fix XR picking in utility laters
  packages/dev/core/src/Behaviors/Meshes/baseSixDofDragBehavior.ts
  packages/dev/core/src/Events/pointerEvents.ts
  packages/dev/core/src/Inputs/scene.inputManager.ts
  packages/dev/core/src/Rendering/utilityLayerRenderer.ts
  packages/dev/core/src/XR/features/WebXRNearInteraction.ts
Labels: bug

#13001 Fix nme drop
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodeLink.ts
Labels: bug, nme, skip changelog

#13007 Fix effects onError notifications
  packages/dev/core/src/Materials/effect.ts
Labels: bug, rendering engine

#13008 Fix cache issue
  packages/dev/sharedUiComponents/src/lines/optionsLineComponent.tsx
Labels: skip changelog

#13000 Clean up implementation of KHR_animation_pointer
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_animation_pointer.data.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_animation_pointer.map.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_animation_pointer.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_lights_punctual.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoaderAnimation.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoaderExtension.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoaderInterfaces.ts
  packages/dev/loaders/src/glTF/2.0/glTFUtilities.ts
  packages/public/glTF2Interface/babylon.glTF2Interface.d.ts
Labels: bug, skip changelog

#13013 Fix some more lint warnings
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_animation_pointer.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoaderInterfaces.ts
Labels: skip changelog

#13011 Tiny perf fix
  packages/dev/core/src/scene.ts
Labels: enhancement, rendering engine

#13017 Nit
  packages/dev/core/src/Rendering/renderingManager.ts
Labels: skip changelog

#13018 Fix particle system support for logarithmic depth
  packages/dev/core/src/Materials/materialHelper.ts
  packages/dev/core/src/Particles/gpuParticleSystem.ts
  packages/dev/core/src/Particles/particleSystem.ts
Labels: skip changelog

#13023 Fix SSAO2 sample generation
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssao2RenderingPipeline.ts
  packages/tools/tests/test/visualization/ReferenceImages/prepass-ssao-b-and-w.png
Labels: bug, rendering engine, breaking change

#13021 Fix instance buffer
  packages/dev/core/src/Materials/Textures/thinRenderTargetTexture.ts
  packages/dev/core/src/Materials/materialHelper.ts
  packages/dev/core/src/Meshes/instancedMesh.ts
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockAlbedoOpacity.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrFragmentExtraDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/vertexColorMixing.fx
  packages/dev/core/src/Shaders/color.fragment.fx
  packages/dev/core/src/Shaders/color.vertex.fx
  packages/dev/core/src/Shaders/default.fragment.fx
  packages/dev/core/src/Shaders/default.vertex.fx
  packages/dev/core/src/Shaders/pbr.vertex.fx
  packages/dev/materials/src/cell/cell.fragment.fx
  packages/dev/materials/src/fire/fire.fragment.fx
  packages/dev/materials/src/fur/fur.fragment.fx
  packages/dev/materials/src/gradient/gradient.fragment.fx
  packages/dev/materials/src/lava/lava.fragment.fx
  packages/dev/materials/src/mix/mix.fragment.fx
  packages/dev/materials/src/simple/simple.fragment.fx
  packages/dev/materials/src/simple/simple.vertex.fx
  packages/dev/materials/src/sky/sky.fragment.fx
  packages/dev/materials/src/terrain/terrain.fragment.fx
  packages/dev/materials/src/terrain/terrain.vertex.fx
  packages/dev/materials/src/triPlanar/triplanar.fragment.fx
  packages/dev/materials/src/triPlanar/triplanar.vertex.fx
  packages/dev/materials/src/water/water.fragment.fx
  packages/dev/materials/src/water/water.vertex.fx
Labels: bug, rendering engine

#13026 Some fixes to OptionLineComponent related to wrong parent info showin…
  packages/dev/sharedUiComponents/src/lines/optionsLineComponent.tsx
  packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/commonControlPropertyGridComponent.tsx
Labels: bug

#13028 Fix default initialization.
  packages/dev/sharedUiComponents/src/lines/optionsLineComponent.tsx
Labels: skip changelog

#13019 Restore wasDispatched to false when MaintainStateBetweenFrames is set to false
  packages/dev/core/src/Rendering/renderingManager.ts
Labels: skip changelog

#13033 Update Storybook to 7
  package-lock.json
  package.json
  packages/dev/sharedUiComponents/.storybook/main.js
  packages/dev/sharedUiComponents/package.json
Labels: skip changelog

#13034 Initial VSM Design
  .vscode/tasks.json
  packages/dev/sharedUiComponents/src/components/bars/CommandBar.modules.scss
  packages/dev/sharedUiComponents/src/components/bars/CommandBarComponent.tsx
  packages/dev/sharedUiComponents/src/components/bars/CommandButton.modules.scss
  packages/dev/sharedUiComponents/src/components/bars/CommandButtonComponent.tsx
  packages/dev/sharedUiComponents/src/components/bars/CommandDropdown.modules.scss
  packages/dev/sharedUiComponents/src/components/bars/CommandDropdownComponent.tsx
  packages/dev/sharedUiComponents/src/components/classNames.ts
  packages/dev/sharedUiComponents/src/components/lines/FileButtonLineComponent.modules.scss
  packages/dev/sharedUiComponents/src/components/lines/FileButtonLineComponent.tsx
  packages/dev/sharedUiComponents/src/imgs/betaFlag.svg
  packages/dev/sharedUiComponents/src/imgs/canvasFitIcon.svg
  packages/dev/sharedUiComponents/src/imgs/hamburger.svg
  packages/dev/sharedUiComponents/src/stories/bars/CommandBarComponent.stories.tsx
  packages/dev/sharedUiComponents/src/stories/bars/CommandButtonComponent.stories.tsx
  packages/dev/sharedUiComponents/src/stories/lines/FileButtonLineComponent.stories.tsx
  packages/tools/vsm/src/customDeclarations.d.ts
  packages/tools/vsm/src/workbench.modules.scss
  packages/tools/vsm/src/workbench.tsx
Labels: skip changelog

#13036 Add applyPostProcess flag on ADV to optionally draw it after the post…
  packages/dev/core/src/Layers/layer.ts
  packages/dev/core/src/Layers/layerSceneComponent.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/scene.ts
  packages/dev/core/src/sceneComponent.ts
  packages/tools/tests/test/visualization/ReferenceImages/uiUnaffected.png
  packages/tools/tests/test/visualization/config.json
Labels: enhancement

#13043 Fix wrong plugin name check for babylon serialization
  packages/dev/core/src/Loading/Plugins/babylonFileLoader.ts
Labels: bug, physics

#13042 Fix billboard scale in hierarchy
  packages/dev/core/src/Meshes/transformNode.ts
  packages/tools/tests/test/visualization/ReferenceImages/billboardParentScale.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#13045 Change the artboard color on VSM
  packages/dev/sharedUiComponents/.storybook/main.js
  packages/dev/sharedUiComponents/src/components/bars/CommandBar.modules.scss
  packages/dev/sharedUiComponents/src/components/bars/CommandBarComponent.tsx
  packages/dev/sharedUiComponents/src/components/colorPicker/ColorComponentEntry.modules.scss
  packages/dev/sharedUiComponents/src/components/colorPicker/ColorComponentEntry.tsx
  packages/dev/sharedUiComponents/src/components/colorPicker/ColorPicker.modules.scss
  packages/dev/sharedUiComponents/src/components/colorPicker/ColorPicker.tsx
  packages/dev/sharedUiComponents/src/components/colorPicker/HexColor.modules.scss
  packages/dev/sharedUiComponents/src/components/colorPicker/HexColor.tsx
  packages/dev/sharedUiComponents/src/components/lines/ColorLineComponent.modules.scss
  packages/dev/sharedUiComponents/src/components/lines/ColorLineComponent.tsx
  packages/dev/sharedUiComponents/src/components/lines/ColorPickerLineComponent.modules.scss
  packages/dev/sharedUiComponents/src/components/lines/ColorPickerLineComponent.tsx
  packages/dev/sharedUiComponents/src/components/lines/NumericInputComponent.modules.scss
  packages/dev/sharedUiComponents/src/components/lines/NumericInputComponent.tsx
  packages/dev/sharedUiComponents/src/imgs/copy.svg
  packages/dev/sharedUiComponents/src/stories/bars/CommandBarComponent.stories.tsx
  packages/dev/sharedUiComponents/src/stories/colorPicker/ColorPicker.stories.tsx
  packages/dev/sharedUiComponents/src/stories/lines/ColorLineComponent.stories.tsx
  packages/dev/sharedUiComponents/src/stories/lines/ColorPickerLineComponent.stories.tsx
  packages/dev/sharedUiComponents/src/stories/lines/NumericInputComponent.stories.tsx
  packages/tools/vsm/src/workbench.modules.scss
  packages/tools/vsm/src/workbench.tsx
Labels: skip changelog

#13046 Inspector Doc Link Fix
  packages/dev/core/src/Debug/debugLayer.ts
Labels: skip changelog
