Repository BabylonJS/Babylon.js, pull requests merged in 2022-08, with the labels that each got.

#12818 Fxi heightmap impostor with Cannon
  packages/dev/core/src/Physics/physicsImpostor.ts
Labels: bug, physics

#12819 Fix babylon native sprites
  packages/dev/core/src/Engines/engineFeatures.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/nullEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Sprites/spriteRenderer.ts
Labels: bug, native

#12822 Change "TO" to "To" in two places in buildSystem.md
  buildSystem.md
Labels: skip changelog

#12767 KHR animation pointer
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_animation_pointer.map.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_animation_pointer.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_lights_punctual.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/index.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoaderInterfaces.ts
  packages/dev/loaders/src/glTF/2.0/glTFUtilities.ts
  packages/dev/serializers/src/glTF/2.0/glTFAnimation.ts
  packages/public/glTF2Interface/babylon.glTF2Interface.d.ts
Labels: enhancement, new feature

#12832 [Build] Support for scss modules
  packages/dev/buildTools/src/webpackTools.ts
  packages/dev/sharedUiComponents/src/components/Button.modules.scss
  packages/dev/sharedUiComponents/src/components/Button.tsx
  packages/dev/sharedUiComponents/src/components/Icon.modules.scss
  packages/dev/sharedUiComponents/src/components/Icon.tsx
  packages/dev/sharedUiComponents/src/components/Label.modules.scss
  packages/dev/sharedUiComponents/src/components/Label.tsx
  packages/dev/sharedUiComponents/src/components/Toggle.modules.scss
  packages/dev/sharedUiComponents/src/components/Toggle.tsx
  packages/dev/sharedUiComponents/src/scssDeclaration.d.ts
  packages/tools/guiEditor/src/custom.d.ts
  packages/tools/nodeEditor/src/custom.d.ts
Labels: new feature

#12835 Move typings to Webgl2RenderingContext
  packages/dev/core/src/Engines/Extensions/engine.query.ts
  packages/dev/core/src/Engines/Extensions/engine.transformFeedback.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/LibDeclarations/webgl.d.ts
  packages/dev/core/src/LibDeclarations/webgl2.d.ts
Labels: enhancement, tools

#12836 Export Material Plugin Events
  packages/dev/core/src/Materials/index.ts
Labels: enhancement, materials

#12837 More Tests on ProjectToPlane
  packages/dev/core/src/Maths/math.vector.ts
  packages/dev/core/test/unit/Math/babylon.math.vector.test.ts
Labels: skip changelog

#12838 Safari/Selenium Tests
  .vscode/launch.json
  jest.config.ts
  package-lock.json
  package.json
  packages/tools/testTools/package.json
  packages/tools/testTools/src/index.ts
  packages/tools/testTools/src/seleniumTestUtils.ts
  packages/tools/tests/test/interactions/safari.test.ts
Labels: skip changelog

#12841 Fix #12839
  packages/dev/core/src/Debug/debugLayer.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGridTabComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/emptyPropertyGridComponent.tsx
  packages/dev/inspector/src/components/embedHost/embedHostComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/sceneExplorer.scss
  packages/dev/inspector/src/components/sceneExplorer/sceneExplorerComponent.tsx
  packages/dev/inspector/src/inspector.ts
Labels: new feature

#12844 GUI Editor Tool buttons now respond on the entire document instead of…
  packages/tools/guiEditor/src/diagram/workbench.tsx
  packages/tools/guiEditor/src/globalState.ts
  packages/tools/guiEditor/src/workbenchEditor.tsx
Labels: bug

#12842 Fix getHeightAtCoordinates with Impostors and out of bound
  packages/dev/core/src/Meshes/groundMesh.ts
  packages/dev/core/src/Physics/physicsImpostor.ts
Labels: bug, physics

#12848 Show full hex color on Color Picker component
  packages/dev/sharedUiComponents/src/colorPicker/colorPicker.tsx
Labels: bug

#12849 Add transform nodes result to assetManager
  packages/dev/core/src/Misc/assetsManager.ts
Labels: enhancement, loaders

#12852 Add IGizmo-extending interfaces for standard Gizmo variants
  packages/dev/core/src/Gizmos/axisDragGizmo.ts
  packages/dev/core/src/Gizmos/axisScaleGizmo.ts
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
  packages/dev/core/src/Gizmos/cameraGizmo.ts
  packages/dev/core/src/Gizmos/gizmoManager.ts
  packages/dev/core/src/Gizmos/lightGizmo.ts
  packages/dev/core/src/Gizmos/planeDragGizmo.ts
  packages/dev/core/src/Gizmos/planeRotationGizmo.ts
  packages/dev/core/src/Gizmos/positionGizmo.ts
  packages/dev/core/src/Gizmos/rotationGizmo.ts
  packages/dev/core/src/Gizmos/scaleGizmo.ts
Labels: enhancement, gizmos

#12853 Fix issues with basis texture and inspector (display format, preview window and broken texture)
  packages/dev/core/src/Misc/basis.ts
  packages/dev/inspector/src/textureHelper.ts
Labels: bug, texture

#12815 Inspector step modifier keys
  packages/dev/sharedUiComponents/src/lines/floatLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/numericInputComponent.tsx
Labels: enhancement, inspector

#12854 Serialize scrollbar properties.
  packages/dev/gui/src/2D/controls/scrollViewers/scrollViewer.ts
Labels: bug, gui editor

#12855 Fix shortcuts firing while user inputs text
  packages/tools/guiEditor/src/globalState.ts
  packages/tools/guiEditor/src/workbenchEditor.tsx
Labels: bug, gui editor

#12859 Fix WebXR helper
  packages/dev/core/src/XR/webXRExperienceHelper.ts
Labels: bug, VR/AR/XR

#12862 Fix #12745
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
Labels: bug, nme

#12863 Rectangles couldn't get correctly rounded because -2 was subtracted f…
  packages/dev/gui/src/2D/controls/rectangle.ts
Labels: bug, gui

#12864 Restore viewport on Procedural Texture Render
  packages/dev/core/src/Materials/Textures/Procedurals/proceduralTexture.ts
Labels: bug, rendering engine

#12821 DeviceInputSystem: Update Device Input folder structure
  packages/dev/core/src/DeviceInput/InputDevices/deviceSource.ts
  packages/dev/core/src/DeviceInput/InputDevices/deviceSourceManager.ts
  packages/dev/core/src/DeviceInput/eventFactory.ts
  packages/dev/core/src/DeviceInput/inputInterfaces.ts
  packages/dev/core/src/DeviceInput/internalDeviceSourceManager.ts
  packages/dev/core/src/DeviceInput/nativeDeviceInputSystem.ts
  packages/dev/core/src/DeviceInput/webDeviceInputSystem.ts
  packages/dev/core/src/Engines/Native/nativeInterfaces.ts
  packages/dev/core/test/unit/DeviceInput/babylon.deviceInput.test.ts
Labels: skip changelog

#12866 Use glb meshes for sphere and plane in NME preview window
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
Labels: enhancement, nme

#12876 Draw rectangles with properly rounded corners
  packages/dev/gui/src/2D/controls/rectangle.ts
Labels: bug, gui

#12850 Created an offset when pasting controls
  packages/tools/guiEditor/src/diagram/workbench.tsx
Labels: enhancement, gui editor

#12881 Improve MergeMeshes documentation.
  packages/dev/core/src/Meshes/mesh.ts
Labels: enhancement, documentation

#12880 Fix is ready in a few scenari (light dirty, rendering pass id, material changes outside render loop)
  packages/dev/core/src/Materials/Background/backgroundMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/materialHelper.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/scene.ts
Labels: bug, rendering engine

#12884 Enable use of Tools.LoadScript in a WebWorker
  packages/dev/core/src/LibDeclarations/browser.d.ts
  packages/dev/core/src/Misc/tools.ts
Labels: enhancement, tools

#12847 Shared message dialog
  packages/dev/sharedUiComponents/src/components/MessageDialog.modules.scss
  packages/dev/sharedUiComponents/src/components/MessageDialog.tsx
  packages/dev/sharedUiComponents/src/stories/MessageDialog.stories.tsx
  packages/tools/guiEditor/src/main.scss
  packages/tools/guiEditor/src/sharedComponents/messageDialog.tsx
  packages/tools/guiEditor/src/workbenchEditor.tsx
  packages/tools/nodeEditor/src/graphEditor.tsx
  packages/tools/nodeEditor/src/main.scss
  packages/tools/nodeEditor/src/sharedComponents/messageDialog.tsx
Labels: skip changelog

#12887 Fix Drag/Release Behavior in GUI and Photo Dome
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
Labels: new feature

#12896 Store which pointerIds have been captured by the ADV so those are the…
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
  packages/dev/gui/src/2D/controls/control.ts
Labels: skip changelog

#12883 Testing: Update Safari Interactions test to point to BrowserStack
  packages/tools/testTools/src/seleniumTestUtils.ts
  packages/tools/tests/test/interactions/safari.test.ts
Labels: skip changelog

#12902 Fix picking on ADV to account for texture coordinates
  packages/dev/core/src/Maths/math.vector.ts
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
Labels: bug

#12912 Add type on blob creation
  packages/dev/core/src/Misc/fileTools.ts
Labels: bug

#12913 Generate sampler name in buildBlock
  packages/dev/core/src/Materials/Node/Blocks/Dual/sceneDepthBlock.ts
Labels: bug

#12918 Two small fixes
  packages/dev/core/src/Helpers/videoDome.ts
  packages/dev/core/src/Misc/fileTools.ts
Labels: bug

#12919 Associated with #12148
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
Labels: new feature, skip changelog

#12921 Associated with #12148
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
Labels: new feature, skip changelog

#12923 Enforce parent blocks being empty in octree
  packages/dev/core/src/Culling/Octrees/octreeBlock.ts
Labels: bug, optimizations

#12924 Fix Loading Cube Texture from basis file
  packages/dev/core/src/Materials/Textures/cubeTexture.ts
  packages/dev/core/src/Materials/Textures/texture.ts
Labels: bug, texture

#12922 Fix base64 texture parsing with similar names
  packages/dev/core/src/Materials/Textures/texture.ts
Labels: bug, loaders

#12927 Cameras: Add noPreventDefault as argument to attachControl call
  packages/dev/core/src/Cameras/cameraInputsManager.ts
Labels: bug, inputs

#12928 Tiny fixes
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/tools/nodeEditor/src/graphSystem/registerDefaultInput.ts
Labels: skip changelog

#12925 Add support of clipplanes in GlowLayer
  packages/dev/core/src/Layers/effectLayer.ts
  packages/dev/core/src/Shaders/glowMapGeneration.fragment.fx
  packages/dev/core/src/Shaders/glowMapGeneration.vertex.fx
Labels: enhancement, post-process
