Repository BabylonJS/Babylon.js, pull requests merged in 2022-10, with the labels that each got.

#13052 Inspector: Raise the limit of samples in SSAO
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/postProcesses/commonRenderingPipelinePropertyGridComponent.tsx
Labels: enhancement, inspector

#13055 Fix negative scaling issue with instances
  packages/dev/core/src/Meshes/mesh.ts
  packages/tools/tests/test/visualization/ReferenceImages/negative scaling with instances.png
  packages/tools/tests/test/visualization/config.json
Labels: bug, rendering engine

#13054 InputManager: add a property to disable mesh checking in the onPointerOver event
  packages/dev/core/src/Inputs/scene.inputManager.ts
  packages/dev/core/src/Meshes/abstractMesh.ts
Labels: new feature, inputs

#13056 Fix pipelineContext deletion in releaseEffect
  packages/dev/core/src/Engines/thinEngine.ts
Labels: skip changelog

#13057 Fix Texture Cache
  packages/dev/core/src/Materials/Textures/texture.ts
Labels: bug, texture

#13061 fix undefined self
  packages/dev/core/src/Misc/tools.ts
Labels: skip changelog

#13067 PBR: Reset all defines when enabling/disabling pbr components
  packages/dev/core/src/Materials/PBR/pbrAnisotropicConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrClearCoatConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrIridescenceConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrSheenConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrSubSurfaceConfiguration.ts
Labels: bug, rendering engine

#13068 fix glow layer kernel set
  packages/dev/core/src/Layers/glowLayer.ts
Labels: bug, post-process

#13070 Depth peeling renderer: Add excluded mesh support
  packages/dev/core/src/Rendering/depthPeelingRenderer.ts
Labels: rendering engine, new feature

#13072 Fix blur kernel size in glow layer second try
  packages/dev/core/src/Layers/glowLayer.ts
Labels: skip changelog

#13074 Material block-dirty mechanism
  packages/dev/core/src/Materials/material.ts
Labels: new feature

#13060 Handle CSP violation errors when loading images.
  packages/dev/core/src/Misc/fileTools.ts
Labels: bug

#13089 Hide change for billboard hierarchy with a static flag
  packages/dev/core/src/Meshes/transformNode.ts
Labels: enhancement

#13090 Texture inspector in Sandbox does not function correctly
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/textures/textureCanvasManager.ts
Labels: bug, inspector

#13095 `PostProcessRenderPipeline`: Made `_renderEffects` protected to allow subclassing
  packages/dev/core/src/PostProcesses/RenderPipeline/postProcessRenderPipeline.ts
Labels: skip changelog

#13097 Add extension support to assetsManager
  packages/dev/core/src/Misc/assetsManager.ts
Labels: enhancement, loaders

#13101 Texture: Make some setters protected for properties not meant to be changed by end user
  packages/dev/core/src/Materials/Textures/baseTexture.ts
  packages/dev/core/src/Materials/Textures/thinTexture.ts
  packages/dev/core/src/Misc/dds.ts
  packages/dev/core/src/Misc/environmentTextureTools.ts
  packages/dev/core/src/XR/features/WebXRLightEstimation.ts
Labels: skip changelog

#13105 WebGPU fix PCF shadows
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/core/src/Shaders/ShadersInclude/shadowsFragmentFunctions.fx
  packages/tools/babylonServer/public/twgsl/twgsl.js
  packages/tools/babylonServer/public/twgsl/twgsl.wasm
Labels: bug, WebGPU

#13071 GLB header length check from exception to warning
  packages/dev/loaders/src/glTF/glTFFileLoader.ts
Labels: enhancement, glTF

#13111 Decals: Add support for rigged meshes + optimization for speed
  packages/dev/core/src/Meshes/Builders/decalBuilder.ts
Labels: rendering engine, new feature

#13114 forceSharedVertices with skinmesh support
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug

#13123 Increase the maximum bloom threshold value on the inspector slider
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/postProcesses/defaultRenderingPipelinePropertyGridComponent.tsx
Labels: enhancement, inspector

#13122 Add correct placeholders to dropup button on sandbox.
  packages/tools/sandbox/src/components/animationBar.tsx
  packages/tools/sandbox/src/components/dropUpButton.tsx
  packages/tools/sandbox/src/components/footer.tsx
  packages/tools/sandbox/src/scss/footer.scss
Labels: bug, sandbox

#13127 Workaround Firefox Leak
  packages/dev/core/src/Engines/Extensions/engine.videoTexture.ts
  packages/dev/core/src/Materials/Textures/htmlElementTexture.ts
  packages/dev/core/src/Materials/Textures/videoTexture.ts
Labels: bug, texture

#13134 Fix usage of useReverseDepthBuffer with orthographic cameras
  packages/dev/core/src/Cameras/camera.ts
Labels: bug, rendering engine

#13131 Fix infinite sprites draw in frozen scenes
  packages/dev/core/src/Rendering/renderingGroup.ts
  packages/dev/core/src/Rendering/renderingManager.ts
  packages/dev/core/src/scene.ts
Labels: bug, sprite

#13136 InputManager: Fix for POINTERTAP firing when cursor is moved
  packages/dev/core/src/Inputs/scene.inputManager.ts
Labels: enhancement, inputs

#13129 Fix loading of GUIs with custom fonts and add font controls to InputText and InputPassword
  packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/commonControlPropertyGridComponent.tsx
  packages/tools/guiEditor/src/diagram/workbench.tsx
Labels: bug, gui editor

#13143 InputManager: Fix for onPointerMove
  packages/dev/core/src/Culling/ray.ts
  packages/dev/core/src/Inputs/scene.inputManager.ts
  packages/dev/core/src/scene.ts
Labels: bug, inputs

#13128 Flip normal if picking ray is in the same direction
  packages/dev/core/src/Collisions/pickingInfo.ts
Labels: bug, picking

#13144 Take into account adaptWidth/HeightToChildren in the StackPanel
  packages/dev/gui/src/2D/controls/stackPanel.ts
Labels: bug, gui

#13148 InputManager: Reset Swipe Status if we skip the next Observable notify
  packages/dev/core/src/Inputs/scene.inputManager.ts
Labels: bug, inputs

#13146 Update Pressure Observer to latest version of the WICG spec
  packages/dev/core/src/LibDeclarations/browser.d.ts
  packages/dev/core/src/Misc/PerformanceViewer/performanceViewerCollectionStrategies.ts
  packages/dev/core/src/Misc/computePressure.ts
  packages/dev/core/src/Misc/index.ts
  packages/dev/core/src/Misc/pressureObserverWrapper.ts
  packages/dev/core/src/scene.ts
  packages/dev/inspector/src/components/actionTabs/tabs/performanceViewer/performanceViewerComponent.tsx
Labels: bug, performance viewer

#13156 ParticleSystem: Add BILLBOARDMODE_STRETCHED_LOCAL mode
  packages/dev/core/src/Engines/constants.ts
  packages/dev/core/src/Particles/particleSystem.ts
  packages/dev/core/src/Shaders/particles.vertex.fx
Labels: particles, new feature

#13162 Fix Camera Order Back Compat
  packages/dev/core/src/Debug/debugLayer.ts
  packages/dev/core/src/scene.ts
  packages/dev/inspector/src/components/sceneExplorer/entities/sceneTreeItemComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/sceneExplorerComponent.tsx
  packages/dev/inspector/src/inspector.ts
Labels: bug, gizmos

#13124 Vsm state view wip
  packages/dev/sharedUiComponents/src/components/layout/FlexibleTab.tsx
  packages/dev/sharedUiComponents/src/components/layout/FlexibleTabsContainer.tsx
  packages/dev/sharedUiComponents/src/components/layout/types.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/tools/vsm/README.md
  packages/tools/vsm/package.json
  packages/tools/vsm/src/SceneContext.ts
  packages/tools/vsm/src/components/EditValueComponent.tsx
  packages/tools/vsm/src/components/SceneRendererComponent.tsx
  packages/tools/vsm/src/components/SelectionContext.tsx
  packages/tools/vsm/src/components/StateBehaviorViewComponent.modules.scss
  packages/tools/vsm/src/components/StateBehaviorViewComponent.tsx
  packages/tools/vsm/src/components/StatesViewComponent.modules.scss
  packages/tools/vsm/src/components/StatesViewComponent.tsx
  packages/tools/vsm/src/components/nodesDisplay/CommonStyles.modules.scss
  packages/tools/vsm/src/components/nodesDisplay/ReadyActionDisplayManager.ts
  packages/tools/vsm/src/components/nodesDisplay/StartActionDisplayManager.ts
  packages/tools/vsm/src/components/nodesDisplay/StateBlockDisplayManager.ts
  packages/tools/vsm/src/components/nodesDisplay/ValueBlockDisplayManager.ts
  packages/tools/vsm/src/components/nodesDisplay/registerToDisplayLedger.ts
  packages/tools/vsm/src/components/types.ts
  packages/tools/vsm/src/initialLayout.tsx
  packages/tools/vsm/src/workbench.tsx
Labels: skip changelog

#13165 (Local only) Fix ktx and loaders local-dev references
  packages/tools/babylonServer/src/ktx2Decoder/index.ts
  packages/tools/babylonServer/src/loaders/index-dev.ts
Labels: skip changelog

#13166 Different ports for our hosted tools
  .vscode/launch.json
  packages/tools/guiEditor/webpack.config.js
  packages/tools/nodeEditor/webpack.config.js
  packages/tools/playground/webpack.config.js
  packages/tools/sandbox/webpack.config.js
  packages/tools/vsm/webpack.config.js
Labels: new feature

#13168 WIP VSM Initial definitions of Actions, Triggers and States
  packages/dev/sharedUiComponents/src/components/bars/CommandBarComponent.tsx
  packages/tools/vsm/src/StateMachineContext.ts
  packages/tools/vsm/src/actions/ActionCoordinator.ts
  packages/tools/vsm/src/actions/BaseBehavior.ts
  packages/tools/vsm/src/actions/actions/BaseAction.ts
  packages/tools/vsm/src/actions/actions/ExecuteCodeAction.ts
  packages/tools/vsm/src/actions/actions/LogAction.ts
  packages/tools/vsm/src/actions/actions/SetPositionAction.ts
  packages/tools/vsm/src/actions/triggers/BaseTrigger.ts
  packages/tools/vsm/src/actions/triggers/ClickTrigger.ts
  packages/tools/vsm/src/components/EditValueComponent.tsx
  packages/tools/vsm/src/components/NodeListComponent.modules.scss
  packages/tools/vsm/src/components/NodeListComponent.tsx
  packages/tools/vsm/src/components/StateBehaviorViewComponent.tsx
  packages/tools/vsm/src/components/StatesViewComponent.tsx
  packages/tools/vsm/src/components/imgs/pauseIcon.svg
  packages/tools/vsm/src/components/imgs/playIcon.svg
  packages/tools/vsm/src/components/nodesDisplay/StateBlockDisplayManager.ts
  packages/tools/vsm/src/components/nodesDisplay/ValueBlockDisplayManager.ts
  packages/tools/vsm/src/components/nodesDisplay/registerToDisplayLedger.ts
  packages/tools/vsm/src/components/tools/useSceneNode.tsx
  packages/tools/vsm/src/components/tools/useStateMachine.tsx
  packages/tools/vsm/src/initialLayout.tsx
  packages/tools/vsm/src/stateMachine/State.ts
  packages/tools/vsm/src/stateMachine/StateMachine.ts
  packages/tools/vsm/src/testComponent.tsx
  packages/tools/vsm/src/workbench.tsx
Labels: skip changelog

#13170 fixing screen coverage LOD for ortho camera
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug, rendering engine

#13175 ADT: Added check to attachToMesh to prevent potential memory leak
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
Labels: bug, inputs, texture

#13176 UniformBuffer: Improve error message in updateUniformArray
  packages/dev/core/src/Materials/uniformBuffer.ts
Labels: skip changelog

#13178 fix nightly for BN
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Shaders/ShadersInclude/hdrFilteringFunctions.fx
  packages/dev/core/src/Shaders/ShadersInclude/helperFunctions.fx
  packages/dev/core/src/Shaders/ShadersInclude/mrtFragmentDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/shadowsFragmentFunctions.fx
  packages/dev/core/src/Shaders/fxaa.fragment.fx
  packages/dev/core/src/Shaders/spriteMap.fragment.fx
Labels: bug, native

#13179 Fix bug rendering transparent meshes using their own materials in effect layer
  packages/dev/core/src/Layers/effectLayer.ts
Labels: bug, post-process

#13177 Lights: Add support for multiple shadow generators
  packages/dev/core/src/Lights/Shadows/cascadedShadowGenerator.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Lights/Shadows/shadowGeneratorSceneComponent.ts
  packages/dev/core/src/Lights/light.ts
  packages/dev/core/src/Lights/pointLight.ts
  packages/dev/core/src/Materials/materialHelper.ts
  packages/dev/core/src/Meshes/abstractMesh.ts
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/core/src/Misc/sceneRecorder.ts
  packages/tools/tests/test/visualization/ReferenceImages/multiSGPerLight.png
  packages/tools/tests/test/visualization/config.json
  packages/tools/viewer/src/managers/sceneManager.ts
Labels: bug, rendering engine

#13187 NME: Fix preview not updated when changing the clamp settings in the Texture block
  packages/tools/nodeEditor/src/graphSystem/properties/texturePropertyTabComponent.tsx
Labels: bug, nme

#13183 NME: fix wrong lighting for some of the preview meshes
  .gitignore
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
Labels: nme, skip changelog

#13191 WebGPU: Add support for GLES3 to WebGPU GLSL processing
  packages/dev/core/src/Engines/Processors/iShaderProcessor.ts
  packages/dev/core/src/Engines/Processors/shaderCodeNode.ts
  packages/dev/core/src/Engines/Processors/shaderProcessor.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsGLSL.ts
Labels: new feature, WebGPU

#13192 Add information to Matrix API
  packages/dev/core/src/Maths/math.vector.ts
Labels: skip changelog

#13186 NME: fix wrong perturbed normals when using pre-existing tangents
  packages/dev/core/src/Materials/Node/Blocks/Fragment/perturbNormalBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/anisotropyBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/clearCoatBlock.ts
Labels: bug, nme
