Repository BabylonJS/Babylon.js, pull requests merged in 2022-06, with the labels that each got.

#12621 Scene.multiPickWithRay signature correction
  packages/dev/core/src/Culling/ray.ts
Labels: bug

#12598 Added a few methods to Quaternion and Vector3
  .gitignore
  packages/dev/core/src/Maths/math.vector.ts
Labels: enhancement, rendering engine

#12625 Improve CheckIsReady in scene
  packages/dev/core/src/Loading/Plugins/babylonFileLoader.ts
  packages/dev/core/src/Materials/Textures/cubeTexture.ts
  packages/dev/core/src/Misc/sceneSerializer.ts
  packages/dev/core/src/scene.ts
Labels: enhancement, rendering engine

#12632 Serialize iridescene in PBR materials
  packages/dev/core/src/Materials/PBR/pbrMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrMetallicRoughnessMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrSpecularGlossinessMaterial.ts
Labels: bug, materials

#12613 [XR] No need to clear (depth) in utility layer
  packages/dev/core/src/Rendering/utilityLayerRenderer.ts
Labels: bug, VR/AR/XR

#12644 Fixed GPU Gems URL in API docs
  packages/dev/core/src/PostProcesses/volumetricLightScatteringPostProcess.ts
Labels: bug, documentation

#12649 Camera: Added divide by zero check FreeCameraTouchInput
  packages/dev/core/src/Cameras/Inputs/freeCameraTouchInput.ts
Labels: bug

#12645 Fix dirty on inactive meshes
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/Meshes/subMesh.ts
Labels: bug, materials

#12655 Camera: Modified isMouseEvent bool logic for Safari
  packages/dev/core/src/Cameras/Inputs/freeCameraTouchInput.ts
Labels: bug

#12658 update dependencies
  package-lock.json
  package.json
  packages/dev/sharedUiComponents/package.json
  packages/public/@babylonjs/core/package.json
  packages/public/@babylonjs/gui/package.json
  packages/public/@babylonjs/loaders/package.json
  packages/public/@babylonjs/materials/package.json
  packages/public/@babylonjs/post-processes/package.json
  packages/public/@babylonjs/procedural-textures/package.json
  packages/public/@babylonjs/serializers/package.json
  packages/public/@babylonjs/viewer/package.json
  packages/public/babylonjs-viewer-assets/package.json
  packages/public/umd/babylonjs-gui-editor/package.json
  packages/public/umd/babylonjs-gui/package.json
  packages/public/umd/babylonjs-inspector/package.json
  packages/public/umd/babylonjs-ktx2decoder/package.json
  packages/public/umd/babylonjs-loaders/package.json
  packages/public/umd/babylonjs-materials/package.json
  packages/public/umd/babylonjs-node-editor/package.json
  packages/public/umd/babylonjs-post-process/package.json
  packages/public/umd/babylonjs-procedural-textures/package.json
  packages/public/umd/babylonjs-serializers/package.json
  packages/public/umd/babylonjs-viewer/package.json
  packages/public/umd/babylonjs/package.json
  packages/tools/babylonServer/package.json
  packages/tools/devHost/package.json
  packages/tools/guiEditor/package.json
  packages/tools/ktx2Decoder/package.json
  packages/tools/nodeEditor/package.json
  packages/tools/playground/package.json
  packages/tools/reflector/package.json
  packages/tools/sandbox/package.json
  packages/tools/viewer/package.json
Labels: skip changelog

#12641 Added Quaternion support in `ShaderMaterial`
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Maths/math.vector.ts
Labels: enhancement, materials

#12670 [GUI] Lines array is generated later
  packages/dev/gui/src/2D/controls/textBlock.ts
Labels: skip changelog

#12671 webgpu update
  packages/dev/core/src/Engines/WebGPU/webgpuConstants.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/LibDeclarations/webgpu.d.ts
  packages/tools/babylonServer/public/twgsl/twgsl.js
  packages/tools/babylonServer/public/twgsl/twgsl.wasm
Labels: bug, WebGPU

#12672 fix cache miss with instances out of frustrum
  packages/dev/core/src/Materials/Background/backgroundMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/effect.ts
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/materials/src/cell/cellMaterial.ts
  packages/dev/materials/src/fire/fireMaterial.ts
  packages/dev/materials/src/fur/furMaterial.ts
  packages/dev/materials/src/gradient/gradientMaterial.ts
  packages/dev/materials/src/grid/gridMaterial.ts
  packages/dev/materials/src/lava/lavaMaterial.ts
  packages/dev/materials/src/mix/mixMaterial.ts
  packages/dev/materials/src/normal/normalMaterial.ts
  packages/dev/materials/src/shadowOnly/shadowOnlyMaterial.ts
  packages/dev/materials/src/simple/simpleMaterial.ts
  packages/dev/materials/src/terrain/terrainMaterial.ts
  packages/dev/materials/src/triPlanar/triPlanarMaterial.ts
  packages/dev/materials/src/water/waterMaterial.ts
Labels: bug

#12674 createTexture onLoad callback passes the texture as arguments
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/nullEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/Node/Blocks/colorMergerBlock.ts
Labels: enhancement, texture

#12682 Wrong rotation offset camera correction
  packages/dev/serializers/src/glTF/2.0/glTFExporter.ts
Labels: bug

#12688 Fix parallaxOcclusion not being reset
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
Labels: bug, materials

#12684 Fix issue with glTF skin node/mesh metadata
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: bug

#12690 Fix serialization when objects have InstancedMesh parents
  packages/dev/core/src/Cameras/camera.ts
  packages/dev/core/src/Lights/light.ts
  packages/dev/core/src/Loading/Plugins/babylonFileLoader.ts
  packages/dev/core/src/Meshes/instancedMesh.ts
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/core/src/Meshes/transformNode.ts
  packages/dev/core/src/node.ts
  packages/tools/tests/test/visualization/ReferenceImages/serializeAndLoadInstancedHierarchy.png
  packages/tools/tests/test/visualization/config.json
Labels: bug

#12693 Added code to track buttons pressed while meta key is active on MacOS
  packages/dev/core/src/DeviceInput/InputDevices/webDeviceInputSystem.ts
Labels: bug

#12694 Only export material from mesh with geometry
  packages/dev/serializers/src/glTF/2.0/glTFExporter.ts
  packages/dev/serializers/src/glTF/2.0/glTFMaterialExporter.ts
Labels: bug

#12696 DeviceInputSystem: Fixed Passive Support Check to prevent Violation Warning
  packages/dev/core/src/DeviceInput/InputDevices/webDeviceInputSystem.ts
Labels: bug

#12701 Fix loading skinned model with multiple primitives
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: bug
