Repository BabylonJS/Babylon.js, pull requests merged in 2022-04, with the labels that each got.

#12318 Added a new flag for checking double sided mesh in collision
  packages/dev/core/src/Collisions/collider.ts
Labels: new feature

#12313 [GUI Editor] update the give feedback link to the beta thread
  packages/tools/guiEditor/src/components/commandBarComponent.tsx
Labels: gui editor

#12314 [GUI Editor] Update Display Grid Parameters
  packages/dev/sharedUiComponents/src/imgs/displayGridLine1Icon.svg
  packages/dev/sharedUiComponents/src/imgs/displayGridLine2Icon.svg
  packages/dev/sharedUiComponents/src/imgs/frequencyIcon.svg
  packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/displayGridPropertyGridComponent.tsx
Labels: gui editor

#12341 Playground fails permanently when Babylon.js 3.3 is selected
  packages/tools/playground/public/index.js
Labels: new feature

#12339 [XR] rotate the hand mesh opposed to the based transform node.
  packages/dev/core/src/XR/features/WebXRHandTracking.ts
Labels: bug, VR/AR/XR

#12340 [XR] assign the number of textures correctly
  packages/dev/core/src/Materials/Textures/MultiviewRenderTarget.ts
Labels: bug, VR/AR/XR

#12344 Let AssetContainer add/instantiate/remove individual components
  packages/dev/core/src/assetContainer.ts
Labels: new feature

#12346 Fix Color3.asArray, Color4.asArray, Color4.toArray and docs for Color…
  packages/dev/core/src/Maths/math.color.ts
Labels: bug, math

#12345 [GUI] use ignoreAdaptiveScaling on containers width adaptWidthToChildren or adaptHeightToChildren
  packages/dev/gui/src/2D/controls/container.ts
Labels: bug, gui

#12351 [Build] Allow editors packages to be included in a single project
  packages/dev/buildTools/src/generateDeclaration.ts
  packages/dev/buildTools/src/packageMapping.ts
Labels: bug, build

#12352 Fix SSAORenderingPipeline with multi cameras
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssaoRenderingPipeline.ts
Labels: bug

#12348 [GUI] On parse, reconnects the keys of the virtual keyboard
  packages/dev/gui/src/2D/controls/virtualKeyboard.ts
Labels: gui

#12353 [Build] add timestamp to CDN assets
  packages/dev/buildTools/src/prepareSnapshot.ts
  packages/tools/guiEditor/public/index.js
  packages/tools/nodeEditor/public/index.js
  packages/tools/playground/public/index.js
  packages/tools/playground/src/tools/monacoManager.ts
  packages/tools/sandbox/public/index.js
Labels: build, new feature

#12356 Fix default settings in video texture
  packages/dev/core/src/Materials/Textures/videoTexture.ts
Labels: bug, texture

#12359 Fix #12354
  packages/tools/nodeEditor/src/diagram/nodeLink.ts
Labels: bug

#12365 Add support for Iridescence in PBR and GLTF
  packages/dev/core/src/Materials/Node/Blocks/PBR/iridescenceBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/Materials/PBR/index.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrIridescenceConfiguration.ts
  packages/dev/core/src/Materials/materialFlags.ts
  packages/dev/core/src/Materials/materialPluginFactoryExport.ts
  packages/dev/core/src/Rendering/boundingBoxRenderer.ts
  packages/dev/core/src/Shaders/ShadersInclude/boundingBoxRendererUboDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/helperFunctions.fx
  packages/dev/core/src/Shaders/ShadersInclude/lightFragment.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrBRDFFunctions.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockIridescence.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrDirectLightingFunctions.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrDirectLightingSetupFunctions.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrFragmentDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrFragmentSamplersDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrVertexDeclaration.fx
  packages/dev/core/src/Shaders/pbr.fragment.fx
  packages/dev/core/src/Shaders/pbr.vertex.fx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/pbrMaterialPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/tools/gltfComponent.tsx
  packages/dev/inspector/src/components/globalState.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_materials_iridescence.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/index.ts
  packages/dev/serializers/src/glTF/2.0/Extensions/KHR_materials_iridescence.ts
  packages/dev/serializers/src/glTF/2.0/Extensions/index.ts
  packages/public/glTF2Interface/babylon.glTF2Interface.d.ts
  packages/tools/tests/test/visualization/ReferenceImages/iridescence.png
  packages/tools/tests/test/visualization/ReferenceImages/iridescence_gltf.png
  packages/tools/tests/test/visualization/ReferenceImages/iridescence_nme.png
  packages/tools/tests/test/visualization/config.json
Labels: materials, glTF, new feature, nme

#12367 Revert the missing fix and add some logs
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug

#12370 Fix babylon mesh parsing, materials were not reattached.
  packages/dev/core/src/Loading/Plugins/babylonFileLoader.ts
Labels: bug, loaders

#12369 Fix minor shader compiler issues
  packages/dev/core/src/Engines/Processors/shaderCodeCursor.ts
Labels: bug

#12376 [Inspector] Add some missing onPropertyChangedObservable to inspector…
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/lights/commonLightPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/texturePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/meshPropertyGridComponent.tsx
Labels: new feature

#12373 [NME] Different selection priorities for nodes and frames dependent of marquee or click selecting
  packages/tools/nodeEditor/src/diagram/graphCanvas.tsx
  packages/tools/nodeEditor/src/diagram/graphFrame.ts
  packages/tools/nodeEditor/src/diagram/graphNode.ts
  packages/tools/nodeEditor/src/globalState.ts
Labels: bug

#12385 New flag to preserve scaling when using gizmos
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
  packages/dev/core/src/Gizmos/gizmo.ts
Labels: enhancement

#12391 Fix #12174
  packages/tools/playground/src/tools/loadManager.ts
  packages/tools/playground/src/tools/saveManager.ts
Labels: bug

#12390 [Engine] Add a flag to use opacity instead of diffuse texture for transparent shadows.
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
Labels: enhancement, rendering engine

#12388 Add normal input to clear coat Block
  packages/dev/core/src/Materials/Node/Blocks/PBR/clearCoatBlock.ts
Labels: new feature, nme

#12392 [GUI] Skip invisible or unrenderable children in layout calculations
  packages/dev/gui/src/2D/controls/container.ts
Labels: bug, gui

#12395 Fix #12394
  packages/dev/core/src/Debug/debugLayer.ts
Labels: new feature

#12362 ktxTextureLoader: Mark _useSRGBBuffers when loading an SRGB-enabled texture format
  packages/dev/core/src/Engines/constants.ts
  packages/dev/core/src/Materials/Textures/Loaders/ktxTextureLoader.ts
  packages/dev/core/src/Misc/khronosTextureContainer.ts
Labels: bug

#12399 [ACE] Deselect keys when active channels are changed.
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/animations/curveEditor/context.ts
Labels: bug

#12402 Fix empty screenshot when enabling antialiasing
  packages/dev/core/src/Misc/screenshotTools.ts
Labels: bug

#12400 [GUI] Block pointer events to scene when pointer is captured
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
Labels: bug, gui

#12403 Scaling preservation fix for boundingBoxGizmo
  packages/dev/core/src/Gizmos/axisScaleGizmo.ts
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
  packages/dev/core/src/Gizmos/gizmo.ts
  packages/dev/core/src/Gizmos/planeRotationGizmo.ts
Labels: enhancement

#12406 Fix Transparent shadows
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Materials/uniformBuffer.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_materials_iridescence.ts
  packages/dev/serializers/src/glTF/2.0/Extensions/KHR_materials_iridescence.ts
  packages/public/glTF2Interface/babylon.glTF2Interface.d.ts
Labels: bug, materials, shadows

#12404 [GUI] fix container regression
  packages/dev/gui/src/2D/controls/container.ts
Labels: bug, gui

#12397 DeviceInputSystem: Remove pollInput calls for MouseWheel from EventFactory
  packages/dev/core/src/DeviceInput/Helpers/eventFactory.ts
  packages/dev/core/src/DeviceInput/InputDevices/deviceTypes.ts
  packages/dev/core/src/DeviceInput/InputDevices/nativeDeviceInputSystem.ts
Labels: inputs, breaking change

#12409 Inspector: render N/A for internal texture unique ID when internal texture is undefined
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/texturePropertyGridComponent.tsx
Labels: bug, inspector

#12410 Fix uninitialized last ray for PointerDragBehavior
  packages/dev/core/src/Behaviors/Meshes/pointerDragBehavior.ts
Labels: bug

#12418 Added function call to focus on canvas when setting PointerLock
  packages/dev/core/src/Engines/engine.ts
Labels: bug

#12421 Remove some unnecessary computations
  packages/dev/core/src/Maths/math.vector.ts
  packages/dev/core/src/Meshes/subMesh.ts
  packages/dev/core/src/Rendering/renderingGroup.ts
  packages/dev/core/src/scene.ts
Labels: new feature

#12425 Fix #12423
  packages/dev/core/src/Materials/Textures/cubeTexture.ts
  packages/tools/nodeEditor/src/diagram/display/textureDisplayManager.ts
Labels: bug

#12427 Fix effectLayer vertex alpha detection
  packages/dev/core/src/Layers/effectLayer.ts
Labels: bug, rendering engine

#12442 [Bug] Fix OimoJS plugin syncMeshWithImpostor method.
  packages/dev/core/src/Physics/Plugins/oimoJSPlugin.ts
Labels: bug, physics

#12440 [XR] make sure pointer up only triggers once
  packages/dev/core/src/XR/features/WebXRControllerPointerSelection.ts
Labels: bug

#12452 WebGPU: more changes and fixes for stencil support
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureHelper.ts
  packages/dev/core/src/Engines/constants.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/texturePropertyGridComponent.tsx
Labels: bug, WebGPU

#12460 Fix GetAngleBetweenVectors precision issue
  packages/dev/core/src/Maths/math.vector.ts
Labels: bug, rendering engine

#12459 WebGPU: Fix terrain erosion visualization test
  packages/tools/tests/test/visualization/webgpu.json
Labels: bug, WebGPU
