Repository BabylonJS/Babylon.js, pull requests merged in 2022-11, with the labels that each got.

#13193 Reduce memory usage in bakeTransformIntoVertices
  packages/dev/core/src/Meshes/mesh.ts
Labels: rendering engine, optimizations

#13197 Shadows: Fix transparent shadows with ALPHABLEND transparency mode
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Shaders/shadowMap.fragment.fx
  packages/dev/core/src/Shaders/shadowMap.vertex.fx
Labels: bug, shadows

#13196 Fix animatable loop
  packages/dev/core/src/Animations/animatable.ts
Labels: bug, animations

#13199 AssetContainer: Fix crash when calling moveAllFromScene if environmentTexture is present
  packages/dev/core/src/assetContainer.ts
Labels: bug, assets

#13200 Motion blur: Fix motion blur when not in the "object based" mode
  packages/dev/core/src/PostProcesses/motionBlurPostProcess.ts
  packages/dev/core/src/Shaders/motionBlur.fragment.fx
Labels: bug, rendering engine

#13190 Xr camera
  packages/dev/core/src/XR/webXRCamera.ts
Labels: bug, VR/AR/XR

#13204 fix: switch back to the main scene using multiple canvases, and rende…
  packages/dev/core/src/Engines/Extensions/engine.views.ts
Labels: bug, rendering engine

#13212 Fix camera selection in sandbox for cameras with duplicated names
  packages/tools/sandbox/src/components/footer.tsx
Labels: bug

#13213 WebGPU: Fixes errors in the console log
  packages/dev/core/src/Misc/basis.ts
  packages/dev/core/src/Shaders/ShadersInclude/bumpFragmentFunctions.fx
  packages/tools/tests/test/visualization/ReferenceImages/webgpu/dissolve effect with node material and glow layer.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#13219 MeshExploder bugfix
  packages/dev/core/src/Misc/meshExploder.ts
Labels: bug

#13218 Properly clear a selected line container component after it is seen
  packages/dev/sharedUiComponents/src/lines/lineContainerComponent.tsx
Labels: bug, inspector, sandbox

#13220 Support correct spelling on center
  packages/dev/core/src/Materials/imageProcessingConfiguration.ts
  packages/dev/core/src/PostProcesses/imageProcessingPostProcess.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/postProcesses/defaultRenderingPipelinePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/scenePropertyGridComponent.tsx
  packages/tools/viewer/public/renderOnlyViewer.html
  packages/tools/viewer/src/configuration/interfaces/imageProcessingConfiguration.ts
  packages/tools/viewer/src/configuration/types/extended.ts
Labels: enhancement, post-process

#13225 STL file loader isBinary update
  packages/dev/loaders/src/STL/stlFileLoader.ts
Labels: skip changelog

#13227 EffectRender: Fix culling state not reset properly
  packages/dev/core/src/Materials/effectRenderer.ts
Labels: bug, rendering engine

#13223 Graph Overhaul in VSM
  package-lock.json
  packages/dev/sharedUiComponents/src/components/layout/FlexibleTabsContainer.modules.scss
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/GraphConnectorHandle.modules.scss
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/GraphConnectorHandle.tsx
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/GraphContainer.modules.scss
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/GraphContainer.tsx
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/GraphContextManager.ts
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/GraphLine.tsx
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/GraphLinesContainer.tsx
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/GraphNode.modules.scss
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/GraphNode.tsx
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/GraphNodesContainer.tsx
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/NodeRenderer.tsx
  packages/dev/sharedUiComponents/src/components/reactGraphSystem/useGraphContext.ts
  packages/tools/vsm/src/components/EditValueComponent.tsx
  packages/tools/vsm/src/components/SceneRendererComponent.tsx
  packages/tools/vsm/src/components/SelectionContext.tsx
  packages/tools/vsm/src/components/StateBehaviorNodeRenderer.tsx
  packages/tools/vsm/src/components/StateBehaviorViewComponent.modules.scss
  packages/tools/vsm/src/components/StateBehaviorViewComponent.tsx
  packages/tools/vsm/src/components/StateViewNodeRenderer.tsx
  packages/tools/vsm/src/components/StatesViewComponent.modules.scss
  packages/tools/vsm/src/components/StatesViewComponent.tsx
  packages/tools/vsm/src/components/nodesDisplay/CommonStyles.modules.scss
  packages/tools/vsm/src/components/nodesDisplay/ReadyActionDisplayManager.ts
  packages/tools/vsm/src/components/nodesDisplay/SetPositionBlock.tsx
  packages/tools/vsm/src/components/nodesDisplay/StartActionDisplayManager.ts
  packages/tools/vsm/src/components/nodesDisplay/StateBlockDisplayManager.ts
  packages/tools/vsm/src/components/nodesDisplay/registerToDisplayLedger.ts
  packages/tools/vsm/src/components/tools/useSceneNode.ts
  packages/tools/vsm/src/components/tools/useSelectedAction.ts
  packages/tools/vsm/src/components/tools/useSelectedState.ts
  packages/tools/vsm/src/components/tools/useStateMachine.ts
  packages/tools/vsm/src/components/types.ts
  packages/tools/vsm/src/context/ActionSelectionContext.ts
  packages/tools/vsm/src/context/SceneContext.ts
  packages/tools/vsm/src/context/StateMachineContext.ts
  packages/tools/vsm/src/context/StateSelectionContext.tsx
  packages/tools/vsm/src/initialLayout.tsx
  packages/tools/vsm/src/stateMachine/State.ts
  packages/tools/vsm/src/stateMachine/StateMachine.ts
  packages/tools/vsm/src/workbench.tsx
Labels: skip changelog

#13236 ShadowDepthWrapper: Fix shadows when wrapping a material using custom material plugins
  packages/dev/core/src/Engines/Processors/shaderProcessor.ts
  packages/dev/core/src/Materials/effect.ts
  packages/dev/core/src/Materials/shadowDepthWrapper.ts
Labels: bug, rendering engine, shadows

#13241 Support matrix in reciproqual block
  packages/dev/core/src/Materials/Node/Blocks/reciprocalBlock.ts
Labels: enhancement, nme

#13245 Extend dragPlanePoint doc on onDrag*Observables
  packages/dev/core/src/Behaviors/Meshes/pointerDragBehavior.ts
Labels: documentation

#13242 Fix #13239 Playground Warning
  packages/tools/playground/src/components/commandBarComponent.tsx
  packages/tools/playground/src/components/commandDropdownComponent.tsx
  packages/tools/playground/src/tools/utilities.ts
Labels: skip changelog

#13246 array flat polyfill for Chakra
  packages/dev/core/src/Engines/nativeEngine.ts
Labels: native

#13233 Fix for FreeCameraMouseInput fluxuating input on multi-touch
  packages/dev/core/src/Cameras/Inputs/freeCameraMouseInput.ts
  packages/dev/core/test/unit/Cameras/babylon.freeCameraInputs.test.ts
Labels: bug, inputs

#13250 InputManager: Fixed up/down picking on callback
  packages/dev/core/src/Inputs/scene.inputManager.ts
  packages/dev/core/test/unit/DeviceInput/babylon.inputManager.test.ts
Labels: bug, inputs

#13252 Better handling of shader code that does not have a main function
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessor.ts
Labels: skip changelog

#13254 WebGPU: Improve copy video to texture
  packages/dev/core/src/Engines/Extensions/engine.videoTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.videoTexture.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureHelper.ts
  packages/dev/core/src/Materials/Textures/htmlElementTexture.ts
  packages/dev/core/src/Materials/Textures/videoTexture.ts
Labels: enhancement, WebGPU

#13249 Support ClipPlanes in Materials
  packages/dev/core/src/Culling/boundingInfo.ts
  packages/dev/core/src/Layers/effectLayer.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Materials/Background/backgroundMaterial.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/clipPlanesBlock.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/clipPlaneMaterialHelper.ts
  packages/dev/core/src/Materials/index.ts
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/Materials/materialHelper.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/Materials/thinMaterialHelper.ts
  packages/dev/core/src/Meshes/linesMesh.ts
  packages/dev/core/src/Particles/baseParticleSystem.ts
  packages/dev/core/src/Particles/gpuParticleSystem.ts
  packages/dev/core/src/Particles/particleSystem.ts
  packages/dev/core/src/Rendering/depthRenderer.ts
  packages/dev/core/src/Rendering/outlineRenderer.ts
  packages/dev/materials/src/cell/cellMaterial.ts
  packages/dev/materials/src/fire/fireMaterial.ts
  packages/dev/materials/src/fur/furMaterial.ts
  packages/dev/materials/src/gradient/gradientMaterial.ts
  packages/dev/materials/src/grid/gridMaterial.ts
  packages/dev/materials/src/lava/lavaMaterial.ts
  packages/dev/materials/src/mix/mixMaterial.ts
  packages/dev/materials/src/normal/normalMaterial.ts
  packages/dev/materials/src/shadowOnly/shadowOnlyMaterial.ts
  packages/dev/materials/src/simple/simpleMaterial.ts
  packages/dev/materials/src/sky/skyMaterial.ts
  packages/dev/materials/src/terrain/terrainMaterial.ts
  packages/dev/materials/src/triPlanar/triPlanarMaterial.ts
  packages/dev/materials/src/water/waterMaterial.ts
Labels: materials, new feature

#13251 Fix dump tools premultiplied alpha.
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/Misc/dumpTools.ts
  packages/dev/core/src/Misc/environmentTextureTools.ts
  packages/dev/core/src/Misc/index.ts
  packages/dev/core/src/Misc/screenshotTools.ts
  packages/dev/core/src/Misc/tools.ts
  packages/dev/serializers/src/glTF/2.0/glTFMaterialExporter.ts
Labels: bug, exporters

#13256 PostProcess: Add hooks to alter shader code used by post processes
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/Shaders/ShadersInclude/imageProcessingFunctions.fx
  packages/dev/core/src/Shaders/circleOfConfusion.fragment.fx
Labels: enhancement, post-process

#13257 Fix IKController with leaf node
  packages/dev/core/src/Bones/boneIKController.ts
Labels: bug, animations

#13259 Add Sprite Manager Metadata
  packages/dev/core/src/Sprites/spriteManager.ts
Labels: enhancement, sprite

#13261 PBR material: Add missing test for the emissive texture in hasTexture
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
Labels: bug, materials

#13262 Matrix: Update the doc for the LookAt functions
  packages/dev/core/src/Maths/math.vector.ts
Labels: skip changelog

#13264 Add confirmation message in PG when switching version
  packages/tools/playground/src/components/commandBarComponent.tsx
Labels: skip changelog

#13267 Fix prepareDefinesForClipPlanes returning true too often
  packages/dev/core/src/Materials/clipPlaneMaterialHelper.ts
Labels: skip changelog

#13276 Couple tiny fixes
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/Textures/videoTexture.ts
  packages/dev/core/test/unit/Materials/PBR/babylon.PBRMaterial.test.ts
Labels: skip changelog

#13272 NME: multiple changes to support ray marching in the NME
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsGLSL.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/lightBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/reflectionTextureBaseBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/reflectionTextureBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/fragDepthBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/index.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/shadowMapBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/reflectionBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/biPlanarBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/index.ts
  packages/dev/core/src/Materials/Node/Blocks/triPlanarBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildState.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildStateSharedData.ts
  packages/dev/core/src/Materials/Node/nodeMaterialDecorator.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/materialHelper.ts
  packages/dev/core/src/Materials/shadowDepthWrapper.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/tools/nodeEditor/src/blockTools.ts
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/display/textureDisplayManager.modules.scss
  packages/tools/nodeEditor/src/graphSystem/display/textureDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/properties/genericNodePropertyComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/properties/texturePropertyTabComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/registerToDisplayLedger.ts
  packages/tools/nodeEditor/src/graphSystem/registerToPropertyLedger.ts
Labels: new feature, nme

#13283 Observable: Do not include deleted observers in hasObservers result
  packages/dev/core/src/Misc/observable.ts
Labels: bug, design

#13282 Mesh: Add forceWorldMatrixInstancedBufferUpdate property
  packages/dev/core/src/Meshes/mesh.ts
Labels: rendering engine, new feature

#13286 Ensure bloom blur size is consistent across hardware scaling levels
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/defaultRenderingPipeline.ts
Labels: bug, post-process

#13287 Bump: Fix black spots in bump when no uv gradients
  packages/dev/core/src/Shaders/ShadersInclude/bumpFragmentMainFunctions.fx
Labels: bug, rendering engine

#13289 RTT: Make sure we increment scene frameId even in "check readiness" mode
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
Labels: bug, rendering engine

#13293 Cameras: Modified cameras to work under onPointerObservable
  packages/dev/core/src/Cameras/Inputs/BaseCameraMouseWheelInput.ts
  packages/dev/core/src/Cameras/Inputs/BaseCameraPointersInput.ts
  packages/dev/core/src/Cameras/Inputs/arcRotateCameraMouseWheelInput.ts
  packages/dev/core/src/Cameras/Inputs/flyCameraMouseInput.ts
  packages/dev/core/src/Cameras/Inputs/followCameraMouseWheelInput.ts
  packages/dev/core/src/Cameras/Inputs/freeCameraMouseInput.ts
  packages/dev/core/src/Cameras/Inputs/freeCameraTouchInput.ts
  packages/dev/core/src/Inputs/scene.inputManager.ts
  packages/dev/core/src/scene.ts
  packages/dev/core/test/unit/Cameras/babylon.freeCameraInputs.test.ts
Labels: bug, inputs

#13295 InputManager: Fix Order and Execution of onPrePointerObservable
  packages/dev/core/src/Inputs/scene.inputManager.ts
  packages/dev/core/test/unit/DeviceInput/babylon.inputManager.test.ts
Labels: bug, inputs

#13299 Fix Texture rebuild on context lost
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Materials/Textures/internalTexture.ts
Labels: bug, texture

#13300 Preserve camera control settings when reattaching camera controls
  packages/dev/core/src/Behaviors/Meshes/baseSixDofDragBehavior.ts
Labels: bug, gizmos

#13302 Fix #13301
  packages/dev/inspector/src/components/sceneExplorer/entities/sceneTreeItemComponent.tsx
Labels: skip changelog
