Repository BabylonJS/Babylon.js, pull requests merged in 2022-07, with the labels that each got.

#12703 Camera: Remove code execute preventDefault for wheel events
  packages/dev/core/src/Cameras/Inputs/BaseCameraMouseWheelInput.ts
  packages/dev/core/src/Cameras/Inputs/arcRotateCameraMouseWheelInput.ts
  packages/dev/core/src/Cameras/Inputs/followCameraMouseWheelInput.ts
Labels: bug

#12709 Created Visual Tests for GUI Input and Pick Testing
  packages/tools/tests/test/visualization/ReferenceImages/guiInputTest.png
  packages/tools/tests/test/visualization/ReferenceImages/pickingVisualTest.png
  packages/tools/tests/test/visualization/config.json
Labels: gui, picking, inputs, skip changelog

#12714 Fix #12712
  packages/dev/inspector/src/components/actionTabs/tabs/gradientStepComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/textures/toolBar.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/colorGradientStepGridComponent.tsx
  packages/dev/sharedUiComponents/src/colorPicker/colorComponentEntry.tsx
  packages/dev/sharedUiComponents/src/colorPicker/colorPicker.tsx
  packages/dev/sharedUiComponents/src/colorPicker/hexColor.tsx
  packages/dev/sharedUiComponents/src/lines/colorLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/colorPickerComponent.tsx
  packages/tools/nodeEditor/src/sharedComponents/colorPickerComponent.tsx
Labels: skip changelog

#12686 Update GLTF Animation serializer to include Camera.
  packages/dev/serializers/src/glTF/2.0/glTFAnimation.ts
Labels: bug

#12720 Fix #12687
  packages/tools/nodeEditor/src/graphSystem/properties/gradientStepComponent.tsx
  packages/tools/nodeEditor/src/sharedComponents/colorPickerComponent.tsx
  packages/tools/nodeEditor/src/sharedComponents/minus.svg
  packages/tools/nodeEditor/src/sharedComponents/numericInputComponent.tsx
  packages/tools/nodeEditor/src/sharedComponents/plus.svg
Labels: bug

#12702 Initial Device Input Test Pattern Setup: Unit Tests
  packages/dev/core/src/DeviceInput/InputDevices/deviceSourceManager.ts
  packages/dev/core/src/DeviceInput/InputDevices/internalDeviceSourceManager.ts
  packages/dev/core/src/DeviceInput/InputDevices/webDeviceInputSystem.ts
  packages/dev/core/test/unit/DeviceInput/babylon.deviceInput.test.ts
Labels: inputs

#12662 Basis transcoder update
  packages/dev/core/src/Materials/Textures/Loaders/basisTextureLoader.ts
  packages/dev/core/src/Misc/basis.ts
  packages/tools/babylonServer/public/basisTranscoder/1/basis_transcoder.js
  packages/tools/babylonServer/public/basisTranscoder/1/basis_transcoder.wasm
  packages/tools/testTools/src/utils.ts
  packages/tools/testTools/src/visualizationUtils.ts
Labels: new feature

#12729 Fix delete key issue with NME
  packages/dev/inspector/src/components/actionTabs/lines/quaternionLineComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/animations/animationGroupPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/animations/animationPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/cameras/arcRotateCameraPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/cameras/commonCameraPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/customPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/layers/layerPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/lights/commonShadowLightPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/backgroundMaterialPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/commonMaterialPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/nodeMaterialPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/pbrMaterialPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/pbrMetallicRoughnessMaterialPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/pbrSpecularGlossinessMaterialPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/standardMaterialPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/texturePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/meshPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/skeletonPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/coneEmitterGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/cylinderEmitterGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/hemisphericEmitterGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/particleSystemPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/sphereEmitterGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/postProcesses/commonPostProcessPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/postProcesses/commonRenderingPipelinePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/postProcesses/defaultRenderingPipelinePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/postProcesses/lensRenderingPipelinePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/postProcesses/ssao2RenderingPipelinePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/postProcesses/ssaoRenderingPipelinePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/scenePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/sounds/soundPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/sprites/spriteManagerPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/sprites/spritePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/tools/gltfComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/toolsTabComponent.tsx
  packages/dev/sharedUiComponents/src/lines/floatLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/matrixLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/sliderLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/vector3LineComponent.tsx
  packages/dev/sharedUiComponents/src/tabs/propertyGrids/gui/commonControlPropertyGridComponent.tsx
  packages/dev/sharedUiComponents/src/tabs/propertyGrids/gui/inputTextPropertyGridComponent.tsx
  packages/tools/guiEditor/src/components/commandBarComponent.tsx
  packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/inputTextPropertyGridComponent.tsx
  packages/tools/nodeEditor/src/components/propertyTab/inputsPropertyTabComponent.tsx
  packages/tools/nodeEditor/src/components/propertyTab/properties/floatPropertyTabComponent.tsx
  packages/tools/nodeEditor/src/components/propertyTab/propertyTabComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/properties/genericNodePropertyComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/properties/gradientStepComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/properties/imageSourcePropertyTabComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/properties/inputNodePropertyComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/properties/texturePropertyTabComponent.tsx
Labels: bug

#12737 Automatically change hardware scaling based on browser zoom level
  packages/dev/core/src/Engines/thinEngine.ts
Labels: new feature

#12739 [GE] Fix gizmos on elements with padded parents
  packages/tools/guiEditor/src/diagram/gizmoGeneric.tsx
Labels: bug, gui editor

#12756 WebGPU: Comply with variable naming restrictions
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsGLSL.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
Labels: skip changelog

#12760 Expose pendingData APIs publicly
  packages/dev/core/src/Audio/sound.ts
  packages/dev/core/src/Engines/Extensions/engine.cubeTexture.ts
  packages/dev/core/src/Engines/Extensions/engine.rawTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.rawTexture.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Loading/sceneLoader.ts
  packages/dev/core/src/Materials/Textures/baseTexture.ts
  packages/dev/core/src/Meshes/geometry.ts
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/core/src/Particles/particleHelper.ts
  packages/dev/core/src/scene.ts
  packages/tools/tests/test/visualization/config.json
Labels: enhancement, rendering engine

#12762 ArcRotateCamera: Modify rotation logic to use invertRotation flag
  packages/dev/core/src/Cameras/arcRotateCamera.ts
Labels: bug

#12755 toolbar can expand now
  packages/tools/guiEditor/src/imgs/toolbarCollapseIcon.svg
  packages/tools/guiEditor/src/imgs/toolbarExpandIcon.svg
  packages/tools/guiEditor/src/main.scss
  packages/tools/guiEditor/src/workbenchEditor.tsx
Labels: new feature

#12764 Always clone skinned meshes for AssetContainer.instantiateModelsToScene
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/core/src/Meshes/transformNode.ts
  packages/dev/core/src/assetContainer.ts
Labels: bug

#12774 Check autoClear for RTT to fix utility layer on native OpenXR
  packages/dev/core/src/Rendering/utilityLayerRenderer.ts
  packages/dev/core/src/scene.ts
Labels: bug

#12773 move depth buffer to ThinEngine
  packages/dev/core/src/Engines/engine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/scene.ts
Labels: skip changelog

#12778 Add computeBoundingBox as a constructor option on SPS.
  packages/dev/core/src/Particles/solidParticleSystem.ts
Labels: enhancement

#12781 Fix crash on smooth shading for meshes with no index buffers on Babylon Native.
  packages/dev/core/src/Engines/nativeEngine.ts
Labels: bug

#12779 Gizmo/camera fixes
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
  packages/dev/core/src/scene.ts
  packages/dev/inspector/src/components/sceneExplorer/entities/sceneTreeItemComponent.tsx
Labels: bug, inspector, new feature, gizmos

#12785 Wait to add pending data to the scene before loading screen logic
  packages/dev/core/src/Loading/sceneLoader.ts
Labels: bug

#12782 Add thinInstance creation check if instanced arrays are not supported.
  packages/dev/core/src/Meshes/thinInstanceMesh.ts
Labels: bug, rendering engine

#12786 fix splice hook
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
Labels: bug, rendering engine

#12789 Fix distorted normals in large-radius flat IcoSpheres.
  packages/dev/core/src/Meshes/Builders/icoSphereBuilder.ts
Labels: bug

#12792 Vertex buffer override for native
  packages/dev/core/src/Engines/nativeEngine.ts
Labels: bug, native

#12794 Fix render method of RTT not using its active camera
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
Labels: bug

#12798 Fix gui loading from snippet
  packages/tools/guiEditor/src/diagram/workbench.tsx
Labels: bug, gui editor

#12804 Allow creation of baseTexture from internalTexture
  packages/dev/core/src/Materials/Textures/baseTexture.ts
Labels: enhancement, texture

#12805 Fix crash when loading node material with loadasync
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
Labels: bug, materials

#12808 fix native sprites
  packages/dev/core/src/Shaders/sprites.fragment.fx
Labels: skip changelog
