Repository BabylonJS/Babylon.js, pull requests merged in 2022-12, with the labels that each got.

#13275 Support create RTT from internal texture directly
  packages/dev/core/src/Engines/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/Extensions/engine.renderTargetCube.ts
  packages/dev/core/src/Engines/Native/nativeHardwareTexture.ts
  packages/dev/core/src/Engines/Native/nativeInterfaces.ts
  packages/dev/core/src/Engines/Native/nativePipelineContext.ts
  packages/dev/core/src/Engines/Native/nativeRenderTargetWrapper.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTargetCube.ts
  packages/dev/core/src/Engines/engine.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/nullEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/Materials/Textures/textureCreationOptions.ts
Labels: new feature

#13306 Fixed NativeEngine render target assignment
  packages/dev/core/src/Engines/nativeEngine.ts
Labels: bug

#13308 Fix restore context in WebGL1 when using non POT textures
  packages/dev/core/src/Engines/engine.ts
  packages/dev/core/src/Engines/thinEngine.ts
Labels: bug, rendering engine

#13312 Add playback rate getter
  packages/dev/core/src/Audio/sound.ts
Labels: enhancement, audio

#13311 Scene: Make sure dispose cleans up everything even if running custom code raises an exception
  packages/dev/core/src/scene.ts
Labels: skip changelog

#13291 Add a Fluid Renderer component
  packages/dev/core/src/Misc/copyTextureToTexture.ts
  packages/dev/core/src/Particles/IParticleSystem.ts
  packages/dev/core/src/Particles/gpuParticleSystem.ts
  packages/dev/core/src/Particles/particleSystem.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderer.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingDepthTextureCopy.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingObject.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingObjectCustomParticles.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingObjectParticleSystem.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingTargetRenderer.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingTextures.ts
  packages/dev/core/src/Rendering/fluidRenderer/index.ts
  packages/dev/core/src/Rendering/index.ts
  packages/dev/core/src/Shaders/copyTextureToTexture.fragment.fx
  packages/dev/core/src/Shaders/fluidRenderingBilateralBlur.fragment.fx
  packages/dev/core/src/Shaders/fluidRenderingParticleDepth.fragment.fx
  packages/dev/core/src/Shaders/fluidRenderingParticleDepth.vertex.fx
  packages/dev/core/src/Shaders/fluidRenderingParticleDiffuse.fragment.fx
  packages/dev/core/src/Shaders/fluidRenderingParticleDiffuse.vertex.fx
  packages/dev/core/src/Shaders/fluidRenderingParticleThickness.fragment.fx
  packages/dev/core/src/Shaders/fluidRenderingParticleThickness.vertex.fx
  packages/dev/core/src/Shaders/fluidRenderingRender.fragment.fx
  packages/dev/core/src/Shaders/fluidRenderingStandardBlur.fragment.fx
  packages/dev/core/src/sceneComponent.ts
  packages/tools/playground/public/textures/flare32bits.png
  packages/tools/tests/test/visualization/ReferenceImages/fluidBoxSphere.png
  packages/tools/tests/test/visualization/ReferenceImages/fluidParticleSystem.png
  packages/tools/tests/test/visualization/config.json
Labels: rendering engine, new feature

#13303 Support KHR_materials_emissive_stength in glTF export
  packages/dev/serializers/src/glTF/2.0/Extensions/KHR_materials_emissive_strength.ts
  packages/dev/serializers/src/glTF/2.0/Extensions/index.ts
Labels: enhancement, exporters, glTF

#13318 Particle System: Add a parameter to also clone textures when cloning a particle system
  packages/dev/core/src/Particles/gpuParticleSystem.ts
  packages/dev/core/src/Particles/particleSystem.ts
Labels: enhancement, particles

#13321 InputManager: Update logic for detecting when to pick
  packages/dev/core/src/Inputs/scene.inputManager.ts
  packages/dev/core/test/unit/DeviceInput/babylon.inputManager.test.ts
Labels: bug, inputs

#13322 Mirror: Fix rendering when cullBackFaces is false
  packages/dev/core/src/Materials/Textures/mirrorTexture.ts
  packages/dev/core/src/Materials/material.ts
  packages/dev/materials/src/water/waterMaterial.ts
Labels: bug, rendering engine

#13326 NME: fixed slowdowns when working in the editor
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildStateSharedData.ts
  packages/dev/core/src/Materials/Textures/baseTexture.ts
  packages/dev/core/src/Materials/Textures/internalTexture.ts
  packages/dev/core/src/Materials/Textures/texture.ts
  packages/dev/sharedUiComponents/src/lines/textInputLineComponent.tsx
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
  packages/tools/nodeEditor/src/graphSystem/properties/genericNodePropertyComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/properties/inputNodePropertyComponent.tsx
Labels: enhancement, nme

#13327 Fix: ACE always opening with the first targeted animation selected
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/animations/targetedAnimationPropertyGridComponent.tsx
Labels: bug

#13330 ArcRotateCamera: Fix lower and upper beta limit type
  packages/dev/core/src/Cameras/arcRotateCamera.ts
Labels: bug, inputs

#13332 VirtualJoystick - Stop iterating when canvas is released
  packages/dev/core/src/Misc/virtualJoystick.ts
Labels: bug

#13333 Make sure BONETEXTURE is always set with a value when supported
  packages/dev/core/src/Materials/materialHelper.ts
Labels: skip changelog

#13317 The STL loader flips the faces
  packages/dev/loaders/src/STL/stlFileLoader.ts
Labels: skip changelog

#13335 NME: Fix reusing the same temporary variable name in TextureBlock
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
Labels: bug, nme

#13325 Add Fullscreen ADT to HTMLTwinRenderer
  packages/tools/accessibility/src/HtmlTwin/htmlTwinHostComponent.tsx
Labels: enhancement

#13342 NME: Add a CSS class to all graph nodes
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/tools/nodeEditor/src/graphEditor.tsx
  packages/tools/nodeEditor/src/main.scss
Labels: skip changelog

#13343 EffectLayer: Allows to set the type of the main texture
  packages/dev/core/src/Layers/effectLayer.ts
  packages/dev/core/src/Layers/glowLayer.ts
  packages/dev/core/src/Layers/highlightLayer.ts
Labels: rendering engine, new feature

#13347 NME: Allow 3 textures for the TriPlanar block
  packages/dev/core/src/Materials/Node/Blocks/biPlanarBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/triPlanarBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialConnectionPointCustomObject.ts
  packages/tools/nodeEditor/src/graphSystem/display/textureDisplayManager.modules.scss
Labels: skip changelog

#13353 Rework Scene and GUI Editor connection
  packages/dev/gui/src/2D/controls/control.ts
  packages/tools/guiEditor/src/components/sceneExplorer/sceneExplorerComponent.tsx
  packages/tools/guiEditor/src/diagram/gizmoGeneric.tsx
  packages/tools/guiEditor/src/diagram/workbench.tsx
Labels: bug, gui editor

#13355 VolumetricLightScattering: Add support for included only meshes
  packages/dev/core/src/PostProcesses/volumetricLightScatteringPostProcess.ts
Labels: rendering engine, new feature

#13356 Fix bug in glTF animation export
  packages/dev/serializers/src/glTF/2.0/glTFAnimation.ts
Labels: bug, exporters, glTF

#13359 RenderTargetTexture: Add forceLayerMaskCheck property
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
Labels: rendering engine, new feature

#13358 LineMesh: Add an option to not dispose the material
  packages/dev/core/src/Meshes/linesMesh.ts
Labels: rendering engine, new feature

#13362 Fix PBR Emissive with lightmap
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockFinalColorComposition.fx
Labels: bug, materials

#13363 LineMesh: Fix the signature of dispose
  packages/dev/core/src/Meshes/linesMesh.ts
Labels: skip changelog

#13366 Fix #13364
  packages/dev/core/src/Culling/ray.ts
  packages/dev/core/src/Meshes/subMesh.ts
Labels: skip changelog

#13368 Add Transpose and Determinant matrix blocks
  packages/dev/core/src/Materials/Node/Blocks/index.ts
  packages/dev/core/src/Materials/Node/Blocks/matrixDeterminantBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/matrixTransposeBlock.ts
  packages/tools/nodeEditor/src/blockTools.ts
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
Labels: new feature, nme

#13372 [GUI] If a new control is added on root, call the camera update function to…
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
Labels: bug, gui

#13374 Workaround Tabs css name conflict
  packages/dev/inspector/src/components/actionTabs/actionTabs.scss
  packages/dev/inspector/src/components/actionTabs/tabsComponent.tsx
Labels: skip changelog

#13371 Material plugins: Allow custom flags when injecting code with regexp
  packages/dev/core/src/Materials/materialPluginManager.ts
Labels: materials, new feature

#13375 Add audioListenerRotationProvider
  packages/dev/core/src/Audio/audioSceneComponent.ts
Labels: enhancement, audio

#13373 Fix audio offset issues
  packages/dev/core/src/Audio/sound.ts
Labels: bug, audio

#13377 Fix crash when calling getGlowLayerByName when no effects have been created yet
  packages/dev/core/src/Layers/glowLayer.ts
Labels: bug, rendering engine

#13379 Don't serialize internal shader materials
  packages/dev/core/src/Meshes/linesMesh.ts
  packages/dev/core/src/Rendering/boundingBoxRenderer.ts
Labels: bug, rendering engine

#13380 Change GUI Editor default image URL
  packages/tools/guiEditor/src/guiNodeTools.ts
Labels: bug, gui editor

#13382 More defensive handling of name property in Inspector
  packages/dev/inspector/src/tools.ts
Labels: bug, inspector

#13384 Add a parameter to CreateScreenshotUsingRenderTarget(Async) to allow …
  packages/dev/core/src/Misc/screenshotTools.ts
Labels: bug, rendering engine

#13386 Hold shift when resizing to lock aspect ratio in GUI Editor
  packages/dev/gui/src/2D/math2D.ts
  packages/tools/guiEditor/src/diagram/gizmoGeneric.tsx
  packages/tools/guiEditor/src/diagram/workbench.tsx
  packages/tools/guiEditor/src/globalState.ts
Labels: enhancement, gui editor
