Repository BabylonJS/Babylon.js, pull requests merged in 2022-05, with the labels that each got.

#12465 Missing null for First go to frame in Animation
  packages/dev/core/src/Animations/animatable.ts
Labels: bug

#12467 [GUI] Add feature testing to text metrics width
  packages/dev/gui/src/2D/controls/textBlock.ts
Labels: bug, gui

#12466 [NME] Fix light selection in Light Information Block
  packages/tools/nodeEditor/src/diagram/properties/lightInformationPropertyTabComponent.tsx
Labels: bug, nme

#12464 Nine patch overlap fix
  packages/dev/gui/src/2D/controls/image.ts
Labels: bug

#12458 Remove BABYLON namespace references in the Inspector
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/textures/textureEditorComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/meshPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/toolsTabComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/entities/gui/guiTools.ts
  packages/tools/devHost/webpack.config.js
  packages/tools/guiEditor/src/guiEditor.ts
  packages/tools/guiEditor/src/legacy/legacy.ts
Labels: new feature

#12468 no plane update for axis gizmos
  packages/dev/core/src/Gizmos/axisDragGizmo.ts
  packages/dev/core/src/Gizmos/axisScaleGizmo.ts
Labels: bug

#12470 Tiny perf improvement
  packages/dev/core/src/Engines/Processors/shaderProcessor.ts
Labels: bug

#12461 Create a TBN NME node to handle tangent space orientation
  packages/dev/core/src/Materials/Node/Blocks/Dual/TBNBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/index.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/perturbNormalBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Input/inputBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/anisotropyBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/clearCoatBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Vertex/morphTargetsBlock.ts
  packages/tools/nodeEditor/src/blockTools.ts
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeEditor/src/diagram/properties/inputNodePropertyComponent.tsx
Labels: bug, nme

#12469 Fix infinite recursion with glTF skeleton
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: bug

#12472 Instance color mixing
  packages/dev/core/src/Materials/materialHelper.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/Shaders/ShadersInclude/vertexColorMixing.fx
  packages/dev/core/src/Shaders/color.vertex.fx
  packages/dev/core/src/Shaders/default.vertex.fx
  packages/dev/core/src/Shaders/pbr.vertex.fx
  packages/dev/materials/src/cell/cell.vertex.fx
  packages/dev/materials/src/fire/fire.vertex.fx
  packages/dev/materials/src/fur/fur.vertex.fx
  packages/dev/materials/src/gradient/gradient.vertex.fx
  packages/dev/materials/src/lava/lava.vertex.fx
  packages/dev/materials/src/mix/mix.vertex.fx
  packages/dev/materials/src/simple/simple.vertex.fx
  packages/dev/materials/src/terrain/terrain.vertex.fx
  packages/dev/materials/src/triPlanar/triplanar.vertex.fx
  packages/dev/materials/src/water/water.vertex.fx
Labels: enhancement

#12477 Optimize rendering to reuse material as much as possible
  packages/dev/core/src/Rendering/renderingGroup.ts
Labels: enhancement

#12482 warning and checks for noimpostor children
  packages/dev/core/src/Debug/physicsViewer.ts
Labels: bug, enhancement

#12486 Add creation of sRGB Render Targets
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/Materials/Textures/textureCreationOptions.ts
Labels: rendering engine, new feature

#12480 [Viewer] fix viewer import from loaders
  packages/tools/viewer/src/index.ts
Labels: bug

#12502 Fix ubo not of the right size when using material plugins
  packages/dev/core/src/Materials/materialPluginManager.ts
  packages/tools/tests/test/visualization/ReferenceImages/materialPlugin.png
  packages/tools/tests/test/visualization/config.json
Labels: bug

#12497 A couple of minor fixes
  packages/dev/core/src/Meshes/Compression/dracoCompression.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: skip changelog

#12504 Fix a stupid bug
  packages/dev/core/src/Meshes/transformNode.ts
Labels: skip changelog

#12487 Still test disable meshes because gltf loaders them them on later
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/scene.ts
Labels: bug

#12499 Fix PointerDragBehavior to account for button context, add button filter
  packages/dev/core/src/Behaviors/Meshes/pointerDragBehavior.ts
Labels: bug, enhancement

#12493 Fix NME Morph block with tangents
  packages/dev/core/src/Materials/Node/Blocks/Vertex/morphTargetsBlock.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssao2RenderingPipeline.ts
Labels: bug, nme

#12517 [XR] switch to enum (instead of const-enum)
  packages/dev/core/src/XR/features/WebXRHandTracking.ts
Labels: skip changelog

#12518 Fix Scissor Doc
  packages/dev/core/src/Engines/engine.ts
  packages/dev/core/src/Engines/engineFactory.ts
Labels: bug, documentation

#12519 Fix: NME TBNBlock world input doesn't work if connected to a vertex node
  packages/dev/core/src/Materials/Node/Blocks/Dual/index.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/TBNBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/index.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/perturbNormalBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/anisotropyBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/clearCoatBlock.ts
  packages/tools/nodeEditor/src/blockTools.ts
Labels: bug, nme

#12520 Add a constant for the Snippet Server URL in all dev packages.
  packages/dev/core/src/Animations/animation.ts
  packages/dev/core/src/Engines/constants.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Particles/particleHelper.ts
  packages/dev/core/src/Sprites/spriteManager.ts
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/particleSystemPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/sprites/spriteManagerPropertyGridComponent.tsx
  packages/tools/playground/src/globalState.ts
Labels: new feature

#12521 Fix Mirror Reflection in right handed system
  packages/dev/core/src/Materials/Background/backgroundMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
Labels: bug, rendering engine

#12526 Fix a bug in glTF loader when loading skins
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: skip changelog

#12498 Add getNormalsData to AbstractMesh and refactor common part with getP…
  packages/dev/core/src/Meshes/abstractMesh.ts
Labels: new feature

#12533 [PG] Fix inspector not working after download
  packages/dev/core/src/scene.ts
  packages/tools/playground/src/tools/downloadManager.ts
Labels: bug

#12515 Exposed Native Engine capabilities to Babylon.js, fixes morph targets on Babylon Native Android
  packages/dev/core/src/Engines/Native/nativeInterfaces.ts
  packages/dev/core/src/Engines/engineCapabilities.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/nullEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Morph/morphTargetManager.ts
Labels: bug

#12509 Add a warning when using ignored options with Dashed Lines update.
  packages/dev/core/src/Meshes/Builders/linesBuilder.ts
Labels: documentation

#12538 More fix for glTF loader skinning code
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: skip changelog

#12540 [Build] remove remaining www.babylonjs.com references
  packages/dev/core/src/Particles/particleHelper.ts
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#12541 Fixed Logic for FreeCameraTouchInput to properly detect when input is mouse input
  packages/dev/core/src/Cameras/Inputs/freeCameraTouchInput.ts
Labels: bug, inputs

#12539 Fix ClearCoat Refraction V direction
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockClearcoat.fx
Labels: bug, materials

#12556 Allow HDR texture types in DepthOfFieldBlurPostProcess
  packages/dev/core/src/PostProcesses/depthOfFieldBlurPostProcess.ts
Labels: bug, rendering engine

#12553 Add sRGB option to 2D RawTexture
  packages/dev/core/src/Engines/Extensions/engine.rawTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.rawTexture.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/nullEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Materials/Textures/internalTexture.ts
  packages/dev/core/src/Materials/Textures/rawTexture.ts
Labels: enhancement, rendering engine

#12555 Fix Instances Color Alpha
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockAlbedoOpacity.fx
  packages/dev/core/src/Shaders/ShadersInclude/vertexColorMixing.fx
  packages/dev/core/src/Shaders/default.fragment.fx
  packages/dev/materials/src/cell/cell.fragment.fx
  packages/dev/materials/src/fire/fire.fragment.fx
  packages/dev/materials/src/fur/fur.fragment.fx
  packages/dev/materials/src/gradient/gradient.fragment.fx
  packages/dev/materials/src/lava/lava.fragment.fx
  packages/dev/materials/src/mix/mix.fragment.fx
  packages/dev/materials/src/simple/simple.fragment.fx
  packages/dev/materials/src/sky/sky.fragment.fx
  packages/dev/materials/src/terrain/terrain.fragment.fx
  packages/dev/materials/src/triPlanar/triplanar.fragment.fx
  packages/dev/materials/src/water/water.fragment.fx
Labels: bug, materials

#12525 Initial storybook setup
  package-lock.json
  packages/dev/buildTools/src/webpackTools.ts
  packages/dev/sharedUiComponents/.storybook/main.js
  packages/dev/sharedUiComponents/.storybook/preview.js
  packages/dev/sharedUiComponents/package.json
  packages/dev/sharedUiComponents/readme.md
  packages/dev/sharedUiComponents/src/components/Button.scss
  packages/dev/sharedUiComponents/src/components/Button.tsx
  packages/dev/sharedUiComponents/src/components/Colors.scss
  packages/dev/sharedUiComponents/src/components/Fonts.scss
  packages/dev/sharedUiComponents/src/components/Icon.scss
  packages/dev/sharedUiComponents/src/components/Icon.tsx
  packages/dev/sharedUiComponents/src/components/Label.scss
  packages/dev/sharedUiComponents/src/components/Label.tsx
  packages/dev/sharedUiComponents/src/components/Toggle.scss
  packages/dev/sharedUiComponents/src/components/Toggle.tsx
  packages/dev/sharedUiComponents/src/components/classNames.ts
  packages/dev/sharedUiComponents/src/scssDeclaration.d.ts
  packages/dev/sharedUiComponents/src/stories/Button.stories.tsx
  packages/dev/sharedUiComponents/src/stories/Icon.stories.tsx
  packages/dev/sharedUiComponents/src/stories/Introduction.stories.mdx
  packages/dev/sharedUiComponents/src/stories/Label.stories.tsx
  packages/dev/sharedUiComponents/src/stories/Toggle.stories.tsx
  packages/dev/sharedUiComponents/src/stories/assets/code-brackets.svg
  packages/dev/sharedUiComponents/src/stories/assets/colors.svg
  packages/dev/sharedUiComponents/src/stories/assets/comments.svg
  packages/dev/sharedUiComponents/src/stories/assets/direction.svg
  packages/dev/sharedUiComponents/src/stories/assets/flow.svg
  packages/dev/sharedUiComponents/src/stories/assets/plugin.svg
  packages/dev/sharedUiComponents/src/stories/assets/repo.svg
  packages/dev/sharedUiComponents/src/stories/assets/stackalt.svg
Labels: tools

#12562 Fix prepass view uniform
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/Shaders/ShadersInclude/defaultFragmentDeclaration.fx
Labels: bug, materials

#12572 PBR refractionIntensityTexture in the inspector
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/pbrMaterialPropertyGridComponent.tsx
Labels: enhancement, inspector

#12565 Change glTF skinned mesh reference to a callback
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/dev/loaders/src/glTF/glTFFileLoader.ts
Labels: skip changelog

#12584 Add missing interpolation to glTF animation key targeting weights
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: bug

#12585 Fix memoryleak
  packages/dev/core/src/Loading/Plugins/babylonFileLoader.ts
Labels: bug, loaders, memory leak

#12586 DeviceInputSystem: Add check for matchMedia in WebDeviceInputSystem
  packages/dev/core/src/DeviceInput/InputDevices/webDeviceInputSystem.ts
Labels: bug

#12579 [Viewer] make sure to watch changes in the assets lib
  packages/tools/viewer/webpack.config.js
Labels: skip changelog

#12524 InputManager: Fix Picking on PointerUp and add bool to skip pointerup picking
  packages/dev/core/src/Inputs/scene.inputManager.ts
  packages/dev/core/src/scene.ts
Labels: bug

#12597 Fix render frame identification issue with instances
  packages/dev/core/src/Meshes/instancedMesh.ts
Labels: bug

#12603 Small fixes for gizmo and navigation
  packages/dev/core/src/Gizmos/gizmo.ts
  packages/dev/core/src/Navigation/Plugins/recastJSPlugin.ts
Labels: bug

#12612 Added forcedExtension option to textur creation
  packages/dev/core/src/Materials/Textures/texture.ts
Labels: enhancement, texture

#12607 Grid children disappear once linked mesh is outside view
  packages/dev/gui/src/2D/controls/container.ts
Labels: bug, gui
