Repository BabylonJS/Babylon.js, pull requests merged in 2023-08, with the labels that each got.

#14104 Disable half float linear filtering in native
  packages/dev/core/src/Engines/nativeEngine.ts
Labels: skip changelog

#14103 Fixes to NME styling
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
Labels: enhancement, nme

#14111 Pass pick result to triggers missing it.
  packages/dev/core/src/Inputs/scene.inputManager.ts
Labels: bug

#14106 Material plugins: Add support for #include resolution
  packages/dev/core/src/Engines/Processors/shaderProcessor.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/materialPluginBase.ts
  packages/dev/core/src/Materials/materialPluginEvent.ts
  packages/dev/core/src/Materials/materialPluginManager.ts
  packages/dev/core/src/Materials/standardMaterial.ts
Labels: enhancement, materials

#14105 Accessibility: Fix crash with instanced meshes
  packages/tools/accessibility/src/HtmlTwin/htmlTwinHostComponent.tsx
Labels: bug, accessibility

#14102 Cancel any pending animation frames on stopRenderLoop
  packages/dev/core/src/Engines/engine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Misc/customAnimationFrameRequester.ts
Labels: bug, rendering engine

#14110 Add setTargetTransform on body
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsBody.ts
Labels: physics, new feature

#14108 Shaders: Don't inject fragment output declaration if already existing
  packages/dev/core/src/Engines/WebGL/webGL2ShaderProcessors.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsGLSL.ts
Labels: enhancement, rendering engine

#14114 Decal map: don't renderer particle systems in the decal map texture
  packages/dev/core/src/Meshes/meshUVSpaceRenderer.ts
Labels: bug, materials

#14115 Add support for teleport nodes in NME
  packages/dev/core/src/Materials/Node/Blocks/Input/inputBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Teleport/index.ts
  packages/dev/core/src/Materials/Node/Blocks/Teleport/teleportInBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Teleport/teleportOutBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/index.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlockConnectionPoint.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/interfaces/displayManager.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/tools.ts
  packages/tools/nodeEditor/src/blockTools.ts
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeEditor/src/graphEditor.tsx
  packages/tools/nodeEditor/src/graphSystem/display/teleportInDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/display/teleportOutDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/properties/teleportOutNodePropertyComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/registerToDisplayLedger.ts
  packages/tools/nodeEditor/src/graphSystem/registerToPropertyLedger.ts
Labels: new feature, nme

#14112 Textures: Fix clearing of textures with integer type
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessor.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsGLSL.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: bug, texture

#14120 Nme fix2
  packages/dev/core/src/Materials/Node/Blocks/Teleport/teleportInBlock.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/interfaces/displayManager.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/interfaces/nodeData.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodeLink.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/tools.ts
  packages/tools/nodeEditor/src/graphEditor.tsx
  packages/tools/nodeEditor/src/graphSystem/blockNodeData.ts
  packages/tools/nodeEditor/src/graphSystem/display/teleportInDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/display/teleportOutDisplayManager.ts
Labels: skip changelog

#14118 Gizmos fixes
  packages/dev/core/src/Gizmos/lightGizmo.ts
  packages/dev/core/src/Gizmos/planeRotationGizmo.ts
  packages/dev/core/src/Gizmos/rotationGizmo.ts
Labels: enhancement, gizmos

#14101 Add populateRootNodes in asset container and loading
  packages/dev/core/src/Loading/sceneLoader.ts
  packages/dev/core/src/assetContainer.ts
Labels: bug, assets

#14121 Fix PR comments
  packages/dev/core/src/Materials/Node/Blocks/Teleport/teleportInBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Teleport/teleportOutBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlockConnectionPoint.ts
Labels: skip changelog

#14129 Implement word boundary checks in regular expressions
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsGLSL.ts
Labels: skip changelog

#14109 Add observable for collision finished events/trigger events
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsAggregate.ts
  packages/dev/core/src/Physics/v2/physicsShape.ts
  packages/tools/babylonServer/public/havok/HavokPhysics.wasm
Labels: physics, new feature

#14133 Clear transform node's physicsBody attribute when that is disposed
  packages/dev/core/src/Physics/v2/physicsBody.ts
Labels: bug, physics

#14132 HDR filtering: Fix state reset
  packages/dev/core/src/Materials/Textures/Filtering/hdrFiltering.ts
  packages/dev/core/src/Materials/effectRenderer.ts
Labels: bug, rendering engine

#14135 GPUParticleSystem: Fix context lost management
  packages/dev/core/src/Particles/IGPUParticleSystemPlatform.ts
  packages/dev/core/src/Particles/computeShaderParticleSystem.ts
  packages/dev/core/src/Particles/gpuParticleSystem.ts
  packages/dev/core/src/Particles/webgl2ParticleSystem.ts
Labels: bug, particles

#14138 Clean up mesh.actionManager attribute when it is disposed of.
  packages/dev/core/src/Actions/actionManager.ts
Labels: bug

#14137 Fluid Renderer: Remove wrong doc
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderer.ts
Labels: skip changelog

#14142 Skeleton: make sure a cloned skeleton is ready to use
  packages/dev/core/src/Bones/skeleton.ts
Labels: enhancement, bones

#14146 PostProcess: Fix crash when detaching and reattaching a camera from/to a render pipeline
  packages/dev/core/src/PostProcesses/RenderPipeline/postProcessRenderEffect.ts
Labels: bug, post-process

#14148 Shadow generators: Add support for red channel only for the shadow map texture
  packages/dev/core/src/Lights/Shadows/cascadedShadowGenerator.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
Labels: enhancement, shadows

#14150 Call the validateDrag function on planeDragGizmo
  packages/dev/core/src/Gizmos/planeDragGizmo.ts
Labels: bug, gizmos

#14151 Bone IK controller: Make sure the absolute matrices are up to date
  packages/dev/core/src/Bones/boneIKController.ts
Labels: bug, bones

#14158 Fix #14157
  packages/dev/core/src/Meshes/Node/Blocks/geometryOptimizeBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/interfaces/nodeData.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/blockNodeData.ts
Labels: skip changelog

#14145 fix children nodes with description not being rendered on a11y tree w…
  packages/tools/accessibility/src/HtmlTwin/htmlTwinHostComponent.tsx
Labels: bug, accessibility

#14159 Improve optimize block
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnFacesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryOptimizeBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
Labels: skip changelog

#14161 Remove unneeded test
  packages/tools/tests/src/umdCompile.ts
  packages/tools/tests/webpack.config.js
Labels: skip changelog

#14160 More descriptive names for the AxesViewer's materials
  packages/dev/core/src/Debug/axesViewer.ts
Labels: enhancement

#14167 GUI InputTextArea: Fix inserting character in long string (wrapped)
  packages/dev/gui/src/2D/controls/inputTextArea.ts
Labels: bug, gui

#14163 Fix #14162
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVolumeBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: skip changelog

#14119 AnimationGroup: Add masking support
  packages/dev/core/src/Animations/animatable.ts
  packages/dev/core/src/Animations/animationGroup.ts
  packages/dev/core/src/Animations/animationGroupMask.ts
  packages/dev/core/src/Animations/index.ts
Labels: animations, new feature

#14171 Add geometryID to NGE
  packages/dev/core/src/Meshes/Node/Blocks/geometryInputBlock.ts
  packages/dev/core/src/Meshes/Node/Enums/nodeGeometryContextualSources.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
  packages/dev/core/src/Meshes/mesh.vertexData.ts
  packages/dev/sharedUiComponents/src/lines/vector3LineComponent.tsx
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/display/inputDisplayManager.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/inputNodePropertyComponent.tsx
Labels: skip changelog

#14175 Add new blocks: GeometryInfo and Collection
  packages/dev/core/src/Meshes/Node/Blocks/geometryCollectionBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryInfoBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryInputBlock.ts
  packages/dev/core/src/Meshes/Node/Enums/nodeGeometryContextualSources.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
  packages/dev/core/src/Meshes/mesh.vertexData.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/display/inputDisplayManager.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/inputNodePropertyComponent.tsx
Labels: skip changelog

#14174 WebDeviceInputSystem: Add additional checks for pointermove started Touch events
  packages/dev/core/src/DeviceInput/webDeviceInputSystem.ts
Labels: bug, inputs

#14177 Fix initial audio engine unlock state
  packages/dev/core/src/Audio/audioEngine.ts
  packages/dev/core/test/unit/Audio/audioEngine.test.ts
  packages/dev/core/test/unit/Audio/helpers/audioTestHelper.ts
  packages/dev/core/test/unit/Audio/helpers/audioTestSamples.ts
  packages/dev/core/test/unit/Audio/helpers/mockedAudioObjects.ts
  packages/dev/core/test/unit/Audio/sound.test.ts
Labels: bug

#14179 Greased line plugin: Fix crash when cloning the material
  packages/dev/core/src/Materials/greasedLinePluginMaterial.ts
Labels: bug, materials

#14178 Fix mute button getting stuck on iOS
  packages/dev/core/src/Audio/audioEngine.ts
  packages/dev/core/test/unit/Audio/helpers/mockedAudioObjects.ts
Labels: bug

#14182 Add a button to sync nge with the hosting scene and mesh
  packages/dev/core/src/Meshes/Node/nodeGeometry.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/meshPropertyGridComponent.tsx
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTabComponent.tsx
  packages/tools/nodeGeometryEditor/src/globalState.ts
  packages/tools/nodeGeometryEditor/src/nodeGeometryEditor.ts
Labels: skip changelog

#14181 Remove unused "inspector visibility" for nge
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/display/inputDisplayManager.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/inputNodePropertyComponent.tsx
Labels: skip changelog

#14180 Add extra safety on audio
  packages/dev/core/src/Audio/audioEngine.ts
Labels: bug, audio

#14185 Bones: Fix wrong world matrix for meshes attached to bone
  packages/dev/core/src/Bones/skeleton.ts
  packages/dev/core/src/Meshes/transformNode.ts
Labels: bug, bones

#14186 Particle Systems: Fix the pivot position for rotations
  packages/dev/core/src/Shaders/gpuRenderParticles.vertex.fx
  packages/dev/core/src/Shaders/particles.vertex.fx
Labels: bug, particles

#14188 Better mesh representation in NGE
  packages/dev/core/src/Meshes/Node/Blocks/Sources/meshBlock.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/meshNodePropertyComponent.tsx
Labels: skip changelog

#14189 Highlight context source when picking a contextual input
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/display/inputDisplayManager.ts
Labels: skip changelog

#14195 Update to Havok 1.1.4
  packages/tools/babylonServer/public/havok/HavokPhysics.wasm
Labels: bug, physics

#14197 Fix updating issue with exposed inputs
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTabComponent.tsx
Labels: skip changelog

#14196 new NGE block: Instantiate
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnFacesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVerticesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVolumeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setColorsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setNormalsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setPositionsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setTangentsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setUVsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryInputBlock.ts
  packages/dev/core/src/Meshes/Node/Enums/nodeGeometryContextualSources.ts
  packages/dev/core/src/Meshes/Node/Interfaces/nodeGeometryExecutionContext.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/display/inputDisplayManager.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/inputNodePropertyComponent.tsx
Labels: skip changelog

#14200 Better display of ports with values
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlockConnectionPoint.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/common.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/display/sourceDisplayManager.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/registerNodePortDesign.ts
Labels: skip changelog

#14206 Shadows: Fix shadow light frustum calculation
  packages/dev/core/src/Lights/Shadows/cascadedShadowGenerator.ts
  packages/dev/core/src/Lights/directionalLight.ts
Labels: bug, shadows

#14211 Procedural texture: Fix the reset method
  packages/dev/core/src/Materials/Textures/Procedurals/proceduralTexture.ts
Labels: bug, texture

#14213 * Change the Custom Frame name formatting.
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: bug, nme, nge

#14217 better nge icons
  packages/tools/nodeGeometryEditor/src/graphSystem/registerNodePortDesign.ts
Labels: skip changelog

#14219 Fix #14218
  packages/dev/core/src/Meshes/Node/Blocks/Sources/cylinderBlock.ts
Labels: skip changelog

#14220 Fix bad input routing
  packages/tools/nodeGeometryEditor/src/components/propertyTab/inputsPropertyTabComponent.tsx
Labels: skip changelog

#14215 New NGE node: Mapping
  packages/dev/core/src/Meshes/Node/Blocks/mappingBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/registerNodePortDesign.ts
Labels: skip changelog

#14221 PointCloudSystem: Fix uv coordinates used when getting color from texture
  packages/dev/core/src/Particles/pointsCloudSystem.ts
Labels: bug, particles

#14222 fix stretch nine patch to respect sourceXXX parameters
  packages/dev/gui/src/2D/controls/image.ts
Labels: bug, gui

#14216 Fix #14214
  packages/tools/nodeGeometryEditor/package.json
  packages/tools/nodeGeometryEditor/src/components/preview/previewManager.ts
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTabComponent.tsx
  packages/tools/nodeGeometryEditor/src/globalState.ts
  packages/tools/nodeGeometryEditor/tsconfig.build.json
  packages/tools/nodeGeometryEditor/webpack.config.js
Labels: skip changelog

#14209 ArcRotateCamera: Modify offset math to correctly zoom to point
  packages/dev/core/src/Cameras/Inputs/arcRotateCameraMouseWheelInput.ts
Labels: bug, inputs

#14228 Add matrix for instatiateXXX
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnFacesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVerticesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVolumeBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
  packages/tools/nodeGeometryEditor/src/main.scss
Labels: skip changelog

#14229 Fix port sync
  packages/dev/core/src/Meshes/Node/Blocks/geometryInputBlock.ts
Labels: skip changelog

#14207 NME: Fix the shadow output of the light blocks
  packages/dev/core/src/Materials/Node/Blocks/Dual/lightBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/Shaders/ShadersInclude/lightFragment.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockDirectLighting.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockFinalLitComponents.fx
  packages/dev/core/src/Shaders/background.fragment.fx
  packages/dev/core/src/Shaders/default.fragment.fx
  packages/dev/materials/src/cell/cell.fragment.fx
  packages/dev/materials/src/fur/fur.fragment.fx
  packages/dev/materials/src/gradient/gradient.fragment.fx
  packages/dev/materials/src/lava/lava.fragment.fx
  packages/dev/materials/src/mix/mix.fragment.fx
  packages/dev/materials/src/normal/normal.fragment.fx
  packages/dev/materials/src/shadowOnly/shadowOnly.fragment.fx
  packages/dev/materials/src/simple/simple.fragment.fx
  packages/dev/materials/src/terrain/terrain.fragment.fx
  packages/dev/materials/src/triPlanar/triplanar.fragment.fx
  packages/dev/materials/src/water/water.fragment.fx
Labels: bug, nme

#14226 Don't allow blocks in NME to automatically connect to other blocks in…
  packages/dev/core/src/Materials/Node/Blocks/Dual/fogBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/lightBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/reflectionTextureBaseBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/reflectionTextureBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/TBNBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/perturbNormalBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/screenSpaceBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/refractionBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Particle/particleTextureBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Vertex/bonesBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Vertex/instancesBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Vertex/morphTargetsBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/viewDirectionBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlock.ts
  packages/tools/nodeEditor/src/graphEditor.tsx
Labels: bug, nme

#14233 Animation groups: Add ClipKeys helper + update inspector
  packages/dev/core/src/Animations/animation.ts
  packages/dev/core/src/Animations/animationGroup.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/animations/animationGroupPropertyGridComponent.tsx
Labels: enhancement, animations

#14237 SolidParticleSystem: Add uvKind option to the digest method
  packages/dev/core/src/Particles/solidParticleSystem.ts
Labels: enhancement, particles

#14239 avoid rendering empty trees on a11y tree
  packages/tools/accessibility/src/HtmlTwin/htmlTwinHostComponent.tsx
Labels: bug, accessibility

#14240 fix alignment issue in NME
  packages/tools/nodeEditor/src/main.scss
Labels: bug, nme

#14238 FreeCameraTouchInput: Add check for Handedness
  packages/dev/core/src/Cameras/Inputs/flyCameraMouseInput.ts
  packages/dev/core/src/Cameras/Inputs/freeCameraKeyboardMoveInput.ts
  packages/dev/core/src/Cameras/Inputs/freeCameraMouseInput.ts
  packages/dev/core/src/Cameras/Inputs/freeCameraTouchInput.ts
  packages/dev/core/src/Cameras/arcRotateCamera.ts
  packages/dev/core/src/Cameras/camera.ts
Labels: bug, inputs
