Repository BabylonJS/Babylon.js, pull requests merged in 2023-09, with the labels that each got.

#14249 RuntimeAnimation: Fix original value used in the bone matrix case
  packages/dev/core/src/Animations/runtimeAnimation.ts
Labels: bug, animations

#14250 Performance viewer: Fix crash when object is empty
  packages/dev/core/src/Misc/PerformanceViewer/performanceViewerCollectionStrategies.ts
Labels: bug, performance viewer

#14253 Occlusion queries: Use the first camera in the case of multiple cameras
  packages/dev/core/src/Meshes/mesh.ts
Labels: enhancement, rendering engine

#14255 Constraints debug view - pivots
  packages/dev/core/src/Debug/physicsViewer.ts
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsConstraint.ts
Labels: physics, new feature

#14257 Fix #14242
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnFacesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVerticesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVolumeBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
Labels: skip changelog

#14140 Flow graph iteration 0.0.2
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphAddBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphBinaryOpBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphConditionalDataBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphGetVariableBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/index.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/flowGraphMeshPickEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/flowGraphSceneReadyEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphConditionalBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphForLoopBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphLogBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphPlayAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSetPropertyBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSetVariableBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphTimerBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/index.ts
  packages/dev/core/src/FlowGraph/flowGraph.ts
  packages/dev/core/src/FlowGraph/flowGraphAsyncExecutionBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphConnection.ts
  packages/dev/core/src/FlowGraph/flowGraphContext.ts
  packages/dev/core/src/FlowGraph/flowGraphDataConnection.ts
  packages/dev/core/src/FlowGraph/flowGraphEventBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphExecutionBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphRichTypes.ts
  packages/dev/core/src/FlowGraph/flowGraphSignalConnection.ts
  packages/dev/core/src/FlowGraph/flowGraphVariableDefinitions.ts
  packages/dev/core/src/FlowGraph/flowGraphWithOnDoneExecutionBlock.ts
Labels: new feature

#14258 Fix #14256
  packages/dev/core/src/Maths/math.vector.ts
  packages/dev/core/src/Meshes/Node/Blocks/debugBlock.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodeLink.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/tools/nodeEditor/src/globalState.ts
  packages/tools/nodeEditor/src/graphSystem/registerDebugSupport.ts
  packages/tools/nodeGeometryEditor/src/globalState.ts
  packages/tools/nodeGeometryEditor/src/graphEditor.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/registerDebugSupport.ts
Labels: skip changelog

#14259 Fix #14244
  packages/dev/core/src/Meshes/Node/Blocks/intFloatConverterBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/mapRangeBlock.ts
Labels: skip changelog

#14260 Fix #14246
  packages/dev/core/src/Meshes/Node/Blocks/mapRangeBlock.ts
Labels: skip changelog

#14262 Fix #14194
  packages/dev/inspector/src/components/sceneExplorer/sceneExplorerComponent.tsx
Labels: skip changelog

#14263 Fix mathblock to accept floats with vectors
  packages/dev/core/src/Meshes/Node/Blocks/mathBlock.ts
Labels: skip changelog

#14265 Screenshots: Fix OffscreenCanvas not supported in older browsers
  packages/dev/core/src/Misc/dumpTools.ts
Labels: enhancement, rendering engine

#14266 Compute shaders: Add support for external (video) textures
  packages/dev/core/src/Compute/computeShader.ts
  packages/dev/core/src/Engines/Extensions/engine.computeShader.ts
  packages/dev/core/src/Engines/WebGPU/webgpuComputeContext.ts
  packages/dev/core/src/Materials/Textures/videoTexture.ts
Labels: enhancement, WebGPU

#14267 fix action manager disposal when shared
  packages/dev/core/src/Actions/actionManager.ts
  packages/dev/core/src/Meshes/abstractMesh.ts
Labels: bug

#14268 Fix #14264
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnFacesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVerticesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVolumeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/matrixComposeBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/dev/core/src/Meshes/Node/nodeGeometry.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/tests/test/visualization/ReferenceImages/nodeGeometry.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#14269 Add new InstanceID info
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnFacesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVerticesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVolumeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setColorsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setMaterialIDBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setNormalsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setPositionsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setTangentsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setUVsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryInputBlock.ts
  packages/dev/core/src/Meshes/Node/Enums/nodeGeometryContextualSources.ts
  packages/dev/core/src/Meshes/Node/Interfaces/nodeGeometryInstancingContext.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/display/inputDisplayManager.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/inputNodePropertyComponent.tsx
Labels: skip changelog

#14270 Fix texture not ready when parsing NME
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
Labels: enhancement, nme

#14261 Flow graph iteration 0.0.3
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphGetVariableBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/flowGraphReceiveCustomEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/index.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphPlayAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSendCustomEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSetVariableBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphStopAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/index.ts
  packages/dev/core/src/FlowGraph/flowGraph.ts
  packages/dev/core/src/FlowGraph/flowGraphContext.ts
  packages/dev/core/src/FlowGraph/flowGraphCustomEvent.ts
  packages/dev/core/src/FlowGraph/flowGraphEventCoordinator.ts
  packages/dev/core/src/FlowGraph/flowGraphVariableDefinitions.ts
  packages/dev/core/src/FlowGraph/index.ts
Labels: new feature, flow graph

#14271 NME: Fix PBR debug mode
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrDebug.fx
Labels: bug, nme

#14272 WebGPU: Fix warnings when using occlusion queries
  packages/dev/core/src/Engines/Extensions/engine.query.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTargetCube.ts
  packages/dev/core/src/Engines/WebGPU/webgpuOcclusionQuery.ts
  packages/dev/core/src/Engines/WebGPU/webgpuQuerySet.ts
  packages/dev/core/src/Engines/renderTargetWrapper.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: bug, WebGPU

#14273 Rework entire stack system for context
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnFacesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVerticesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVolumeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setColorsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setNormalsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setPositionsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setTangentsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setUVsBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
Labels: skip changelog

#14274 WebGPU: Fix having a single occlusion query per mesh per frame
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.query.ts
  packages/dev/core/src/Engines/WebGPU/webgpuOcclusionQuery.ts
Labels: bug, WebGPU

#14275 I'm with stupid...
  packages/dev/core/src/Meshes/Node/Blocks/matrixComposeBlock.ts
Labels: skip changelog

#14276 Add textures ready helper
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
Labels: skip changelog

#14278 Animations: Refactor the code that creates additive animations
  packages/dev/core/src/Animations/animation.ts
  packages/dev/core/src/Animations/animationGroup.ts
Labels: enhancement, animations

#14279 Fix context lost or unwanted data update
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnFacesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVerticesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVolumeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setColorsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setMaterialIDBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setNormalsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setPositionsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setTangentsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/setUVsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/boxBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/capsuleBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/cylinderBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/discBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/gridBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/icoSphereBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/meshBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/planeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/sphereBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/torusBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryCollectionBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryOptimizeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryTransformBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/mergeGeometryBlock.ts
Labels: skip changelog

#14280 Add an option to lock random values per loop
  packages/dev/core/src/Meshes/Node/Blocks/randomBlock.ts
Labels: skip changelog

#14282 Fix few bugs
  packages/dev/core/src/Maths/math.vector.ts
  packages/dev/core/src/Meshes/Node/Blocks/Matrices/alignBlock.ts
  packages/tools/nodeGeometryEditor/src/components/propertyTab/inputsPropertyTabComponent.tsx
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTabComponent.tsx
Labels: skip changelog

#14283 Fix issue with merge conflicts when data was not present
  packages/dev/core/src/Meshes/mesh.vertexData.ts
Labels: skip changelog

#14284 MeshLine: Add support for thin instances
  packages/dev/core/src/Meshes/linesMesh.ts
Labels: enhancement, rendering engine

#14285 Effect: Call pipelineContext.setUIntX instead of setIntX for the unsigned variants
  packages/dev/core/src/Materials/effect.ts
Labels: bug, materials

#14286 Idempotent disposing of physics bodies and shapes.
  packages/dev/core/src/Physics/v2/physicsBody.ts
  packages/dev/core/src/Physics/v2/physicsShape.ts
Labels: bug, physics

#14289 Optimize block on context by default
  packages/dev/core/src/Meshes/Node/Blocks/geometryOptimizeBlock.ts
Labels: skip changelog

#14288 Fix #14281
  packages/dev/core/src/Meshes/Node/Blocks/Teleport/teleportInBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Teleport/teleportOutBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/debugBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryInputBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometry.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/blockNodeData.ts
Labels: skip changelog

#14290 Add a rebuild button
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTabComponent.tsx
Labels: skip changelog

#14291 Fix scale for noiseblock
  packages/dev/core/src/Meshes/Node/Blocks/noiseBlock.ts
Labels: skip changelog

#14293 Document adding and updating visual snapshots
  buildSystem.md
Labels: skip changelog

#14294 Fix geom caching
  packages/dev/core/src/Meshes/Node/Blocks/geometryInfoBlock.ts
Labels: skip changelog

#14299 Fix #14295
  packages/dev/core/src/Meshes/Node/Blocks/boundingBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: skip changelog

#14298 Fix #14296
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnFacesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVerticesBlock.ts
  packages/dev/core/src/Meshes/mesh.vertexData.ts
Labels: skip changelog

#14302 Fix adapt to not trigger with undefined
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
Labels: skip changelog

#14297 Nge texture
  packages/dev/core/src/Meshes/Node/Blocks/Textures/geometryTextureBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Textures/geometryTextureFetchBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/debugBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryTransformBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryTrigonometryBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/mapRangeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/mathBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/normalizeVectorBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/randomBlock.ts
  packages/dev/core/src/Meshes/Node/Enums/nodeGeometryConnectionPointTypes.ts
  packages/dev/core/src/Meshes/Node/Interfaces/nodeGeometryTextureData.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/dev/core/src/Meshes/Node/nodeGeometry.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/display/textureDisplayManager.modules.scss
  packages/tools/nodeGeometryEditor/src/graphSystem/display/textureDisplayManager.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/textureNodePropertyComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/registerDebugSupport.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/registerNodePortDesign.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/registerToDisplayLedger.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/registerToPropertyLedger.ts
Labels: skip changelog

#14305 Bump mapping: Fix parallax mapping in right handed mode
  packages/dev/core/src/Materials/Node/Blocks/Fragment/perturbNormalBlock.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/Shaders/ShadersInclude/bumpFragmentFunctions.fx
Labels: bug, materials

#14307 Allow debug nodes to be terminal
  packages/dev/core/src/Meshes/Node/Blocks/debugBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
Labels: skip changelog, nge

#14310 Add more locking mode for random block
  packages/dev/core/src/Meshes/Node/Blocks/randomBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
Labels: skip changelog, nge

#14314 Texture: Set type and format at load time
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: bug, texture

#14309 Mesh: Fix subMesh bounding info when mesh has thin instances
  packages/dev/core/src/Meshes/subMesh.ts
Labels: bug, rendering engine

#14319 Better icons
  packages/tools/nodeGeometryEditor/src/graphSystem/registerNodePortDesign.ts
Labels: skip changelog

#14321 more outputs
  packages/dev/core/src/Meshes/Node/Blocks/Textures/geometryTextureFetchBlock.ts
Labels: skip changelog

#14322 Fix PBR double sided lighting harmonics
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
Labels: bug, materials

#14323 Add missing collision and trigger events to IPhysicsEnginePluginV2 in…
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
Labels: enhancement, physics

#14320 flow graph: arithmetic and logic nodes
  packages/dev/core/src/FlowGraph/Blocks/Data/Logic/flowGraphLogicBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphNumberMathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphVector2MathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphVector3MathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphVector4MathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphAddBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphBinaryOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphConstantOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphUnaryOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/index.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/flowGraphSceneTickEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/index.ts
  packages/dev/core/src/FlowGraph/flowGraphDataConnection.ts
Labels: new feature, flow graph

#14325 Add an ugly flag to glTF draco loader extension
  packages/dev/core/src/Meshes/Compression/dracoCompression.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_draco_mesh_compression.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: skip changelog

#14326 STL loader: Fix out of memory when loading big stl files
  packages/dev/loaders/src/STL/stlFileLoader.ts
Labels: enhancement, loaders

#14329 Add morph target names to gltf serializer
  packages/dev/serializers/src/glTF/2.0/glTFExporter.ts
Labels: exporters, glTF

#14126 Auto compute texture size in wrapNativeTexture
  packages/dev/core/src/Engines/engine.ts
  packages/dev/core/src/Engines/nativeEngine.ts
Labels: skip changelog

#14332 Flow graph pause animation node
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphPauseAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphPlayAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphStopAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/index.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/index.ts
Labels: new feature, flow graph

#14335 Texture loading: Fix regression with compressed textures not working anymore
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: bug, texture

#14336 Fix PBR transmission in Webgl1
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
Labels: bug, materials

#14316 Fixes and enhancements for gizmos
  packages/dev/core/src/Gizmos/axisDragGizmo.ts
  packages/dev/core/src/Gizmos/axisScaleGizmo.ts
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
  packages/dev/core/src/Gizmos/gizmo.ts
  packages/dev/core/src/Gizmos/planeDragGizmo.ts
  packages/dev/core/src/Gizmos/planeRotationGizmo.ts
  packages/dev/core/src/Gizmos/scaleGizmo.ts
  packages/dev/inspector/src/components/globalState.ts
  packages/dev/inspector/src/components/sceneExplorer/entities/cameraTreeItemComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/entities/lightTreeItemComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/entities/sceneTreeItemComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/sceneExplorerComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/treeItemComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/treeItemSelectableComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/treeItemSpecializedComponent.tsx
Labels: bug, enhancement, gizmos

#14341 [XR] initiateRoomCapture added to plane detection feature
  packages/dev/core/src/LibDeclarations/webxr.d.ts
  packages/dev/core/src/XR/features/WebXRPlaneDetector.ts
Labels: enhancement, VR/AR/XR

#14339 Playwright test timeout configuration
  packages/tools/tests/test/playwright/visualizationPlaywright.utils.ts
Labels: skip changelog

#14342 comments!!
  packages/dev/core/src/Buffers/buffer.ts
Labels: skip changelog

#14343 CascadedShadowGenerator: Fix shadowMaxZ upper bound checking when using an infinite far camera plane
  packages/dev/core/src/Lights/Shadows/cascadedShadowGenerator.ts
Labels: bug, shadows

#14344 Animations: Add some animation getter helpers
  packages/dev/core/src/Animations/animatable.ts
  packages/dev/core/src/Animations/animationGroup.ts
Labels: enhancement, animations

#14334 Add bitwise blocks to Flow Graph
  packages/dev/core/src/FlowGraph/Blocks/Data/Logic/flowGraphBitwiseBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Logic/index.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/index.ts
Labels: new feature, flow graph

#14346 Update component if the label has changed
  packages/dev/sharedUiComponents/src/lines/sliderLineComponent.tsx
Labels: bug, inspector

#14327 Flow graph control flow nodes - 1
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphNumberMathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphBinaryOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphConditionalDataBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphConstantOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphGetVariableBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphUnaryOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/flowGraphReceiveCustomEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphPlayAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphConditionalBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphCounterBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphDoNBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphForLoopBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphMultiGateBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphSwitchBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphThrottleBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphTimerBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphWaitAllBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphWhileLoopBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/index.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphLogBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSetVariableBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/index.ts
  packages/dev/core/src/FlowGraph/flowGraphConnection.ts
  packages/dev/core/src/FlowGraph/flowGraphContext.ts
  packages/dev/core/src/FlowGraph/flowGraphDataConnection.ts
  packages/dev/core/src/FlowGraph/flowGraphExecutionBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphSignalConnection.ts
Labels: new feature, flow graph

#14349 Fix to styling of NME and NGE
  packages/tools/nodeEditor/src/components/nodeList/nodeList.scss
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeEditor/src/components/propertyTab/propertyTab.scss
  packages/tools/nodeEditor/src/graphEditor.tsx
  packages/tools/nodeEditor/src/main.scss
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeList.scss
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTab.scss
  packages/tools/nodeGeometryEditor/src/graphEditor.tsx
  packages/tools/nodeGeometryEditor/src/main.scss
Labels: bug, nme, nge

#14351 Better fix for recent Draco changes
  packages/dev/core/src/Buffers/buffer.ts
  packages/dev/core/src/Meshes/Compression/dracoCompression.ts
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#14354 Fix a typo
  packages/dev/materials/src/custom/pbrCustomMaterial.ts
Labels: skip changelog

#14359 switch all dependencies to CDN Serve and Watch
  .vscode/launch.json
  .vscode/tasks.json
Labels: skip changelog

#14355 Flow graph control flow blocks 2
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/index.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/index.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphDebounceBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphFlipFlopBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/index.ts
Labels: new feature, flow graph

#14360 Texture cache fix
  packages/dev/core/src/Materials/Textures/equiRectangularCubeTexture.ts
  packages/dev/core/src/Materials/Textures/texture.ts
Labels: skip changelog

#14350 add FlowGraphEngine class
  packages/dev/core/src/FlowGraph/flowGraph.ts
  packages/dev/core/src/FlowGraph/flowGraphCoordinator.ts
  packages/dev/core/src/FlowGraph/index.ts
Labels: new feature, flow graph

#14362 Fix crash bug when no mesh data is provided
  packages/dev/core/src/Meshes/Node/Blocks/geometryCollectionBlock.ts
Labels: skip changelog

#14333 Add coordinate transform and constant value blocks
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphConstantBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphCoordinateTransformBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/index.ts
  packages/dev/core/src/FlowGraph/flowGraphRichTypes.ts
Labels: new feature, flow graph

#14357 flow graphs vector and matrix math
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphMatrixBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphVector2MathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphVector3MathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphVector4MathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/index.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/index.ts
  packages/dev/core/src/FlowGraph/flowGraphDataConnection.ts
  packages/dev/core/src/FlowGraph/flowGraphRichTypes.ts
Labels: new feature, flow graph

#14367 OIT: Fix viewport not set correctly
  packages/dev/core/src/Rendering/depthPeelingRenderer.ts
Labels: bug, rendering engine

#14365 Gizmos fixes and small improvements
  packages/dev/core/src/Behaviors/Meshes/pointerDragBehavior.ts
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
  packages/dev/core/src/Gizmos/gizmo.ts
  packages/dev/core/src/Gizmos/planeRotationGizmo.ts
  packages/dev/core/src/Gizmos/positionGizmo.ts
  packages/dev/core/src/Gizmos/rotationGizmo.ts
  packages/dev/core/src/Gizmos/scaleGizmo.ts
  packages/dev/core/src/Maths/math.vector.ts
Labels: enhancement, gizmos

#14371 Mesh: Add a helper method to draw a mesh given a render pass id
  packages/dev/core/src/Materials/uniformBuffer.ts
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/core/src/Misc/tools.ts
Labels: enhancement, rendering engine

#14372 AnimationGroup: Fix onAnimationGroupLoop observable not triggered when mask is not empty
  packages/dev/core/src/Animations/animationGroup.ts
Labels: bug, animations

#14373 Fix stupid bug
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVolumeBlock.ts
Labels: skip changelog, nge
