Repository BabylonJS/Babylon.js, pull requests merged in 2023-10, with the labels that each got.

#14377 Procedural texture: Allow to pass shader code when creating a procedural texture
  packages/dev/core/src/Materials/Textures/Procedurals/proceduralTexture.ts
Labels: enhancement, texture

#14378 WebGPU: Sync with the spec
  packages/dev/core/src/Engines/WebGPU/webgpuCacheRenderPipeline.ts
  packages/dev/core/src/Engines/WebGPU/webgpuConstants.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureHelper.ts
  packages/dev/core/src/LibDeclarations/webgpu.d.ts
Labels: skip changelog

#14379 Geometry buffer renderer: Add an option to generate normals in world space
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssao2RenderingPipeline.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssrRenderingPipeline.ts
  packages/dev/core/src/PostProcesses/screenSpaceCurvaturePostProcess.ts
  packages/dev/core/src/PostProcesses/screenSpaceReflectionPostProcess.ts
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/core/src/Shaders/geometry.fragment.fx
  packages/dev/core/src/Shaders/geometry.vertex.fx
Labels: enhancement, rendering engine

#14384 WebGPU: Fix bug introduced by #14378
  packages/dev/core/src/Engines/WebGPU/webgpuTextureHelper.ts
Labels: bug, WebGPU

#14385 Fix missing data when using booleans
  packages/dev/core/src/Meshes/Node/Blocks/booleanGeometryBlock.ts
Labels: skip changelog, nge

#14386 Fix #14381
  packages/dev/core/src/Meshes/Node/Blocks/Sources/meshBlock.ts
Labels: skip changelog, nge

#14352 ArcRotateCamera: Modify mapPanning to account for upVector
  packages/dev/core/src/Cameras/arcRotateCamera.ts
Labels: bug, inputs, breaking change

#14395 Add gltf with bad draco test
  packages/tools/tests/test/visualization/ReferenceImages/gltfBadDraco.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#14397 WebGPU: Add labels to buffers + support non float vertex buffers
  packages/dev/core/src/Animations/animationGroup.ts
  packages/dev/core/src/Buffers/buffer.ts
  packages/dev/core/src/Buffers/storageBuffer.ts
  packages/dev/core/src/Engines/Extensions/engine.storageBuffer.ts
  packages/dev/core/src/Engines/Extensions/engine.uniformBuffer.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.storageBuffer.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.uniformBuffer.ts
  packages/dev/core/src/Engines/WebGPU/webgpuBufferManager.ts
  packages/dev/core/src/Engines/WebGPU/webgpuCacheRenderPipeline.ts
  packages/dev/core/src/Engines/WebGPU/webgpuDrawContext.ts
  packages/dev/core/src/Engines/WebGPU/webgpuPipelineContext.ts
  packages/dev/core/src/Engines/WebGPU/webgpuQuerySet.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessingContext.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessor.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsGLSL.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureHelper.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTintWASM.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/effect.ts
  packages/dev/core/src/Materials/meshDebugPluginMaterial.ts
  packages/dev/core/src/Materials/uniformBuffer.ts
  packages/dev/core/src/Meshes/geometry.ts
  packages/dev/core/src/Shaders/ShadersInclude/shadowsFragmentFunctions.fx
  packages/tools/tests/test/visualization/config.json
Labels: new feature, WebGPU

#14402 NME: Add support for reflectivity to the PrePassOutput block
  packages/dev/core/src/Materials/Node/Blocks/Fragment/prePassOutputBlock.ts
Labels: enhancement, nme

#14401 WebGPU: fix uniform analysis deactivation
  packages/dev/core/src/Engines/WebGPU/webgpuTintWASM.ts
Labels: WebGPU, skip changelog

#14387 ArcRotateCamera: Modified zoomOn to use same logic as FramingBehavior
  packages/dev/core/src/Behaviors/Cameras/framingBehavior.ts
  packages/dev/core/src/Cameras/arcRotateCamera.ts
  packages/dev/core/test/unit/Cameras/babylon.arcRotateCameraInputs.test.ts
Labels: bug

#14172 P8 NGE linear and radial cloner blocks
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateLinearBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateRadialBlock.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: skip changelog

#14407 Reuse / fix maths / simplify
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateBaseBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateLinearBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateRadialBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
Labels: skip changelog

#14408 fix feedback from 14398
  packages/tools/nodeEditor/src/components/preview/svgs/icon-ibl.svg
Labels: skip changelog

#14415 add reminders for cdn usage
  packages/public/umd/babylonjs-gui/readme.md
  packages/public/umd/babylonjs-inspector/readme.md
  packages/public/umd/babylonjs-loaders/readme.md
  packages/public/umd/babylonjs-materials/readme.md
  packages/public/umd/babylonjs-post-process/readme.md
  packages/public/umd/babylonjs-procedural-textures/readme.md
  packages/public/umd/babylonjs-viewer/readme.md
  readme.md
Labels: skip changelog

#14418 Fix render to texture mips
  packages/dev/core/src/Engines/WebGL/webGLRenderTargetWrapper.ts
  packages/dev/core/src/Engines/thinEngine.ts
Labels: bug, rendering engine, texture

#14416 Fix #14414
  packages/dev/core/src/Meshes/Node/Blocks/Sources/meshBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Textures/geometryTextureBlock.ts
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTabComponent.tsx
Labels: skip changelog, nge

#14419 Texture: Serialize the noMipmap property
  packages/dev/core/src/Materials/Textures/texture.ts
Labels: bug, texture

#14389 Flow graphs serialization
  packages/dev/core/src/FlowGraph/Blocks/Data/Logic/flowGraphBitwiseBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Logic/flowGraphLogicBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphMatrixBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphNumberMathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphVector2MathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphVector3MathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphVector4MathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphBinaryOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphConditionalDataBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphConstantBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphConstantOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphCoordinateTransformBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphGetVariableBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphUnaryOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/flowGraphMeshPickEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/flowGraphReceiveCustomEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/flowGraphSceneReadyEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/flowGraphSceneTickEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphPauseAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphPlayAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphStopAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Audio/flowGraphPlayAudioBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Audio/flowGraphStopAudioBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphBranchBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphCounterBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphDebounceBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphDoNBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphFlipFlopBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphForLoopBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphMultiGateBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphSwitchBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphThrottleBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphTimerBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphWaitAllBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphWhileLoopBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphCustomFunctionBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphLogBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSendCustomEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSetPropertyBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSetVariableBlock.ts
  packages/dev/core/src/FlowGraph/flowGraph.ts
  packages/dev/core/src/FlowGraph/flowGraphAsyncExecutionBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphConnection.ts
  packages/dev/core/src/FlowGraph/flowGraphContext.ts
  packages/dev/core/src/FlowGraph/flowGraphCoordinator.ts
  packages/dev/core/src/FlowGraph/flowGraphDataConnection.ts
  packages/dev/core/src/FlowGraph/flowGraphExecutionBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphRichTypes.ts
  packages/dev/core/src/FlowGraph/flowGraphSignalConnection.ts
  packages/dev/core/src/FlowGraph/flowGraphVariableDefinitions.ts
  packages/dev/core/src/FlowGraph/flowGraphWithOnDoneExecutionBlock.ts
  packages/dev/core/test/unit/FlowGraph/flowGraphDataNodes.test.ts
  packages/dev/core/test/unit/FlowGraph/flowGraphEventNodes.test.ts
  packages/dev/core/test/unit/FlowGraph/flowGraphExecutionNodes.test.ts
  packages/dev/core/test/unit/FlowGraph/flowGraphSerialization.test.ts
Labels: new feature, flow graph

#14422 WebGL engine: Add a loseContextOnDispose option
  packages/dev/core/src/Engines/thinEngine.ts
Labels: enhancement, rendering engine

#14413 WebGPU: support vertex buffers with non multiple of 4 bytes strides
  packages/dev/core/src/Buffers/buffer.align.ts
  packages/dev/core/src/Buffers/buffer.ts
  packages/dev/core/src/Buffers/index.ts
  packages/dev/core/src/Engines/WebGPU/webgpuCacheRenderPipeline.ts
  packages/dev/core/src/Engines/engineFeatures.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/nullEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Meshes/geometry.ts
  packages/tools/tests/test/visualization/ReferenceImages/VertexBuffer-non-aligned-strides.png
  packages/tools/tests/test/visualization/config.json
Labels: rendering engine, WebGPU

#14425 DefaultRenderingPipeline: Fix pipeline reconstruction
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/defaultRenderingPipeline.ts
Labels: bug, post-process

#14433 Fix #14432
  packages/dev/core/src/Meshes/Node/Blocks/Sources/meshBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Textures/geometryTextureBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometry.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTabComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/meshNodePropertyComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/textureNodePropertyComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/registerExportData.ts
  packages/tools/nodeGeometryEditor/src/serializationTools.ts
Labels: skip changelog

#14435 Remove crash
  packages/dev/core/src/Meshes/Node/Blocks/Textures/geometryTextureFetchBlock.ts
Labels: skip changelog

#14427 proper use filter in getTags function
  packages/dev/core/src/scene.ts
  packages/dev/core/test/unit/Scene/babylon.scene.test.ts
Labels: bug, breaking change

#14436 Fix createTexture for R and RG format textures
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/test/unit/Engines/thinEngine.test.ts
Labels: enhancement, texture

#14440 Unification and allowedHosts in local dev
  package-lock.json
  packages/dev/buildTools/src/webpackTools.ts
  packages/public/babylonjs-viewer-assets/webpack.config.js
  packages/tools/babylonServer/webpack.config.js
  packages/tools/babylonServer/webpack.config.snapshot.js
  packages/tools/devHost/webpack.config.js
  packages/tools/guiEditor/webpack.config.js
  packages/tools/nodeEditor/webpack.config.js
  packages/tools/nodeGeometryEditor/webpack.config.js
  packages/tools/playground/webpack.config.js
  packages/tools/sandbox/webpack.config.js
  packages/tools/viewer/webpack.config.js
  packages/tools/vsm/webpack.config.js
Labels: enhancement, build

#14438 Add flag on ADT to skip blocking certain events
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
Labels: gui, new feature

#14431 font inheritance changes
  packages/dev/gui/src/2D/controls/control.ts
  packages/tools/tests/test/visualization/ReferenceImages/Childoverridingparentfontproperties.png
  packages/tools/tests/test/visualization/ReferenceImages/Font-style-inheritance.png
  packages/tools/tests/test/visualization/ReferenceImages/Fontsizeinheritance.png
  packages/tools/tests/test/visualization/config.json
Labels: enhancement

#14428 Oblique Camera Implementation
  packages/dev/core/src/Cameras/camera.ts
  packages/dev/core/src/Maths/math.vector.ts
Labels: enhancement, rendering engine

#14441 Faster twin renderer
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
  packages/dev/gui/src/2D/controls/control.ts
  packages/tools/accessibility/src/HtmlTwin/htmlTwinAccessibilityItem.tsx
  packages/tools/accessibility/src/HtmlTwin/htmlTwinGUIItem.ts
  packages/tools/accessibility/src/HtmlTwin/htmlTwinHostComponent.tsx
  packages/tools/accessibility/src/HtmlTwin/htmlTwinItem.ts
  packages/tools/accessibility/src/HtmlTwin/htmlTwinItem.tsx
  packages/tools/accessibility/src/HtmlTwin/htmlTwinItemAdapter.tsx
  packages/tools/accessibility/src/HtmlTwin/htmlTwinNodeItem.ts
  packages/tools/accessibility/src/HtmlTwin/htmlTwinSceneContext.tsx
  packages/tools/accessibility/src/HtmlTwin/htmlTwinSceneTree.tsx
  packages/tools/accessibility/src/HtmlTwin/htmlTwinTreeComponent.tsx
Labels: enhancement, accessibility

#14448 Fix texture sampler precision for skinning and morph
  packages/dev/core/src/Shaders/ShadersInclude/bonesDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/morphTargetsVertexGlobalDeclaration.fx
Labels: bug, rendering engine

#14450 Fix key navigation in scene explorer
  packages/dev/inspector/src/components/sceneExplorer/sceneExplorerComponent.tsx
Labels: bug, inspector

#14449 ShadowDepthWrapper: Fix a memory leak when new effects must be created
  packages/dev/core/src/Materials/shadowDepthWrapper.ts
Labels: bug, shadows

#14455 Fix an issue in the mesh parsing code
  packages/dev/core/src/Meshes/mesh.ts
Labels: skip changelog

#14452 Fix stack panel giving a warning for children with resizeToFit.
  packages/dev/gui/src/2D/controls/stackPanel.ts
Labels: bug, gui

#14456 Fix instanced buffers of cloned meshes
  packages/dev/core/src/Meshes/instancedMesh.ts
Labels: bug

#14457 Function to add element and all its children to AssetContainer
  packages/dev/core/src/assetContainer.ts
Labels: enhancement

#14463 CreateScreenshotUsingRenderTarget: Render to texture only when texture and camera are ready
  packages/dev/core/src/Misc/screenshotTools.ts
Labels: bug, rendering engine

#14467 Fix transform node world space rotation when parent has negative world matrix determinant
  packages/dev/core/src/Meshes/transformNode.ts
Labels: bug, rendering engine

#14453 Flow graph node caching
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphBinaryOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphCachedOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphConstantOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphUnaryOperationBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphContext.ts
  packages/dev/core/src/FlowGraph/flowGraphSignalConnection.ts
  packages/dev/core/test/unit/FlowGraph/flowGraphDataNodes.test.ts
  packages/dev/core/test/unit/FlowGraph/flowGraphExecutionNodes.test.ts
Labels: skip changelog

#14471 Fix #14466
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnFacesBlock.ts
  packages/dev/core/src/Meshes/Node/Interfaces/nodeGeometryExecutionContext.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
  packages/dev/core/src/assetContainer.ts
Labels: skip changelog, nge

#14470 Add ground projection support
  packages/dev/core/src/Materials/Background/backgroundMaterial.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/reflectionTextureBaseBlock.ts
  packages/dev/core/src/Shaders/ShadersInclude/backgroundFragmentDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/backgroundUboDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/helperFunctions.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrHelperFunctions.fx
  packages/dev/core/src/Shaders/background.fragment.fx
  packages/dev/core/src/Shaders/default.fragment.fx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/backgroundMaterialPropertyGridComponent.tsx
  packages/tools/tests/test/visualization/ReferenceImages/groundProjection.png
  packages/tools/tests/test/visualization/config.json
Labels: materials, new feature

#14473 Fix gltf validator url
  packages/dev/loaders/src/glTF/glTFValidation.ts
Labels: skip changelog

#14475 fix stack panel GUI warnings
  packages/dev/gui/src/2D/controls/stackPanel.ts
Labels: bug, gui

#14451 Adapt post process to viewport in DefaultRenderingPipeline
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/defaultRenderingPipeline.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/postProcessRenderPipeline.ts
Labels: enhancement, post-process

#14480 ShaderMaterial: Make sure the color attribute is not duplicated
  packages/dev/core/src/Materials/shaderMaterial.ts
Labels: bug, rendering engine
