Repository BabylonJS/Babylon.js, pull requests merged in 2023-11, with the labels that each got.

#14485 Allow matrix transposeToRef to work in place
  packages/dev/core/src/Maths/math.vector.ts
Labels: bug, math

#14486 Fix shallow copies of referenced objects
  packages/dev/core/src/Meshes/GreasedLine/greasedLineMesh.ts
  packages/dev/core/src/Meshes/GreasedLine/greasedLineRibbonMesh.ts
  packages/dev/core/src/Misc/deepCopier.ts
Labels: bug, rendering engine

#14488 Better eval context evaluation
  packages/dev/core/src/Meshes/Node/Blocks/Sources/boxBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/capsuleBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/cylinderBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/discBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/gridBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/icoSphereBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/planeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/sphereBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/torusBlock.ts
Labels: skip changelog

#14487 GLTF loading dirty mechanism perf
  packages/dev/core/src/Materials/Textures/baseTexture.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/Materials/Textures/texture.ts
  packages/dev/core/src/Materials/materialPluginManager.ts
  packages/dev/core/src/scene.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/EXT_lights_image_based.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_lights_punctual.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: enhancement, glTF

#14491 refactor: Optimized the Observable.add type
  packages/dev/core/src/Misc/observable.ts
Labels: skip changelog

#14493 CreateText does not align text on z
  packages/dev/core/src/Meshes/Builders/textBuilder.ts
Labels: bug, breaking change, geometry

#14492 Fix ray cast skipBoundingInfo with in intersects
  packages/dev/core/src/Meshes/abstractMesh.ts
Labels: bug, math

#14495 Flow Graph Context Logger
  packages/dev/core/src/FlowGraph/flowGraphContext.ts
  packages/dev/core/src/FlowGraph/flowGraphContextLogger.ts
  packages/dev/core/src/FlowGraph/flowGraphDataConnection.ts
  packages/dev/core/src/FlowGraph/flowGraphEventBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphSignalConnection.ts
  packages/dev/core/src/FlowGraph/index.ts
Labels: enhancement, flow graph

#14497 Animations: Add an easingFunction property to IAnimationKey
  packages/dev/core/src/Animations/animation.ts
  packages/dev/core/src/Animations/animationKey.ts
Labels: enhancement, animations

#14499 Flow graph remove event coordinator
  packages/dev/core/src/FlowGraph/Blocks/Event/flowGraphReceiveCustomEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSendCustomEventBlock.ts
  packages/dev/core/src/FlowGraph/flowGraph.ts
  packages/dev/core/src/FlowGraph/flowGraphContext.ts
  packages/dev/core/src/FlowGraph/flowGraphCoordinator.ts
  packages/dev/core/src/FlowGraph/flowGraphCustomEvent.ts
  packages/dev/core/src/FlowGraph/flowGraphEventCoordinator.ts
  packages/dev/core/src/FlowGraph/index.ts
Labels: skip changelog, flow graph

#14482 Camera: Modify Camera Movement to work off of time, instead of frame rate
  packages/dev/core/src/Animations/animatable.ts
  packages/dev/core/src/Behaviors/Meshes/fadeInOutBehavior.ts
  packages/dev/core/src/Cameras/arcRotateCamera.ts
  packages/dev/core/src/Cameras/camera.ts
  packages/dev/core/src/Cameras/targetCamera.ts
  packages/dev/core/src/Engines/constants.ts
  packages/dev/core/src/Misc/precisionDate.ts
  packages/dev/core/src/scene.ts
  packages/dev/core/test/unit/DeviceInput/babylon.inputManager.test.ts
  packages/tools/tests/test/visualization/ReferenceImages/SpaceDeK.png
  packages/tools/tests/test/visualization/ReferenceImages/particles.png
  packages/tools/tests/test/visualization/ReferenceImages/prepass-ssao-particles.png
  packages/tools/tests/test/visualization/ReferenceImages/subemitters.png
Labels: bug, inputs, breaking change

#14502 Add optional color option to camera gizmo
  packages/dev/core/src/Gizmos/cameraGizmo.ts
Labels: enhancement

#14507 Fix dynamic texture clear with transparency
  packages/dev/core/src/Materials/Textures/dynamicTexture.ts
Labels: bug, texture

#14509 CreateText does not align text on z
  packages/dev/core/src/Meshes/Builders/textBuilder.ts
Labels: skip changelog

#14510 Revert "Camera: Modify Camera Movement to work off of time
  packages/dev/core/src/Animations/animatable.ts
  packages/dev/core/src/Behaviors/Meshes/fadeInOutBehavior.ts
  packages/dev/core/src/Cameras/arcRotateCamera.ts
  packages/dev/core/src/Cameras/camera.ts
  packages/dev/core/src/Cameras/targetCamera.ts
  packages/dev/core/src/Engines/constants.ts
  packages/dev/core/src/Misc/precisionDate.ts
  packages/dev/core/src/scene.ts
  packages/dev/core/test/unit/DeviceInput/babylon.inputManager.test.ts
  packages/tools/tests/test/visualization/ReferenceImages/SpaceDeK.png
  packages/tools/tests/test/visualization/ReferenceImages/particles.png
  packages/tools/tests/test/visualization/ReferenceImages/prepass-ssao-particles.png
  packages/tools/tests/test/visualization/ReferenceImages/subemitters.png
Labels: bug

#14514 Fix light in NME
  packages/dev/core/src/Materials/Node/Blocks/Dual/lightBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
Labels: bug, nme

#14521 Fix #14478
  packages/dev/core/src/Meshes/Node/Blocks/Sources/boxBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/capsuleBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/cylinderBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/discBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/gridBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/icoSphereBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/planeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/sphereBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/torusBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlockConnectionPoint.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/genericNodePropertyComponent.tsx
Labels: skip changelog

#14520 Material: Fix wrong normal when material has two sided lighting enabled
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug, materials

#14522 Fix crash when one teleport was not serialized
  packages/dev/core/src/Meshes/Node/nodeGeometry.ts
Labels: skip changelog

#14528 DepthRenderer: Support point rendering
  packages/dev/core/src/Rendering/depthRenderer.ts
  packages/dev/core/src/Shaders/depth.vertex.fx
Labels: rendering engine, new feature

#14529 Fix teleport node target
  packages/dev/core/src/Materials/Node/Blocks/Teleport/teleportInBlock.ts
Labels: skip changelog

#14533 Fix inputTextArea isReadOnly
  packages/dev/gui/src/2D/controls/inputTextArea.ts
Labels: bug, gui

#14532 Usability Fix
  packages/dev/core/src/Maths/math.vector.ts
Labels: skip changelog

#14535 Multi canvas rendering: Allow multiple cameras when registering a view
  packages/dev/core/src/Engines/Extensions/engine.views.ts
Labels: enhancement, rendering engine

#14536 OIT: Add a isReady method to the depth peeling renderer
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.multiRender.ts
  packages/dev/core/src/Materials/Textures/multiRenderTarget.ts
  packages/dev/core/src/Rendering/depthPeelingRenderer.ts
  packages/dev/core/src/scene.ts
Labels: enhancement, rendering engine

#14537 Update skeletonViewer.ts
  packages/dev/core/src/Debug/skeletonViewer.ts
Labels: skip changelog

#14540 glTF loader: Fix checking bounds when creating a typed array
  packages/dev/loaders/src/glTF/glTFFileLoader.ts
Labels: bug, glTF

#14541 Fix highlight layer properties in inspector
  packages/dev/core/src/XR/features/WebXRRawCameraAccess.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/layers/layerPropertyGridComponent.tsx
Labels: bug, inspector

#14542 glTF transmission: Fix rendering sprites and particle systems in the opaque texture
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_materials_transmission.ts
Labels: bug, glTF

#14546 Engine: Misc helpers
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/core/src/Rendering/geometryBufferRendererSceneComponent.ts
Labels: skip changelog

#14552 Engine: Misc helpers
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
Labels: skip changelog

#14553 Thin instances: Support forcedInstanceCount with thin instances
  packages/dev/core/src/Meshes/mesh.ts
Labels: rendering engine, new feature

#14554 Simple One Word Typo Fix
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/particleSystemPropertyGridComponent.tsx
Labels: skip changelog

#14551 Mesh: Add a setIndexBuffer method
  packages/dev/core/src/Meshes/geometry.ts
  packages/dev/core/src/Meshes/mesh.ts
Labels: rendering engine, new feature

#14557 Fix incorrect range check when reading glTF buffer
  packages/dev/loaders/src/glTF/glTFFileLoader.ts
Labels: skip changelog

#14560 Fix for animations with relative loop mode.
  packages/dev/core/src/Animations/animation.ts
  packages/dev/core/src/Animations/runtimeAnimation.ts
  packages/dev/core/src/Maths/math.size.ts
Labels: bug, animations, ace

#14562 Fix camera rotation when exporting glTF
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/dev/serializers/src/glTF/2.0/glTFExporter.ts
Labels: bug

#14561 Fix opaque only picking for rotated controls
  packages/dev/core/src/Engines/ICanvas.ts
  packages/dev/gui/src/2D/controls/image.ts
Labels: bug, gui

#14568 Post process: Add support for uniform buffers
  packages/dev/core/src/PostProcesses/postProcess.ts
Labels: rendering engine, new feature

#14569 Add analytics
  packages/tools/nodeEditor/public/index.html
  packages/tools/nodeGeometryEditor/public/index.html
  packages/tools/playground/public/debug.html
  packages/tools/playground/public/frame.html
  packages/tools/playground/public/full.html
  packages/tools/playground/public/index.html
  packages/tools/sandbox/public/index.html
Labels: skip changelog
