Repository BabylonJS/Babylon.js, pull requests merged in 2023-02, with the labels that each got.

#13490 Check for invalid hierarchies in the asset container and warn the user
  packages/dev/core/src/assetContainer.ts
Labels: enhancement, assets

#13491 Nme updates
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodeLedger.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/searchBox.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/searchBox.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
Labels: enhancement, nme

#13496 Fix conditions for clone vs instance in AssetContainer.instantiateHie…
  packages/dev/core/src/assetContainer.ts
Labels: assets, skip changelog

#13497 Fix ClipPlane being unset
  packages/dev/core/src/Materials/clipPlaneMaterialHelper.ts
Labels: skip changelog

#13495 Nme updates part 2
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/searchBox.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/tools/nodeEditor/src/graphEditor.tsx
Labels: enhancement, new feature, nme

#13499 Texture: Fix doc for sampling modes
  packages/dev/core/src/Materials/Textures/texture.ts
Labels: skip changelog

#13500 KTXDecoder: Fix crash with "buffer already detached"
  packages/dev/core/src/Misc/khronosTextureContainer2.ts
  packages/tools/tests/test/visualization/ReferenceImages/Loading glTF model with KTX2 textures.png
  packages/tools/tests/test/visualization/config.json
Labels: bug, glTF

#13504 Fix for sprite rendering for ios 14 and lower
  packages/dev/core/src/Shaders/sprites.fragment.fx
Labels: skip changelog

#13506 KhronosTextureContainer2: minor code formating
  packages/dev/core/src/Misc/khronosTextureContainer2.ts
Labels: skip changelog

#13505 Physics iteration 6
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
  packages/dev/core/src/Physics/v2/physicsBody.ts
Labels: physics, skip changelog

#13503 Fix gui declaration
  packages/dev/gui/src/2D/controls/container.ts
  packages/dev/gui/src/2D/controls/rectangle.ts
Labels: skip changelog

#13501 Add Object Space mapping to NME PerturbNormal block
  packages/dev/core/src/Materials/Node/Blocks/Fragment/perturbNormalBlock.ts
  packages/dev/core/src/Shaders/ShadersInclude/bumpFragment.fx
  packages/dev/core/src/Shaders/ShadersInclude/bumpFragmentMainFunctions.fx
  packages/tools/tests/test/visualization/config.json
Labels: new feature, nme

#13508 WebGL2 Visualization tests: Log to the console by default, not to a file
  packages/tools/tests/test/visualization/visualization.webgl2.test.ts
Labels: skip changelog

#13510 Shader Fix
  packages/dev/core/src/Shaders/ShadersInclude/bumpFragmentMainFunctions.fx
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#13507 InputManager: Refine logic for handling non-captured pointerup events
  packages/dev/core/src/Inputs/scene.inputManager.ts
  packages/dev/core/test/unit/Cameras/babylon.arcRotateCameraInputs.test.ts
  packages/dev/core/test/unit/Cameras/babylon.freeCameraInputs.test.ts
  packages/dev/core/test/unit/DeviceInput/babylon.inputManager.test.ts
Labels: bug, inputs

#13511 better UI for title + bug fix for auto link
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodeLink.ts
Labels: skip changelog

#13513 VideoTexture - Resize the internal texture when the video size changes
  packages/dev/core/src/Materials/Textures/videoTexture.ts
Labels: bug, texture

#13512 Move to TypeScript 4.9.5
  package-lock.json
  package.json
  packages/dev/buildTools/src/ltsTransformer.ts
  packages/dev/core/src/Engines/Extensions/engine.multiRender.ts
  packages/dev/core/src/Engines/Extensions/engine.renderTarget.ts
  packages/tools/tests/src/umdCompile.ts
  packages/tools/tests/webpack.config.js
  packages/tools/viewer/src/managers/sceneManager.ts
Labels: new feature

#13515 fix type issue
  packages/dev/core/src/Maths/math.vector.ts
Labels: skip changelog

#13519 CustomMaterial: Don't prevent support for uniform arrays
  packages/dev/materials/src/custom/customMaterial.ts
  packages/dev/materials/src/custom/pbrCustomMaterial.ts
Labels: materials, new feature

#13518 Set event.sourceEvent in ExecuteCodeAction callback for pointer triggers
  packages/dev/core/src/Events/pointerEvents.ts
  packages/dev/core/src/Inputs/scene.inputManager.ts
Labels: new feature, inputs

#13520 Delay resize event listener to after video internal texture is created.
  packages/dev/core/src/Materials/Textures/videoTexture.ts
Labels: bug

#13521 Change InputManager._pickMove arg type to reduce number of casts needed
  packages/dev/core/src/Inputs/scene.inputManager.ts
Labels: inputs, skip changelog

#13516 DeviceInputSystem: Use correct pointerId for touch inputs on blur and pointercancel event
  packages/dev/core/src/DeviceInput/eventFactory.ts
  packages/dev/core/src/DeviceInput/webDeviceInputSystem.ts
Labels: bug, inputs

#13524 Fix to instantiate hierarchy
  packages/dev/core/src/Meshes/mesh.ts
  packages/tools/tests/test/visualization/ReferenceImages/Instantiate Hierarchy.png
  packages/tools/tests/test/visualization/config.json
Labels: bug

#13528 PBRMaterial: Fix INVERTCUBICMAP not being reset
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
Labels: bug, materials

#13530 Physics Iteration 7
  packages/dev/core/src/Debug/physicsViewer.ts
  packages/dev/core/src/Physics/v2/physicsBody.ts
Labels: physics

#13529 Fix option properties in InputNodePropertyComponent
  packages/tools/nodeEditor/src/graphSystem/properties/inputNodePropertyComponent.tsx
Labels: bug, nme

#13531 Fluid renderer: Fix rendering in right handed system
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingObject.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingTargetRenderer.ts
  packages/dev/core/src/Shaders/fluidRenderingParticleDepth.fragment.fx
  packages/dev/core/src/Shaders/fluidRenderingRender.fragment.fx
Labels: bug, rendering engine

#13533 Fix ANIMATESHEET for custom particle effect
  packages/dev/core/src/Particles/particleSystemComponent.ts
Labels: bug, particles

#13535 DefaultRenderingPipeline: Fix image processing not being reset in some cases
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/defaultRenderingPipeline.ts
Labels: bug, post-process

#13537 Add Clip plane support in Geometry Buffer
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/core/src/Shaders/geometry.fragment.fx
  packages/dev/core/src/Shaders/geometry.vertex.fx
Labels: bug, rendering engine

#13540 PBR: Fix realtime filtering for refraction
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockSubSurface.fx
Labels: bug, materials

#13538 Added ability to pass callback as key trigger parameter.
  packages/dev/core/src/Actions/actionManager.ts
Labels: new feature

#13541 WebGPU: Fix engine initialization
  packages/dev/core/src/Engines/engine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: bug, WebGPU

#13547 Materials: Fix depth state not set correctly with transparent meshes
  packages/dev/core/src/Engines/Extensions/engine.alpha.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.alpha.ts
Labels: bug, materials

#13548 PBR: Don't apply radiance occlusion to clearcoat
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockClearcoat.fx
Labels: bug, materials

#13550 Fix an issue building the sandbox
  packages/tools/sandbox/src/components/renderingZone.tsx
  packages/tools/testTools/src/utils.ts
  packages/tools/testTools/src/visualizationUtils.ts
Labels: skip changelog

#13552 Camera: Add code to update View and Projection Matrices in update function
  packages/dev/core/src/Cameras/camera.ts
  packages/dev/core/test/unit/DeviceInput/babylon.inputManager.test.ts
Labels: bug, inputs

#13336 SSR improvements
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/index.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssrRenderingPipeline.ts
  packages/dev/core/src/PostProcesses/screenSpaceReflectionPostProcess.ts
  packages/dev/core/src/Rendering/depthRenderer.ts
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/core/src/Rendering/prePassRendererSceneComponent.ts
  packages/dev/core/src/Rendering/screenSpaceReflections2Configuration.ts
  packages/dev/core/src/Shaders/ShadersInclude/screenSpaceRayTrace.fx
  packages/dev/core/src/Shaders/default.fragment.fx
  packages/dev/core/src/Shaders/depth.fragment.fx
  packages/dev/core/src/Shaders/depth.vertex.fx
  packages/dev/core/src/Shaders/geometry.fragment.fx
  packages/dev/core/src/Shaders/pbr.fragment.fx
  packages/dev/core/src/Shaders/screenSpaceReflection2.fragment.fx
  packages/dev/core/src/Shaders/screenSpaceReflection2Blur.fragment.fx
  packages/dev/core/src/Shaders/screenSpaceReflection2BlurCombiner.fragment.fx
  packages/tools/tests/test/visualization/ReferenceImages/Screen Space Reflections 2.png
  packages/tools/tests/test/visualization/config.json
Labels: enhancement, rendering engine

#13555 fix tag assignment when copying
  packages/dev/core/src/Misc/decorators.ts
Labels: bug

#13556 Add CPU side exact srgb conversions
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Helpers/environmentHelper.ts
  packages/dev/core/src/Materials/Background/backgroundMaterial.ts
  packages/dev/core/src/Materials/Node/Blocks/Input/inputBlock.ts
  packages/dev/core/src/Materials/materialHelper.ts
  packages/dev/core/src/Maths/math.color.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/postProcesses/defaultRenderingPipelinePropertyGridComponent.tsx
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_materials_transmission.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/MSFT_sRGBFactors.ts
  packages/dev/serializers/src/glTF/2.0/glTFExporter.ts
  packages/dev/serializers/src/glTF/2.0/glTFMaterialExporter.ts
Labels: skip changelog

#13560 Fix Inspector Additional Nodes
  packages/dev/inspector/src/inspector.ts
Labels: bug, inspector

#13559 Physics iteration 10
  packages/dev/core/src/Debug/physicsViewer.ts
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
  packages/dev/core/src/Physics/v2/physicsAggregate.ts
  packages/dev/core/src/Physics/v2/physicsShape.ts
Labels: physics, skip changelog

#13561 Fix Skeleton Bounding Box Timing issue
  packages/dev/core/src/Bones/skeleton.ts
Labels: bug, animations

#13566 Prevent NME Crash with old light block
  packages/tools/nodeEditor/src/graphSystem/properties/lightInformationPropertyTabComponent.tsx
Labels: bug, nme

#13568 Always pass default KTX2 decoder options
  packages/dev/core/src/Misc/khronosTextureContainer2.ts
Labels: bug, texture
