Repository BabylonJS/Babylon.js, pull requests merged in 2024-10, with the labels that each got.

#15656 Remove animation side effects
  packages/dev/core/src/Animations/animatable.core.ts
  packages/dev/core/src/Animations/animatable.ts
  packages/dev/core/src/Animations/animationGroup.ts
  packages/dev/core/src/Animations/runtimeAnimation.ts
  packages/dev/core/src/Behaviors/Cameras/bouncingBehavior.ts
  packages/dev/core/src/Behaviors/Cameras/framingBehavior.ts
  packages/dev/core/src/Bones/skeleton.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphPauseAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphPlayAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphStopAnimationBlock.ts
  packages/dev/core/src/Lights/light.ts
  packages/dev/core/src/Misc/assetsManager.ts
  packages/dev/core/src/assetContainer.ts
  packages/dev/core/src/node.ts
  packages/dev/core/src/scene.ts
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
  packages/tools/nodeGeometryEditor/src/components/preview/previewManager.ts
Labels: build

#15662 WebGPU: Fix buffer memory leak
  packages/dev/core/src/Engines/WebGPU/webgpuBufferManager.ts
  packages/dev/core/src/Engines/WebGPU/webgpuPipelineContext.ts
  packages/dev/core/src/Engines/index.ts
  packages/dev/core/src/Meshes/WebGPU/webgpuDataBuffer.ts
Labels: bug, WebGPU

#15664 Fix unwanted skip
  packages/dev/core/src/Culling/ray.core.ts
  packages/dev/core/src/Inputs/scene.inputManager.ts
  packages/dev/core/src/import.helper.ts
  packages/dev/core/src/scene.ts
Labels: skip changelog

#15670 Global Illumination: Fix WGSL code
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.debugging.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/ShadersWGSL/bilateralBlurQuality.fragment.fx
  packages/dev/core/src/ShadersWGSL/geometry.fragment.fx
  packages/dev/core/src/ShadersWGSL/geometry.vertex.fx
  packages/dev/core/src/ShadersWGSL/rsmFullGlobalIllumination.fragment.fx
Labels: bug, rendering engine

#15673 Supersplat file loading
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: new feature

#15675 Sprite maps: add fog and logarithmic depth support
  packages/dev/core/src/Shaders/spriteMap.fragment.fx
  packages/dev/core/src/Shaders/spriteMap.vertex.fx
  packages/dev/core/src/Sprites/spriteMap.ts
Labels: enhancement, rendering engine

#15679 Allow user to overload picking mechanism
  packages/dev/core/src/Culling/ray.core.ts
Labels: skip changelog

#15680 Fix index remapper
  packages/dev/core/src/Meshes/Node/Blocks/Set/setPositionsBlock.ts
Labels: skip changelog

#15681 Add support for Lattice modifier
  packages/dev/core/src/Meshes/index.ts
  packages/dev/core/src/Meshes/lattice.ts
  packages/tools/tests/test/visualization/ReferenceImages/lattice.png
  packages/tools/tests/test/visualization/config.json
Labels: new feature, geometry

#15676 WebGPU Snapshot rendering: add SnapshotRenderingHelper class
  packages/dev/core/src/Engines/index.ts
  packages/dev/core/src/Misc/index.ts
  packages/dev/core/src/Misc/snapshotRenderingHelper.ts
Labels: new feature, WebGPU

#15558 Mesh HotSpot
  packages/dev/core/src/Meshes/abstractMesh.hotSpot.ts
  packages/dev/core/src/Meshes/index.ts
  packages/tools/viewer-alpha/src/viewer.ts
  packages/tools/viewer-alpha/src/viewerElement.ts
  packages/tools/viewer-alpha/test/apps/web/index.html
Labels: viewer, new feature

#15685 Fix pbr shader
  packages/dev/core/src/ShadersWGSL/pbr.fragment.fx
Labels: skip changelog

#15687 Fix #15686
  packages/dev/core/src/Meshes/Node/Blocks/geometryClampBlock.ts
Labels: new feature

#15690 Add lattice support for NGE
  packages/dev/core/src/Meshes/Node/Blocks/Set/latticeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryInputBlock.ts
  packages/dev/core/src/Meshes/Node/Enums/nodeGeometryContextualSources.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
  packages/dev/core/src/Meshes/lattice.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/display/inputDisplayManager.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/genericNodePropertyComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/inputNodePropertyComponent.tsx
Labels: new feature

#15691 Fix #15689
  packages/tools/nodeGeometryEditor/src/components/preview/previewManager.ts
Labels: new feature

#15694 WebGPU: Remove "unreachable code" warnings
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
Labels: enhancement, WebGPU

#15695 Null engine: no flushFramebuffer
  packages/dev/core/src/Engines/nullEngine.ts
Labels: bug, rendering engine

#15700 Add shader rendering support for Lattice
  packages/dev/core/src/Materials/Textures/rawTexture3D.ts
  packages/dev/core/src/Materials/materialPluginBase.ts
  packages/dev/core/src/Meshes/index.ts
  packages/dev/core/src/Meshes/lattice.material.ts
  packages/dev/core/src/Meshes/lattice.ts
  packages/tools/tests/test/visualization/ReferenceImages/lattice-hal.png
  packages/tools/tests/test/visualization/config.json
Labels: new feature

#15701 WebGPU: Fix crash when using lightmaps
  packages/dev/core/src/ShadersWGSL/default.fragment.fx
Labels: bug, WebGPU

#15707 Usdz exporter
  packages/dev/serializers/src/USDZ/index.ts
  packages/dev/serializers/src/USDZ/usdzExporter.ts
  packages/dev/serializers/src/index.ts
  packages/lts/serializers/src/legacy/legacy-usdzSerializer.ts
  packages/lts/serializers/src/legacy/legacy.ts
  packages/public/umd/babylonjs-serializers/src/USDZ.ts
  packages/public/umd/babylonjs-serializers/webpack.config.js
  packages/tools/babylonServer/src/serializers/legacy-dev.ts
  packages/tools/babylonServer/src/serializers/legacy-lts.ts
Labels: new feature

#15708 Export camera to usdz
  packages/dev/serializers/src/USDZ/usdzExporter.ts
Labels: new feature

#15710 Materials: Add plug-ins even if the material has already been used for rendering
  packages/dev/core/src/Materials/Background/backgroundMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/Materials/materialPluginManager.ts
  packages/dev/core/src/Materials/pushMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
Labels: enhancement, materials

#15709 Improve handling of texture names in glTF loader
  packages/dev/core/src/Materials/Textures/texture.ts
  packages/dev/core/src/Materials/Textures/textureSampler.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/dev/loaders/src/glTF/glTFFileLoader.ts
Labels: new feature

#15715 Set missing morph target id for serialization
  packages/dev/core/src/Morph/morphTarget.ts
Labels: bug

#15714 Fix crash
  packages/dev/sharedUiComponents/src/lines/vector2LineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/vector3LineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/vector4LineComponent.tsx
Labels: bug

#15722 WebGPU: Fix collisions in bind group cache
  packages/dev/core/src/Engines/WebGPU/webgpuCacheBindGroups.ts
  packages/dev/core/src/Engines/WebGPU/webgpuCacheSampler.ts
Labels: bug, WebGPU

#15713 CSG2: Using Manifold for boolean operations
  packages/dev/core/src/Meshes/Node/Blocks/booleanGeometryBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometry.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
  packages/dev/core/src/Meshes/csg.ts
  packages/dev/core/src/Meshes/csg2.ts
  packages/dev/core/src/Meshes/index.ts
  packages/dev/core/src/Meshes/mesh.vertexData.ts
  packages/dev/core/src/Misc/tools.internals.ts
  packages/dev/core/src/Misc/tools.ts
  packages/tools/tests/test/visualization/ReferenceImages/csg.png
  packages/tools/tests/test/visualization/ReferenceImages/csgVertColor.png
  packages/tools/tests/test/visualization/config.json
Labels: new feature

#15677 NME for Gaussian Splatting
  packages/dev/core/src/Materials/GaussianSplatting/gaussianSplattingMaterial.ts
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/gaussianBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/gaussianSplattingBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/index.ts
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/splatReaderBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Input/inputBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/index.ts
  packages/dev/core/src/Materials/Node/Enums/nodeMaterialModes.ts
  packages/dev/core/src/Materials/Node/index.ts
  packages/dev/core/src/Materials/Node/nodeMaterialDefault.ts
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/core/src/Shaders/ShadersInclude/gaussianSplatting.fx
  packages/dev/core/src/Shaders/ShadersInclude/gaussianSplattingFragmentDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/gaussianSplattingUboDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/gaussianSplattingVertexDeclaration.fx
  packages/dev/core/src/Shaders/gaussianSplatting.fragment.fx
  packages/dev/core/src/Shaders/gaussianSplatting.vertex.fx
  packages/tools/nodeEditor/public/index.js
  packages/tools/nodeEditor/src/blockTools.ts
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
  packages/tools/nodeEditor/src/components/preview/previewMeshControlComponent.tsx
  packages/tools/nodeEditor/src/components/preview/previewType.ts
  packages/tools/nodeEditor/src/components/propertyTab/propertyTabComponent.tsx
  packages/tools/tests/test/visualization/ReferenceImages/gsplat-nme.png
  packages/tools/tests/test/visualization/config.json
Labels: new feature, nme

#15726 Fix #15725
  packages/dev/core/src/Meshes/Node/Blocks/Set/aggregatorBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: new feature, nge

#15724 Fix issue when creating instances from a gltf object
  packages/dev/core/src/Meshes/mesh.ts
  packages/tools/tests/test/visualization/config.json
Labels: bug, breaking change

#15720 Reduce splat VRAM size
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/splatReaderBlock.ts
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/core/src/Shaders/ShadersInclude/gaussianSplatting.fx
  packages/dev/core/src/Shaders/gaussianSplatting.vertex.fx
Labels: enhancement

#15727 Update gltf_validator.js to 2.0.0-dev.3.10
  packages/tools/babylonServer/public/gltf_validator.js
Labels: new feature

#15728 Inspector: Fix crash when viewing texture in inspector with WebGL1
  packages/dev/core/src/Shaders/lod.fragment.fx
Labels: bug, inspector

#15731 Allow user to specify material for csg2
  packages/dev/core/src/Meshes/csg2.ts
Labels: skip changelog

#15729 Update GS parsing for back compatibility loading
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: skip changelog

#15736 Add warning when detecting negative genus
  packages/dev/core/src/Meshes/csg2.ts
Labels: skip changelog

#15738 SnapshotRenderingHelper: Add new helper method
  packages/dev/core/src/Misc/snapshotRenderingHelper.ts
Labels: enhancement, WebGPU

#15739 Allow users to extend the dirty system
  packages/dev/core/src/Meshes/abstractMesh.ts
  packages/dev/core/src/Meshes/transformNode.ts
Labels: skip changelog

#15745 Fix missing matrix
  packages/dev/core/src/Shaders/ShadersInclude/backgroundVertexDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/defaultVertexDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrVertexDeclaration.fx
Labels: skip changelog

#15743 SnapshotRenderingHelper: Fix interaction with performance priority mode
  packages/dev/core/src/Misc/snapshotRenderingHelper.ts
Labels: bug, WebGPU

#15744 WebGPU: Sync with specification
  packages/dev/core/src/Engines/WebGPU/webgpuCacheRenderPipeline.ts
  packages/dev/core/src/Engines/WebGPU/webgpuConstants.ts
  packages/dev/core/src/Engines/constants.ts
  packages/dev/core/src/LibDeclarations/webgpu.d.ts
Labels: enhancement, WebGPU

#15747 solidify nge
  packages/dev/core/src/Meshes/Node/Blocks/geometryTransformBlock.ts
Labels: skip changelog

#15742 Standard material: use the specular color of the material for reflectivity when there's no light
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/Shaders/ShadersInclude/defaultFragmentDeclaration.fx
  packages/dev/core/src/Shaders/default.fragment.fx
  packages/dev/core/src/ShadersWGSL/default.fragment.fx
Labels: bug, rendering engine

#15734 Async loading and parsing of GS
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: enhancement

#15751 fix several bugs
  .build/config.json
  package-lock.json
  packages/dev/core/src/Maths/math.functions.ts
  packages/dev/core/src/Meshes/Node/Blocks/cleanGeometryBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/dev/core/src/Meshes/Node/nodeGeometry.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
  packages/tools/nodeGeometryEditor/package.json
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/components/preview/previewAreaComponent.tsx
  packages/tools/nodeGeometryEditor/src/components/preview/previewManager.ts
  packages/tools/nodeGeometryEditor/src/components/preview/previewMode.ts
  packages/tools/nodeGeometryEditor/src/components/preview/svgs/doubleSided.svg
  packages/tools/nodeGeometryEditor/src/main.scss
  packages/tools/nodeGeometryEditor/tsconfig.build.json
  packages/tools/nodeGeometryEditor/webpack.config.js
Labels: skip changelog

#15758 BBox gizmo axis info observable
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
Labels: enhancement, gizmos
