Repository BabylonJS/Babylon.js, pull requests merged in 2024-07, with the labels that each got.

#15248 ArcRotate progressive restore state
  packages/dev/core/src/Cameras/arcRotateCamera.ts
  packages/dev/core/src/Maths/math.vector.ts
  packages/tools/viewer-alpha/src/viewer.ts
Labels: enhancement

#15250 Fix missing test with ArcRotateCamera
  packages/dev/core/src/Cameras/arcRotateCamera.ts
  packages/dev/core/src/Cameras/camera.ts
Labels: skip changelog

#15251 Fix cube texture defaultLodScale
  packages/dev/core/src/Materials/Textures/cubeTexture.ts
Labels: bug

#15249 allow url query parameters on svg paths
  packages/dev/gui/src/2D/controls/image.ts
Labels: new feature

#15254 Use Quaternion and slerp for alpha/beta/gamma arcrotate interpolation
  packages/dev/core/src/Cameras/arcRotateCamera.ts
  packages/dev/core/src/Maths/math.vector.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
Labels: skip changelog

#15257 Fix a typo with new bounding box code
  packages/dev/core/src/Meshes/abstractMesh.ts
  packages/dev/core/src/Meshes/instancedMesh.ts
Labels: bug, skip changelog

#15247 buffer: copy unaligned data in GetFloatData
  packages/dev/core/src/Buffers/buffer.ts
  packages/dev/core/src/Buffers/bufferUtils.ts
Labels: bug

#15255 Remove check for pointer out
  packages/dev/gui/src/2D/controls/control.ts
Labels: bug

#15272 Fix gpu part aging issue
  packages/dev/core/src/Shaders/gpuRenderParticles.vertex.fx
Labels: bug

#15277 Fix #15263
  packages/dev/core/src/Collisions/gpuPicker.ts
Labels: skip changelog

#15281 Fix #15279
  packages/dev/core/src/Materials/Node/Blocks/Teleport/teleportInBlock.ts
Labels: bug

#15286 Fix edges render with instances in MRT
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
Labels: bug

#15287 Fix elbow overload being ignored when using modules
  packages/tools/nodeEditor/src/graphSystem/display/elbowDisplayManager.modules.scss
Labels: bug, skip changelog

#15288 add support for log depth
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/fragmentOutputBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Vertex/vertexOutputBlock.ts
Labels: skip changelog

#15291 Add consistent support for toolkit
  packages/tools/playground/src/tools/saveManager.ts
Labels: skip changelog

#15293 fix translucency intensity texture
  packages/dev/core/src/Materials/PBR/pbrSubSurfaceConfiguration.ts
Labels: bug, glTF

#15294 Fix effect dispose memory leak
  packages/dev/core/src/Engines/thinEngine.ts
Labels: bug

#15289 add support for ShadowMapBlock
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/shadowMapBlock.ts
  packages/dev/core/src/ShadersWGSL/ShadersInclude/packingFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/shadowMapFragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/shadowMapVertexMetric.fx
Labels: skip changelog

#15299 Fix raw texture clone by leveraging a shared internal texture
  packages/dev/core/src/Materials/Textures/rawTexture.ts
Labels: bug, texture

#15300 [Native] Warning for non supported fill modes
  packages/dev/core/src/Engines/nativeEngine.ts
Labels: native

#15303 Fix race condition
  packages/tools/playground/src/components/rendererComponent.tsx
Labels: skip changelog

#15308 Fix blinking caret
  packages/dev/gui/src/2D/controls/inputTextArea.ts
Labels: skip changelog

#15310 Fix text highlight breaking cursor movements
  packages/dev/gui/src/2D/controls/inputTextArea.ts
Labels: skip changelog

#15309 Fix copy paste caret positioning
  packages/dev/gui/src/2D/controls/inputTextArea.ts
Labels: skip changelog

#15316 Fix #15315
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/genericNodePropertyComponent.tsx
Labels: new feature

#15318 Fix resuming animation after pause
  packages/dev/core/src/Animations/animationGroup.ts
Labels: bug, animations

#15317 Add minified and non-minified esm bundles to viewer alpha package
  package-lock.json
  packages/public/@babylonjs/viewer-alpha/package.json
  packages/public/@babylonjs/viewer-alpha/rollup.config.dist.esm.mjs
  packages/public/@babylonjs/viewer-alpha/rollup.config.lib.mjs
  packages/public/@babylonjs/viewer-alpha/tsconfig.build.dist.json
  packages/public/@babylonjs/viewer-alpha/tsconfig.build.lib.json
Labels: new feature

#15314 filling the gaps
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/reflectionTextureBaseBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/anisotropyBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/clearCoatBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/reflectionBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/refractionBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/sheenBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/subSurfaceBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildState.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockAlphaFresnel.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockAnisotropic.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockReflection.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockSheen.fx
  packages/dev/core/src/Shaders/pbr.fragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/bumpFragmentMainFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/decalFragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/harmonicsFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/hdrFilteringFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/helperFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/imageProcessingFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBRDFFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockAlbedoOpacity.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockAlphaFresnel.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockAnisotropic.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockClearcoat.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockFinalLitComponents.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockReflection.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockSheen.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockSubSurface.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrDirectLightingFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrHelperFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrIBLFunctions.fx
  packages/tools/tests/test/visualization/ReferenceImages/node-material-pbr-2.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15323 Fix decal
  packages/dev/core/src/Meshes/Builders/decalBuilder.ts
Labels: bug

#15325 Fix issue where the attribute names where polluted on rebuild with a …
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/Node/Blocks/Input/inputBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/refractionBlock.ts
Labels: skip changelog

#15329 Fix Texture Decals shader recompilation
  packages/dev/core/src/Meshes/meshUVSpaceRenderer.ts
Labels: bug

#15339 Fix animationGrup.reset endless loop
  packages/dev/core/src/Animations/animatable.ts
  packages/dev/core/src/Animations/animationGroup.ts
Labels: bug

#15342 Support getAlphaFromRGB in transparent shadow maps
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Shaders/ShadersInclude/shadowMapFragmentExtraDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/shadowMapFragmentSoftTransparentShadow.fx
  packages/dev/core/src/Shaders/shadowMap.fragment.fx
Labels: enhancement, shadows
