Repository BabylonJS/Babylon.js, pull requests merged in 2024-12, with the labels that each got.

#15918 WebGPU: Fix crash when generating shadows for a point light
  packages/dev/core/src/ShadersWGSL/ShadersInclude/lightFragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/shadowsFragmentFunctions.fx
Labels: bug, WebGPU, shadows

#15849 SPZ splat file loader
  packages/dev/core/src/Materials/GaussianSplatting/gaussianSplattingMaterial.ts
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/core/src/Shaders/ShadersInclude/gaussianSplatting.fx
  packages/dev/core/src/Shaders/ShadersInclude/gaussianSplattingVertexDeclaration.fx
  packages/dev/core/src/Shaders/gaussianSplatting.vertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/gaussianSplatting.fx
  packages/dev/core/src/ShadersWGSL/gaussianSplatting.vertex.fx
  packages/dev/loaders/src/SPLAT/splatFileLoader.metadata.ts
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: enhancement, loaders

#15926 Edge Renderer: Fix edges not displayed the second time we enable the edge renderer for a mesh
  packages/dev/core/src/Rendering/edgesRenderer.ts
Labels: bug, rendering engine

#15948 Reintroduce shadowdom support
  packages/dev/inspector/src/inspector.ts
  packages/dev/sharedUiComponents/src/styleHelper.ts
Labels: skip changelog

#15950 Do not pick during a multi-touch gesture
  packages/dev/core/src/Inputs/scene.inputManager.ts
Labels: bug

#15954 Fix sandbox regressions
  packages/tools/sandbox/src/sandbox.tsx
Labels: skip changelog

#15955 WebGPU: fix crash when enabling fog
  packages/dev/core/src/ShadersWGSL/ShadersInclude/fogVertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/sceneUboDeclaration.fx
Labels: bug, WebGPU

#15952 IES shader
  packages/dev/core/src/Lights/spotLight.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/lightBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/Materials/Textures/Loaders/exrTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/hdrTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/iesTextureLoader.ts
  packages/dev/core/src/Materials/materialHelper.functions.ts
  packages/dev/core/src/Shaders/ShadersInclude/lightFragment.fx
  packages/dev/core/src/Shaders/ShadersInclude/lightFragmentDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/lightUboDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/lightsFragmentFunctions.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrDirectLightingFalloffFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/lightFragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/lightUboDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/lightsFragmentFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrDirectLightingFalloffFunctions.fx
  packages/tools/tests/test/visualization/ReferenceImages/iesprofile.png
  packages/tools/tests/test/visualization/ReferenceImages/iesprofile2.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15959 Add IES to inspector
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGridTabComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/lights/spotLightPropertyGridComponent.tsx
Labels: skip changelog

#15964 Fix an issue with effect reference counting
  .build/config.json
  packages/dev/core/src/Materials/material.ts
Labels: bug

#15965 Fix camera serialization
  packages/dev/core/src/Cameras/targetCamera.ts
Labels: bug

#15968 Keep splats datas in ram
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
Labels: enhancement

#15967 Material: Fix disposing resources when disposing of a material
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/Meshes/abstractMesh.ts
  packages/dev/core/src/Rendering/objectRenderer.ts
Labels: bug, materials

#15970 Add support for glTF extension EXT_lights_ies
  packages/dev/inspector/src/components/globalState.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/EXT_lights_ies.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_animation_pointer.data.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/dynamic.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/index.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoaderInterfaces.ts
  packages/public/glTF2Interface/babylon.glTF2Interface.d.ts
  packages/tools/tests/test/visualization/ReferenceImages/ext-lights-ies.png
  packages/tools/tests/test/visualization/config.json
Labels: new feature

#15962 FrameGraph: add support for shadow generators (CSM included)
  packages/dev/core/src/Debug/directionalLightFrustumViewer.ts
  packages/dev/core/src/Engines/Extensions/engine.multiRender.ts
  packages/dev/core/src/Engines/constants.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/blackAndWhitePostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/bloomPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/blurPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/circleOfConfusionPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/depthOfFieldPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/extractHighlightsPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/baseObjectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/baseShadowGeneratorBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/csmShadowGeneratorBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/cullObjectsBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/geometryRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/objectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/shadowGeneratorBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/clearBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/copyTextureBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/generateMipmapsBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/index.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/inputBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/resourceContainerBlock.ts
  packages/dev/core/src/FrameGraph/Node/Types/nodeRenderGraphTypes.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraph.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraphBlock.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraphBlockConnectionPoint.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/csmShadowGeneratorTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/objectRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/shadowGeneratorTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Texture/clearTextureTask.ts
  packages/dev/core/src/FrameGraph/frameGraph.ts
  packages/dev/core/src/FrameGraph/frameGraphTextureManager.ts
  packages/dev/core/src/FrameGraph/index.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Lights/directionalLight.ts
  packages/dev/core/src/Lights/shadowLight.ts
  packages/dev/core/src/Lights/spotLight.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/Misc/copyTextureToTexture.ts
  packages/dev/core/src/Misc/filesInput.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/PostProcesses/postProcessManager.ts
  packages/dev/core/src/scene.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/lights/commonShadowLightPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/lights/directionalLightPropertyGridComponent.tsx
  packages/tools/nodeRenderGraphEditor/public/index.js
  packages/tools/nodeRenderGraphEditor/src/blockTools.ts
  packages/tools/nodeRenderGraphEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/components/preview/previewManager.ts
  packages/tools/nodeRenderGraphEditor/src/graphEditor.tsx
  packages/tools/nodeRenderGraphEditor/src/graphSystem/registerNodePortDesign.ts
Labels: new feature, frame graph

#15974 Fix broken nightly Native
  packages/dev/core/src/Shaders/ShadersInclude/lightsFragmentFunctions.fx
Labels: skip changelog

#15972 Final touches on glTF serializer rework
  packages/dev/serializers/src/glTF/2.0/glTFMaterialExporter.ts
  packages/dev/serializers/src/glTF/2.0/index.ts
  packages/dev/serializers/test/integration/glTFSerializer.test.ts
Labels: skip changelog

#15975 FrameGraph: add "execute" task and block
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/blackAndWhitePostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/bloomPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/blurPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/circleOfConfusionPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/depthOfFieldPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/extractHighlightsPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/baseObjectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/csmShadowGeneratorBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/cullObjectsBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/geometryRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/shadowGeneratorBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/clearBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/copyTextureBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/generateMipmapsBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/executeBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/index.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/resourceContainerBlock.ts
  packages/dev/core/src/FrameGraph/Node/Types/nodeRenderGraphTypes.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraphBlock.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraphBlockConnectionPoint.ts
  packages/dev/core/src/FrameGraph/Passes/cullPass.ts
  packages/dev/core/src/FrameGraph/Tasks/Misc/executeTask.ts
  packages/dev/core/src/FrameGraph/frameGraph.ts
  packages/dev/core/src/FrameGraph/index.ts
  packages/dev/gui/src/2D/FrameGraph/renderGraphGUIBlock.ts
  packages/tools/nodeRenderGraphEditor/src/blockTools.ts
  packages/tools/nodeRenderGraphEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/components/preview/previewManager.ts
  packages/tools/nodeRenderGraphEditor/src/graphEditor.tsx
Labels: enhancement, frame graph

#15976 Adding missing part for gltf EXT_lights_ies
  packages/dev/loaders/src/glTF/2.0/Extensions/EXT_lights_ies.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_animation_pointer.data.ts
  packages/public/glTF2Interface/babylon.glTF2Interface.d.ts
Labels: skip changelog

#15979 WebGL shaders: Add new EXTENSION injection points
  packages/dev/core/src/Shaders/default.fragment.fx
  packages/dev/core/src/Shaders/default.vertex.fx
  packages/dev/core/src/Shaders/pbr.fragment.fx
  packages/dev/core/src/Shaders/pbr.vertex.fx
Labels: enhancement, rendering engine

#15984 SPZ rendering quality improvement
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: skip changelog

#15987 Fix webgpu test flakyness
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15991 Fix camera getFrontPosition
  packages/dev/core/src/Cameras/targetCamera.ts
Labels: bug

#15993 Fix XR's near interaction's selection mesh positioning
  packages/dev/core/src/XR/features/WebXRNearInteraction.ts
Labels: bug

#15995 Upload Draco encoder modules to CDN
  packages/tools/babylonServer/public/draco_encoder.js
  packages/tools/babylonServer/public/draco_encoder.wasm
  packages/tools/babylonServer/public/draco_encoder_wasm_wrapper.js
Labels: skip changelog

#15996 Update doc for CreateScreenshotWithResizeAsync
  packages/dev/core/src/Misc/screenshotTools.ts
Labels: skip changelog

#15997 Mesh: loss of thin instances during mesh cloning
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug, rendering engine

#15999 WebGPU: Fix crash when using LDR merge in glow layer
  packages/dev/core/src/ShadersWGSL/glowMapMerge.fragment.fx
Labels: bug, WebGPU

#16015 Adjust KHR_texture_transform offset for non-zero rotation center
  packages/dev/serializers/src/glTF/2.0/Extensions/KHR_texture_transform.ts
Labels: skip changelog

#16016 Mesh: Fix wireframe for unindexed meshes
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/core/src/Meshes/subMesh.ts
Labels: bug, rendering engine

#16014 Morph target manager: Refactor of code + ability to disable position morphing
  packages/dev/core/src/Culling/Helper/computeShaderBoundingHelper.ts
  packages/dev/core/src/Culling/Helper/transformFeedbackBoundingHelper.ts
  packages/dev/core/src/Layers/effectLayer.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Materials/Node/Blocks/Vertex/morphTargetsBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/materialHelper.functions.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/Morph/morphTarget.ts
  packages/dev/core/src/Morph/morphTargetManager.ts
  packages/dev/core/src/PostProcesses/volumetricLightScatteringPostProcess.ts
  packages/dev/core/src/Rendering/depthRenderer.ts
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/core/src/Rendering/outlineRenderer.ts
  packages/dev/core/src/Shaders/ShadersInclude/morphTargetsVertex.fx
  packages/dev/core/src/Shaders/ShadersInclude/morphTargetsVertexDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/morphTargetsVertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/morphTargetsVertexDeclaration.fx
Labels: enhancement, rendering engine, breaking change

#16018 Import pass shader in glTF serializer
  packages/dev/serializers/src/glTF/2.0/glTFMaterialExporter.ts
Labels: skip changelog

#16019 Limit cases where KHR_texture_transform offset is adjusted for non-origin rotation
  packages/dev/serializers/src/glTF/2.0/Extensions/KHR_texture_transform.ts
Labels: skip changelog

#16021 Fix volume refresh for GS
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
Labels: bug

#16026 FrameGraph: add glow layer block and task
  packages/dev/core/src/FrameGraph/Node/Blocks/Layers/glowLayerBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/baseObjectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/index.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraphBlock.ts
  packages/dev/core/src/FrameGraph/Passes/renderPass.ts
  packages/dev/core/src/FrameGraph/Tasks/Layers/glowLayerTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/bloomMergeTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/bloomTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/circleOfConfusionTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldBlurTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldMergeTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/postProcessTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/objectRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/shadowGeneratorTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/taaObjectRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Texture/copyToTextureTask.ts
  packages/dev/core/src/FrameGraph/frameGraph.ts
  packages/dev/core/src/FrameGraph/frameGraphRenderContext.ts
  packages/dev/core/src/FrameGraph/frameGraphTask.ts
  packages/dev/core/src/FrameGraph/frameGraphTextureManager.ts
  packages/dev/core/src/FrameGraph/index.ts
  packages/dev/core/src/Layers/effectLayer.ts
  packages/dev/core/src/Layers/glowLayer.ts
  packages/dev/core/src/Layers/highlightLayer.ts
  packages/dev/core/src/Layers/index.ts
  packages/dev/core/src/Layers/thinEffectLayer.ts
  packages/dev/core/src/Layers/thinGlowLayer.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/tools/nodeRenderGraphEditor/src/blockTools.ts
  packages/tools/nodeRenderGraphEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/tests/test/visualization/config.json
Labels: enhancement, frame graph
