Repository BabylonJS/Babylon.js, pull requests merged in 2024-08, with the labels that each got.

#15357 Fix crash when multi call to build for nme
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/tools/tests/test/visualization/ReferenceImages/nme-multi-build.png
  packages/tools/tests/test/visualization/config.json
Labels: bug

#15358 Port WebGPUTextureManager to WGSL
  packages/dev/core/src/Buffers/buffer.nonFloatVertexBuffers.ts
  packages/dev/core/src/Engines/Processors/shaderProcessor.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessingContext.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureManager.ts
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/thinEngine.functions.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/effect.functions.ts
  packages/dev/core/src/Materials/effect.ts
  packages/tools/testTools/src/visualizationUtils.ts
Labels: skip changelog

#15366 Fix procedural refresh issue
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
Labels: bug

#15365 Shadow maps webgpu
  packages/dev/core/src/Lights/Shadows/index.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/Misc/index.ts
  packages/dev/core/src/Misc/rgbdTextureTools.ts
  packages/dev/core/src/PostProcesses/blurPostProcess.ts
  packages/dev/core/src/PostProcesses/index.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/ShadersWGSL/ShadersInclude/bayerDitherFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/kernelBlurFragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/kernelBlurFragment2.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/kernelBlurVaryingDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/kernelBlurVertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/shadowMapFragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/shadowMapFragmentExtraDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/shadowMapFragmentSoftTransparentShadow.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/shadowMapVertexExtraDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/shadowMapVertexMetric.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/shadowMapVertexNormalBias.fx
  packages/dev/core/src/ShadersWGSL/depthBoxBlur.fragment.fx
  packages/dev/core/src/ShadersWGSL/kernelBlur.fragment.fx
  packages/dev/core/src/ShadersWGSL/kernelBlur.vertex.fx
  packages/dev/core/src/ShadersWGSL/rgbdDecode.fragment.fx
  packages/dev/core/src/ShadersWGSL/rgbdEncode.fragment.fx
  packages/dev/core/src/ShadersWGSL/shadowMap.fragment.fx
  packages/dev/core/src/ShadersWGSL/shadowMap.vertex.fx
Labels: new feature

#15371 Add support for inline comments in OBJ loaded
  packages/dev/loaders/src/OBJ/objFileLoader.ts
Labels: new feature

#15344 SceneLoader Options
  packages/dev/core/src/Loading/sceneLoader.ts
  packages/dev/loaders/src/OBJ/objFileLoader.ts
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
  packages/dev/loaders/src/STL/stlFileLoader.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/MSFT_lod.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/dev/loaders/src/glTF/glTFFileLoader.ts
  packages/tools/viewer-alpha/src/viewer.ts
Labels: new feature

#15378 Use correct glslang capitalization
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/tools/testTools/src/visualizationUtils.ts
Labels: skip changelog

#15379 Fix flacky test
  packages/dev/core/src/Misc/rgbdTextureTools.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrDebug.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrDebug.fx
  packages/tools/tests/test/visualization/ReferenceImages/PBR-Debug-Modes.png
Labels: skip changelog

#15390 Allow users to popup the inspector windows
  packages/dev/core/src/Debug/debugLayer.ts
  packages/dev/inspector/src/inspector.ts
Labels: new feature

#15393 Fix isSupported
  packages/dev/core/src/PostProcesses/postProcess.ts
Labels: skip changelog

#15394 Fix NME displaying wrong execution time
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/tools/nodeEditor/src/graphSystem/blockNodeData.ts
Labels: skip changelog

#15395 Layer to webgpu
  packages/dev/core/src/Layers/layer.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Meshes/index.ts
  packages/dev/core/src/Meshes/linesMesh.ts
  packages/dev/core/src/Misc/environmentTextureTools.ts
  packages/dev/core/src/Misc/rgbdTextureTools.ts
  packages/dev/core/src/PostProcesses/index.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/PostProcesses/vrDistortionCorrectionPostProcess.ts
  packages/dev/core/src/ShadersWGSL/color.fragment.fx
  packages/dev/core/src/ShadersWGSL/color.vertex.fx
  packages/dev/core/src/ShadersWGSL/depthBoxBlur.fragment.fx
  packages/dev/core/src/ShadersWGSL/layer.fragment.fx
  packages/dev/core/src/ShadersWGSL/layer.vertex.fx
  packages/dev/core/src/ShadersWGSL/vrDistortionCorrection.fragment.fx
  packages/dev/loaders/test/integration/babylon.sceneLoader.test.ts
  packages/tools/tests/test/visualization/config.json
Labels: new feature, WebGPU

#15398 DefaultRenderingPipeline to webgpu
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Layers/highlightLayer.ts
  packages/dev/core/src/Misc/rgbdTextureTools.ts
  packages/dev/core/src/Misc/textureTools.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/index.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssao2RenderingPipeline.ts
  packages/dev/core/src/PostProcesses/anaglyphPostProcess.ts
  packages/dev/core/src/PostProcesses/blackAndWhitePostProcess.ts
  packages/dev/core/src/PostProcesses/bloomMergePostProcess.ts
  packages/dev/core/src/PostProcesses/blurPostProcess.ts
  packages/dev/core/src/PostProcesses/chromaticAberrationPostProcess.ts
  packages/dev/core/src/PostProcesses/circleOfConfusionPostProcess.ts
  packages/dev/core/src/PostProcesses/depthOfFieldMergePostProcess.ts
  packages/dev/core/src/PostProcesses/extractHighlightsPostProcess.ts
  packages/dev/core/src/PostProcesses/fxaaPostProcess.ts
  packages/dev/core/src/PostProcesses/grainPostProcess.ts
  packages/dev/core/src/PostProcesses/imageProcessingPostProcess.ts
  packages/dev/core/src/PostProcesses/index.ts
  packages/dev/core/src/PostProcesses/passPostProcess.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/PostProcesses/sharpenPostProcess.ts
  packages/dev/core/src/PostProcesses/vrDistortionCorrectionPostProcess.ts
  packages/dev/core/src/Rendering/depthRenderer.ts
  packages/dev/core/src/Rendering/index.ts
  packages/dev/core/src/Shaders/chromaticAberration.fragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pointCloudVertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pointCloudVertexDeclaration.fx
  packages/dev/core/src/ShadersWGSL/anaglyph.fragment.fx
  packages/dev/core/src/ShadersWGSL/blackAndWhite.fragment.fx
  packages/dev/core/src/ShadersWGSL/bloomMerge.fragment.fx
  packages/dev/core/src/ShadersWGSL/chromaticAberration.fragment.fx
  packages/dev/core/src/ShadersWGSL/circleOfConfusion.fragment.fx
  packages/dev/core/src/ShadersWGSL/depth.fragment.fx
  packages/dev/core/src/ShadersWGSL/depth.vertex.fx
  packages/dev/core/src/ShadersWGSL/depthOfFieldMerge.fragment.fx
  packages/dev/core/src/ShadersWGSL/extractHighlights.fragment.fx
  packages/dev/core/src/ShadersWGSL/fxaa.fragment.fx
  packages/dev/core/src/ShadersWGSL/fxaa.vertex.fx
  packages/dev/core/src/ShadersWGSL/grain.fragment.fx
  packages/dev/core/src/ShadersWGSL/imageProcessing.fragment.fx
  packages/dev/core/src/ShadersWGSL/sharpen.fragment.fx
  packages/dev/core/src/ShadersWGSL/ssao2.fragment.fx
  packages/dev/core/src/ShadersWGSL/ssaoCombine.fragment.fx
  packages/tools/tests/test/visualization/ReferenceImages/fluidParticleSystem.png
  packages/tools/tests/test/visualization/config.json
Labels: new feature, WebGPU, breaking change

#15400 Color correction to webgpu
  packages/dev/core/src/PostProcesses/colorCorrectionPostProcess.ts
  packages/dev/core/src/PostProcesses/index.ts
  packages/dev/core/src/ShadersWGSL/colorCorrection.fragment.fx
  packages/tools/tests/test/visualization/ReferenceImages/color-correction.png
  packages/tools/tests/test/visualization/config.json
Labels: new feature, WebGPU

#15401 Convolution PP to webgpu
  packages/dev/core/src/PostProcesses/convolutionPostProcess.ts
  packages/dev/core/src/PostProcesses/index.ts
  packages/dev/core/src/ShadersWGSL/convolution.fragment.fx
  packages/tools/tests/test/visualization/ReferenceImages/convolution.png
  packages/tools/tests/test/visualization/config.json
Labels: new feature, WebGPU

#15406 Bugfix for part matching in xmlLoader
  packages/dev/gui/src/2D/xmlLoader.ts
Labels: bug

#15409 Material plugins to Webgpu (+meshUVSpaceRenderer)
  packages/dev/core/src/Materials/PBR/pbrAnisotropicConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrBRDFConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrClearCoatConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrIridescenceConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrSheenConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrSubSurfaceConfiguration.ts
  packages/dev/core/src/Materials/material.decalMapConfiguration.ts
  packages/dev/core/src/Materials/material.detailMapConfiguration.ts
  packages/dev/core/src/Materials/materialPluginBase.ts
  packages/dev/core/src/Materials/materialPluginManager.ts
  packages/dev/core/src/Materials/meshDebugPluginMaterial.ts
  packages/dev/core/src/Meshes/index.ts
  packages/dev/core/src/Meshes/meshUVSpaceRenderer.ts
  packages/dev/core/src/ShadersWGSL/meshUVSpaceRenderer.fragment.fx
  packages/dev/core/src/ShadersWGSL/meshUVSpaceRenderer.vertex.fx
  packages/dev/core/src/ShadersWGSL/meshUVSpaceRendererFinaliser.fragment.fx
  packages/dev/core/src/ShadersWGSL/meshUVSpaceRendererFinaliser.vertex.fx
  packages/dev/core/src/ShadersWGSL/meshUVSpaceRendererMasker.fragment.fx
  packages/dev/core/src/ShadersWGSL/meshUVSpaceRendererMasker.vertex.fx
Labels: new feature, WebGPU

#15410 Add missing test for meshUVSpaceRenderer
  packages/dev/core/src/Materials/PBR/pbrAnisotropicConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrBRDFConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrClearCoatConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrIridescenceConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrSheenConfiguration.ts
  packages/dev/core/src/Materials/PBR/pbrSubSurfaceConfiguration.ts
  packages/dev/core/src/Materials/material.decalMapConfiguration.ts
  packages/dev/core/src/Materials/material.detailMapConfiguration.ts
  packages/dev/core/src/Materials/materialPluginBase.ts
  packages/dev/core/src/Materials/meshDebugPluginMaterial.ts
  packages/dev/core/src/Meshes/meshUVSpaceRenderer.ts
  packages/dev/core/src/ShadersWGSL/meshUVSpaceRendererFinaliser.fragment.fx
  packages/dev/core/src/ShadersWGSL/meshUVSpaceRendererFinaliser.vertex.fx
  packages/dev/core/src/ShadersWGSL/meshUVSpaceRendererMasker.vertex.fx
  packages/tools/tests/test/visualization/ReferenceImages/decal-map-pp.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15414 Fix weird bug
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/perturbNormalBlock.ts
  packages/tools/nodeEditor/src/sharedComponents/textureLineComponent.tsx
Labels: skip changelog

#15411 Global Illumination to WebGPU
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Rendering/GlobalIllumination/giRSMManager.ts
  packages/dev/core/src/Rendering/GlobalIllumination/index.ts
  packages/dev/core/src/Rendering/reflectiveShadowMap.ts
  packages/dev/core/src/ShadersWGSL/bilateralBlur.fragment.fx
  packages/dev/core/src/ShadersWGSL/bilateralBlurQuality.fragment.fx
  packages/dev/core/src/ShadersWGSL/rsmFullGlobalIllumination.fragment.fx
  packages/dev/core/src/ShadersWGSL/rsmGlobalIllumination.fragment.fx
Labels: new feature, WebGPU

#15412 MotionBlur and geometry buffer renderer to webgpu
  packages/dev/core/src/PostProcesses/index.ts
  packages/dev/core/src/PostProcesses/motionBlurPostProcess.ts
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/core/src/Rendering/index.ts
  packages/dev/core/src/Shaders/geometry.fragment.fx
  packages/dev/core/src/ShadersWGSL/geometry.fragment.fx
  packages/dev/core/src/ShadersWGSL/geometry.vertex.fx
  packages/dev/core/src/ShadersWGSL/motionBlur.fragment.fx
Labels: new feature, WebGPU

#15418 Sprites to webgpu
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssao2RenderingPipeline.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/ShadersWGSL/ShadersInclude/imageProcessingCompatibility.fx
  packages/dev/core/src/ShadersWGSL/sprites.fragment.fx
  packages/dev/core/src/ShadersWGSL/sprites.vertex.fx
  packages/dev/core/src/ShadersWGSL/ssao2.fragment.fx
  packages/dev/core/src/Sprites/index.ts
  packages/dev/core/src/Sprites/spriteRenderer.ts
Labels: new feature, WebGPU

#15421 Fix detailmap, depthprepass, morphtarget, decal, refreaction on webgpu
  packages/dev/core/src/ShadersWGSL/ShadersInclude/bumpFragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/depthPrePass.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/morphTargetsVertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/oitFragment.fx
  packages/dev/core/src/ShadersWGSL/default.fragment.fx
Labels: skip changelog

#15422 Particle systems to WebGPU
  packages/dev/core/src/Particles/index.ts
  packages/dev/core/src/Particles/thinParticleSystem.ts
  packages/dev/core/src/ShadersWGSL/particles.fragment.fx
  packages/dev/core/src/ShadersWGSL/particles.vertex.fx
Labels: new feature, WebGPU

#15415 Update BBox Gizmo style
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
  packages/tools/tests/test/visualization/ReferenceImages/nested-BBG.png
Labels: enhancement, gizmos

#15426 Add ref counting for effects
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/effect.ts
  packages/dev/core/src/Materials/effectRenderer.ts
Labels: skip changelog

#15430 Fix pbr world normal mismatch
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/tools/nodeEditor/src/graphSystem/blockNodeData.ts
Labels: skip changelog

#15424 Lens flares to WebGPU
  packages/dev/core/src/Layers/effectLayer.ts
  packages/dev/core/src/LensFlares/index.ts
  packages/dev/core/src/LensFlares/lensFlare.ts
  packages/dev/core/src/LensFlares/lensFlareSystem.ts
  packages/dev/core/src/ShadersWGSL/lensFlare.fragment.fx
  packages/dev/core/src/ShadersWGSL/lensFlare.vertex.fx
Labels: new feature, WebGPU

#15431 Fix getTextureData
  packages/dev/core/src/Misc/textureTools.ts
Labels: bug, skip changelog

#15433 PP.Geteffect can return null
  packages/dev/core/src/Misc/rgbdTextureTools.ts
  packages/dev/core/src/Misc/screenshotTools.ts
  packages/dev/core/src/Misc/textureTools.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/tools/nodeEditor/src/sharedComponents/textureLineComponent.tsx
  packages/tools/nodeGeometryEditor/src/sharedComponents/textureLineComponent.tsx
Labels: skip changelog

#15434 remove unused functions
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
Labels: skip changelog

#15439 Fix ocean shader
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/materials/src/custom/customMaterial.ts
Labels: skip changelog

#15438 Add more coverage for visual tests
  packages/tools/tests/test/visualization/ReferenceImages/detail-map.png
  packages/tools/tests/test/visualization/ReferenceImages/needDepthPrePass.png
  packages/tools/tests/test/visualization/ReferenceImages/simple-refraction.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15440 Cascaded Shadows Map to webgpu
  packages/dev/core/src/Lights/Shadows/cascadedShadowGenerator.ts
Labels: new feature, WebGPU

#15442 CopyTexture to WebGPU
  packages/dev/core/src/Misc/copyTextureToTexture.ts
  packages/dev/core/src/Misc/index.ts
  packages/dev/core/src/ShadersWGSL/copyTextureToTexture.fragment.fx
Labels: skip changelog

#15444 Fix texture preview gone missing
  packages/tools/nodeEditor/src/sharedComponents/textureLineComponent.tsx
Labels: skip changelog

#15443 Fix pp logic
  packages/dev/core/src/Layers/highlightLayer.ts
  packages/dev/core/src/PostProcesses/anaglyphPostProcess.ts
  packages/dev/core/src/PostProcesses/blackAndWhitePostProcess.ts
  packages/dev/core/src/PostProcesses/bloomMergePostProcess.ts
  packages/dev/core/src/PostProcesses/blurPostProcess.ts
  packages/dev/core/src/PostProcesses/circleOfConfusionPostProcess.ts
  packages/dev/core/src/PostProcesses/depthOfFieldMergePostProcess.ts
  packages/dev/core/src/PostProcesses/extractHighlightsPostProcess.ts
  packages/dev/core/src/PostProcesses/fxaaPostProcess.ts
  packages/dev/core/src/PostProcesses/imageProcessingPostProcess.ts
  packages/dev/core/src/PostProcesses/vrDistortionCorrectionPostProcess.ts
Labels: skip changelog

#15445 Cleanup
  packages/dev/core/src/Misc/environmentTextureTools.ts
  packages/dev/core/src/Particles/thinParticleSystem.ts
Labels: skip changelog

#15446 Adding an option to load last minute async at Effect level
  packages/dev/core/src/Buffers/buffer.nonFloatVertexBuffers.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/effect.ts
  packages/dev/core/src/Particles/particleSystemComponent.ts
  packages/dev/core/src/Particles/thinParticleSystem.ts
Labels: new feature, WebGPU

#15447 More Postprocesses ported to webgpu
  packages/dev/core/src/Collisions/gpuPicker.ts
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Layers/effectLayer.ts
  packages/dev/core/src/Layers/glowLayer.ts
  packages/dev/core/src/Layers/highlightLayer.ts
  packages/dev/core/src/Layers/layer.ts
  packages/dev/core/src/Materials/Background/backgroundMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/effect.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/Meshes/linesMesh.ts
  packages/dev/core/src/Particles/particleSystemComponent.ts
  packages/dev/core/src/PostProcesses/anaglyphPostProcess.ts
  packages/dev/core/src/PostProcesses/blackAndWhitePostProcess.ts
  packages/dev/core/src/PostProcesses/bloomMergePostProcess.ts
  packages/dev/core/src/PostProcesses/blurPostProcess.ts
  packages/dev/core/src/PostProcesses/chromaticAberrationPostProcess.ts
  packages/dev/core/src/PostProcesses/circleOfConfusionPostProcess.ts
  packages/dev/core/src/PostProcesses/colorCorrectionPostProcess.ts
  packages/dev/core/src/PostProcesses/convolutionPostProcess.ts
  packages/dev/core/src/PostProcesses/depthOfFieldMergePostProcess.ts
  packages/dev/core/src/PostProcesses/displayPassPostProcess.ts
  packages/dev/core/src/PostProcesses/extractHighlightsPostProcess.ts
  packages/dev/core/src/PostProcesses/filterPostProcess.ts
  packages/dev/core/src/PostProcesses/fxaaPostProcess.ts
  packages/dev/core/src/PostProcesses/grainPostProcess.ts
  packages/dev/core/src/PostProcesses/highlightsPostProcess.ts
  packages/dev/core/src/PostProcesses/imageProcessingPostProcess.ts
  packages/dev/core/src/PostProcesses/index.ts
  packages/dev/core/src/PostProcesses/motionBlurPostProcess.ts
  packages/dev/core/src/PostProcesses/passPostProcess.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/PostProcesses/sharpenPostProcess.ts
  packages/dev/core/src/PostProcesses/tonemapPostProcess.ts
  packages/dev/core/src/PostProcesses/vrDistortionCorrectionPostProcess.ts
  packages/dev/core/src/ShadersWGSL/displayPass.fragment.fx
  packages/dev/core/src/ShadersWGSL/filter.fragment.fx
  packages/dev/core/src/ShadersWGSL/highlights.fragment.fx
  packages/dev/core/src/ShadersWGSL/tonemap.fragment.fx
Labels: new feature, WebGPU

#15448 BoundingBox Renderer to WebGPU
  packages/dev/core/src/Rendering/boundingBoxRenderer.ts
  packages/dev/core/src/Rendering/index.ts
  packages/dev/core/src/ShadersWGSL/boundingBoxRenderer.fragment.fx
  packages/dev/core/src/ShadersWGSL/boundingBoxRenderer.vertex.fx
Labels: new feature, WebGPU

#15455 Fix missing transfer
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssao2RenderingPipeline.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssrRenderingPipeline.ts
Labels: skip changelog

#15456 EdgesRenderer to WebGPU
  packages/dev/core/src/Rendering/boundingBoxRenderer.ts
  packages/dev/core/src/Rendering/edgesRenderer.ts
  packages/dev/core/src/Rendering/index.ts
  packages/dev/core/src/ShadersWGSL/line.fragment.fx
  packages/dev/core/src/ShadersWGSL/line.vertex.fx
Labels: new feature, WebGPU

#15458 In preparation for EXR, moved all texture loaders to deferred loading
  packages/dev/core/src/Engines/AbstractEngine/abstractEngine.cubeTexture.ts
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Materials/Textures/Loaders/basisTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/ddsTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/envTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/hdrTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/index.ts
  packages/dev/core/src/Materials/Textures/Loaders/internalTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/ktxTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/textureLoaderManager.ts
  packages/dev/core/src/Materials/Textures/Loaders/tgaTextureLoader.ts
  packages/dev/core/src/Materials/Textures/index.ts
Labels: loaders, new feature

#15460 Scene meshes ordering list
  packages/dev/core/src/scene.ts
Labels: bug

#15463 Fix #15397
  packages/dev/core/src/Misc/fileTools.ts
Labels: new feature

#15465 Fixed TinyEXR attribution and license
  packages/dev/core/src/Materials/Textures/Loaders/EXR/exrLoader.compression.huf.ts
  packages/dev/core/src/Materials/Textures/Loaders/EXR/exrLoader.compression.rle.ts
  packages/dev/core/src/Materials/Textures/Loaders/EXR/exrLoader.compression.ts
  packages/dev/core/src/Materials/Textures/Loaders/EXR/exrLoader.core.ts
  packages/dev/core/src/Materials/Textures/Loaders/EXR/exrLoader.decoder.ts
  packages/dev/core/src/Materials/Textures/Loaders/EXR/exrLoader.header.ts
  packages/dev/core/src/Materials/Textures/Loaders/exrTextureLoader.ts
Labels: skip changelog

#15471 Add labelTooltip to NumericInput
  packages/dev/sharedUiComponents/src/lines/colorLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/numericInputComponent.tsx
Labels: enhancement

#15472 Native Texture Loaders
  packages/dev/core/src/Engines/nativeEngine.ts
Labels: skip changelog

#15476 Don't enforce ContentSecurityPolicy for image loading if the disposition is "report"
  packages/dev/core/src/Misc/fileTools.ts
Labels: bug

#15486 Fix ternary op crash for native
  packages/dev/core/src/Shaders/ShadersInclude/pbrHelperFunctions.fx
Labels: native

#15487 fix BB Style anchor alignment
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
Labels: skip changelog

#15495 SpriteRenderer dispose
  packages/dev/core/src/Sprites/spriteRenderer.ts
Labels: skip changelog

#15494 shouldHitTriggers raycast query option
  packages/dev/core/src/Physics/physicsRaycastResult.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
Labels: enhancement, physics

#15500 Fix ssao shader compilation bug
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssao2RenderingPipeline.ts
Labels: bug

#15503 fix wrong drag axis bboxgizmo
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
Labels: skip changelog
