Repository BabylonJS/Babylon.js, pull requests merged in 2024-02, with the labels that each got.

#14755 Use shader material written in wgsl as shadow depth wrapper
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Materials/effect.ts
  packages/dev/core/src/Materials/shadowDepthWrapper.ts
Labels: materials, new feature, WebGPU

#14761 Allow loading .ply with loadFileAsync
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: skip changelog

#14762 Misc updates for RSM & WebGPU timestamp queries
  packages/dev/core/src/Engines/WebGPU/webgpuTimestampQuery.ts
  packages/dev/core/src/Rendering/reflectiveShadowMap.ts
Labels: skip changelog

#14764 Camera: Add hasMoved property
  packages/dev/core/src/Cameras/camera.ts
Labels: enhancement, rendering engine

#14767 Ray: use an epsilon when calculating ray/triangle intersections
  packages/dev/core/src/Culling/ray.ts
Labels: enhancement, collisions

#14768 ShaderMaterial: add support for fog
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Shaders/color.fragment.fx
  packages/dev/core/src/Shaders/color.vertex.fx
Labels: enhancement, materials

#14765 Particle systems: add support for fog
  packages/dev/core/src/Materials/materialHelper.ts
  packages/dev/core/src/Particles/baseParticleSystem.ts
  packages/dev/core/src/Particles/gpuParticleSystem.ts
  packages/dev/core/src/Particles/particleSystem.ts
  packages/dev/core/src/Shaders/gpuRenderParticles.fragment.fx
  packages/dev/core/src/Shaders/gpuRenderParticles.vertex.fx
  packages/dev/core/src/Shaders/particles.fragment.fx
  packages/dev/core/src/Shaders/particles.vertex.fx
Labels: enhancement, particles

#14772 Ray: set non 0 epsilon
  packages/dev/core/src/Culling/ray.ts
Labels: enhancement, collisions

#14771 PostProcess: Add a simple TAA rendering pipeline
  packages/dev/core/src/Maths/halton2DSequence.ts
  packages/dev/core/src/Maths/index.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/index.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/taaRenderingPipeline.ts
  packages/dev/core/src/Shaders/taa.fragment.fx
Labels: new feature, post-process

#14779 TrailMesh: Add texture coordinates to trail mesh
  packages/dev/core/src/Meshes/trailMesh.ts
Labels: enhancement, rendering engine

#14783 TAA: Fix when using an orthographic camera
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/taaRenderingPipeline.ts
Labels: bug, rendering engine

#14786 GreasedLines: Fix material not disposed
  packages/dev/core/src/Meshes/GreasedLine/greasedLineBaseMesh.ts
Labels: bug, materials

#14785 Animation: Fix animation delta time in deterministic mode
  packages/dev/core/src/scene.ts
Labels: bug, animations

#14797 AnimationGroup: Add setters for "from" and "to" properties
  packages/dev/core/src/Animations/animationGroup.ts
Labels: enhancement, animations

#14798 make vision OS emulator work
  packages/dev/core/src/LibDeclarations/webxr.d.ts
  packages/dev/core/src/XR/features/WebXRControllerPointerSelection.ts
  packages/dev/core/src/XR/features/WebXRControllerTeleportation.ts
Labels: skip changelog

#14799 Add timeStep option to NullEngine
  packages/dev/core/src/Engines/nullEngine.ts
  packages/dev/core/test/unit/Engines/nullEngine.test.ts
Labels: new feature

#14802 SkeletonViewer: Try to display a spur for the last bone of a chain
  packages/dev/core/src/Debug/skeletonViewer.ts
Labels: enhancement, animations, debug tool

#14801 Nge nodes2
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryDistanceBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryDotBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryPosterizeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryReplaceColorBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: skip changelog, nge

#14800 Associated with #14595
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
Labels: skip changelog, nge

#14803 Associated with #14595
  packages/dev/core/src/Meshes/Node/Blocks/geometryLengthBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryRotate2dBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: skip changelog, nge

#14795 Gizmos: add additional transform property
  packages/dev/core/src/Gizmos/gizmo.ts
  packages/dev/core/src/Gizmos/gizmoManager.ts
  packages/dev/core/src/Gizmos/positionGizmo.ts
  packages/dev/core/src/Gizmos/rotationGizmo.ts
  packages/dev/core/src/Gizmos/scaleGizmo.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/skeletonPropertyGridComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/entities/sceneTreeItemComponent.tsx
Labels: new feature, gizmos

#14806 Particle systems: serialize worldOffset
  packages/dev/core/src/Particles/particleSystem.ts
Labels: bug, particles

#14807 OffscreenCanvas doesn't have the remove function
  packages/dev/core/src/Engines/ICanvas.ts
  packages/dev/core/src/Materials/Textures/dynamicTexture.ts
Labels: bug

#14813 TrailMesh: Fix wrong starting position when the generator is a TransformNode
  packages/dev/core/src/Meshes/trailMesh.ts
Labels: bug, rendering engine

#14815 WebGPU: Simplify error handling during engine creation/initialization
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/tools/playground/src/components/rendererComponent.tsx
Labels: enhancement, WebGPU

#14819 GUI - Allow InputText text outline
  packages/dev/gui/src/2D/controls/inputText.ts
  packages/dev/gui/src/2D/controls/inputTextArea.ts
Labels: new feature

#14821 Type change to XRHand
  packages/dev/core/src/LibDeclarations/webxr.d.ts
Labels: skip changelog
