Repository BabylonJS/Babylon.js, pull requests merged in 2024-01, with the labels that each got.

#14657 DynamicTexture: add sanity check in dispose
  packages/dev/core/src/Materials/Textures/dynamicTexture.ts
Labels: enhancement, texture

#14664 Fix material plugin calls without register
  packages/dev/core/src/Materials/material.ts
Labels: bug, loaders

#14608 Flow Graph/Interactivity/Animation Pointer Object model
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphGetPropertyBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Event/flowGraphMeshPickEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphPauseAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphPlayAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphStopAnimationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Audio/flowGraphPlayAudioBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/Audio/flowGraphStopAudioBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphCounterBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphDebounceBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphDoNBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphForLoopBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphThrottleBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphWaitAllBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphWhileLoopBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphConsoleLogBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSendCustomEventBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSetPropertyBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSetVariableBlock.ts
  packages/dev/core/src/FlowGraph/flowGraph.ts
  packages/dev/core/src/FlowGraph/flowGraphBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphContext.ts
  packages/dev/core/src/FlowGraph/flowGraphCoordinator.ts
  packages/dev/core/src/FlowGraph/flowGraphExecutionBlockWithOutSignal.ts
  packages/dev/core/src/FlowGraph/flowGraphPath.ts
  packages/dev/core/src/FlowGraph/flowGraphPathComponent.ts
  packages/dev/core/src/FlowGraph/flowGraphPathConverter.ts
  packages/dev/core/src/FlowGraph/flowGraphPathConverterComponent.ts
  packages/dev/core/src/FlowGraph/index.ts
  packages/dev/core/src/FlowGraph/serialization.ts
  packages/dev/core/src/FlowGraph/typeDefinitions.ts
  packages/dev/core/src/ObjectModel/index.ts
  packages/dev/core/src/ObjectModel/objectModelInterfaces.ts
  packages/dev/core/src/index.ts
  packages/dev/core/test/unit/FlowGraph/flowGraphEventNodes.test.ts
  packages/dev/core/test/unit/FlowGraph/flowGraphExecutionNodes.test.ts
  packages/dev/core/test/unit/FlowGraph/flowGraphSerialization.test.ts
  packages/dev/core/test/unit/FlowGraph/flowGraphUtils.test.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_animation_pointer.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_interactivity.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/gltfPathToObjectConverter.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/interactivityFunctions.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/interactivityPathCameraExtensions.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/interactivityPathExtensions.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/interactivityPathMaterialExtensions.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/interactivityPathToObjectConverter.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/interactivityPathTransformNodeExtensions.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/dev/loaders/test/unit/Interactivity/babylon.interactivity.test.ts
  packages/dev/loaders/test/unit/Interactivity/testData.ts
Labels: flow graph

#14665 Fix arcrotate gamepad input
  packages/dev/core/src/Cameras/Inputs/arcRotateCameraGamepadInput.ts
Labels: bug, inputs

#14655 WebGPU: Manage context lost and restoration
  packages/dev/core/src/Engines/Extensions/engine.dynamicTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.dynamicTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.rawTexture.ts
  packages/dev/core/src/Engines/WebGPU/webgpuBufferManager.ts
  packages/dev/core/src/Engines/WebGPU/webgpuCacheBindGroups.ts
  packages/dev/core/src/Engines/WebGPU/webgpuCacheRenderPipeline.ts
  packages/dev/core/src/Engines/WebGPU/webgpuCacheRenderPipelineTree.ts
  packages/dev/core/src/Engines/WebGPU/webgpuCacheSampler.ts
  packages/dev/core/src/Engines/WebGPU/webgpuClearQuad.ts
  packages/dev/core/src/Engines/WebGPU/webgpuHardwareTexture.ts
  packages/dev/core/src/Engines/WebGPU/webgpuPipelineContext.ts
  packages/dev/core/src/Engines/WebGPU/webgpuQuerySet.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureHelper.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureManager.ts
  packages/dev/core/src/Engines/engine.ts
  packages/dev/core/src/Engines/renderTargetWrapper.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/Textures/hardwareTextureWrapper.ts
  packages/dev/core/src/Materials/Textures/internalTexture.ts
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/Materials/uniformBuffer.ts
  packages/dev/core/src/Meshes/WebGPU/webgpuDataBuffer.ts
  packages/dev/core/src/Meshes/geometry.ts
  packages/dev/core/src/Misc/brdfTextureTools.ts
  packages/dev/core/src/Misc/rgbdTextureTools.ts
  packages/dev/core/src/Particles/computeShaderParticleSystem.ts
  packages/dev/core/src/Particles/gpuParticleSystem.ts
  packages/dev/core/src/Particles/particleSystem.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderer.ts
  packages/dev/core/src/types.ts
  packages/tools/tests/test/visualization/ReferenceImages/geometrybufferrenderer.png
  packages/tools/tests/test/visualization/config.json
Labels: enhancement, WebGPU

#14666 ArcRotateCamera: Allow to pass a transform node to setTarget / targetHost
  packages/dev/core/src/Behaviors/Cameras/bouncingBehavior.ts
  packages/dev/core/src/Behaviors/Cameras/framingBehavior.ts
  packages/dev/core/src/Cameras/arcRotateCamera.ts
Labels: enhancement, inputs

#14667 Sandbox: Allow to drop .webp files
  packages/tools/sandbox/src/components/renderingZone.tsx
Labels: enhancement, sandbox

#14668 Clean up ground mesh documentation
  packages/dev/core/src/Meshes/Builders/groundBuilder.ts
Labels: skip changelog

#14670 Camera framing behavior: Fix crash
  packages/dev/core/src/Behaviors/Cameras/framingBehavior.ts
Labels: bug, inputs

#14671 Nge new blocks
  packages/dev/core/src/Meshes/Node/Blocks/geometryArcTan2Block.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryLerpBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryNLerpBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometrySmoothStepBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryStepBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryTrigonometryBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: skip changelog

#14672 Nge add2
  packages/dev/core/src/Meshes/Node/Blocks/geometryClampBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryCrossBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryModBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryPowBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryTrigonometryBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: skip changelog

#14669 Fix scaling problems in sixDofDragBehavior
  packages/dev/core/src/Behaviors/Meshes/sixDofDragBehavior.ts
Labels: bug

#14676 Force texture loading with bitmap when in offscreen canvas
  packages/dev/core/src/Engines/thinEngine.ts
Labels: bug, texture

#14677 Fix camera not being reattached after a two pointer SixDofDragBehavior
  packages/dev/core/src/Behaviors/Meshes/baseSixDofDragBehavior.ts
Labels: bug

#14678 prevent internal misuse of VB
  packages/dev/core/src/Buffers/buffer.align.ts
  packages/dev/core/src/Buffers/buffer.ts
  packages/dev/core/src/Meshes/geometry.ts
Labels: skip changelog

#14682 Skeleton: Fix empty transform matrices when cloning a mesh
  packages/dev/core/src/Bones/skeleton.ts
Labels: bug, bones

#14679 Thin instances: Change default value for the staticBuffer parameter
  packages/dev/core/src/Meshes/thinInstanceMesh.ts
  packages/tools/tests/test/visualization/config.json
Labels: rendering engine, breaking change

#14680 RSM: add support for reflective shadow maps generation + GI based on RSM
  packages/dev/core/src/Materials/materialPluginManager.ts
  packages/dev/core/src/Rendering/GlobalIllumination/giRSM.ts
  packages/dev/core/src/Rendering/GlobalIllumination/giRSMManager.ts
  packages/dev/core/src/Rendering/GlobalIllumination/index.ts
  packages/dev/core/src/Rendering/index.ts
  packages/dev/core/src/Rendering/reflectiveShadowMap.ts
  packages/dev/core/src/Shaders/bilateralBlur.fragment.fx
  packages/dev/core/src/Shaders/bilateralBlurQuality.fragment.fx
  packages/dev/core/src/Shaders/rsmFullGlobalIllumination.fragment.fx
  packages/dev/core/src/Shaders/rsmGlobalIllumination.fragment.fx
Labels: rendering engine, new feature

#14686 Add GA to GUI
  packages/tools/guiEditor/public/index.html
Labels: skip changelog

#14689 Add clarification about transformed position in shadowLight.
  packages/dev/core/src/Lights/shadowLight.ts
Labels: skip changelog

#14688 [XR] Port teleportation observable to feature
  packages/dev/core/src/XR/features/WebXRControllerTeleportation.ts
  packages/dev/core/src/XR/webXRCamera.ts
  packages/dev/core/test/unit/XR/webXRFeaturesManager.test.ts
Labels: skip changelog

#14693 typedoc comment analyzer
  packages/dev/core/src/Engines/ICanvas.ts
  packages/dev/core/src/Engines/Native/validatedNativeDataStream.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphGetVariableBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphDoNBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphSequenceBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/flowGraphSetVariableBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphConnection.ts
  packages/dev/core/src/FlowGraph/flowGraphContext.ts
  packages/dev/core/src/ObjectModel/objectModelInterfaces.ts
  packages/dev/core/src/node.ts
  scripts/comment-analyzer.js
  scripts/typedoc-generator.js
Labels: skip changelog

#14697 Spotlight: Fix wrong projected texture when light is parented
  packages/dev/core/src/Lights/spotLight.ts
Labels: bug, rendering engine

#14695 recast.js update, fix link transform for ragdoll
  packages/dev/core/src/Navigation/INavigationEngine.ts
  packages/dev/core/src/Navigation/Plugins/recastJSPlugin.ts
  packages/dev/core/src/Physics/v2/ragdoll.ts
  packages/tools/babylonServer/public/recast.d.ts
  packages/tools/babylonServer/public/recast.js
Labels: enhancement, navigation

#14691 Flow graph integer math
  packages/dev/core/src/FlowGraph/Blocks/Data/Logic/flowGraphBitwiseBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Logic/index.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphMathBlocks.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/flowGraphUnaryOperationBlock.ts
  packages/dev/core/src/FlowGraph/Blocks/Execution/ControlFlow/flowGraphDoNBlock.ts
  packages/dev/core/src/FlowGraph/flowGraphInteger.ts
  packages/dev/core/src/FlowGraph/flowGraphPathConverterComponent.ts
  packages/dev/core/src/FlowGraph/flowGraphRichTypes.ts
  packages/dev/core/src/FlowGraph/serialization.ts
  packages/dev/core/test/unit/FlowGraph/flowGraphExecutionNodes.test.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/interactivityUtils.ts
  packages/dev/loaders/test/unit/Interactivity/babylon.interactivity.test.ts
  packages/dev/loaders/test/unit/Interactivity/testData.ts
Labels: new feature, flow graph

#14698 WebGPU: Sync with specification
  packages/dev/core/src/Engines/WebGPU/webgpuCacheRenderPipeline.ts
  packages/dev/core/src/Engines/WebGPU/webgpuConstants.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/LibDeclarations/webgpu.d.ts
Labels: enhancement, WebGPU

#14702 Updating typedoc check script
  package-lock.json
  package.json
  scripts/comment-analyzer.js
  scripts/typedoc-generator.js
Labels: skip changelog

#14704 add clarification to pbrmaterial docs
  packages/dev/core/src/Materials/PBR/pbrMaterial.ts
Labels: skip changelog

#14708 Fix parent transformations being applied to position/rotation deltas …
  packages/dev/core/src/Behaviors/Meshes/sixDofDragBehavior.ts
Labels: bug

#14710 TransformNode: Serialize animations
  packages/dev/core/src/Meshes/transformNode.ts
Labels: enhancement, animations

#14712 Further updates to typedoc script and missing docs
  packages/dev/core/src/Cameras/Inputs/BaseCameraPointersInput.ts
  packages/dev/core/src/Cameras/Inputs/freeCameraMouseInput.ts
  packages/dev/core/src/Cameras/VR/vrExperienceHelper.ts
  packages/dev/core/src/Culling/Octrees/octree.ts
  packages/dev/core/src/Debug/physicsViewer.ts
  packages/dev/core/src/FlowGraph/Blocks/Data/Math/flowGraphMathBlocks.ts
  packages/dev/core/src/Gizmos/gizmo.ts
  packages/dev/core/src/Loading/sceneLoader.ts
  packages/dev/core/src/Materials/GreasedLine/greasedLineMaterialInterfaces.ts
  packages/dev/core/src/Materials/GreasedLine/greasedLinePluginMaterial.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/index.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/reflectionTextureBaseBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Input/prePassTextureBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrMetallicRoughnessMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrSpecularGlossinessMaterial.ts
  packages/dev/core/src/Materials/Textures/Procedurals/noiseProceduralTexture.ts
  packages/dev/core/src/Materials/Textures/multiRenderTarget.ts
  packages/dev/core/src/Materials/Textures/thinRenderTargetTexture.ts
  packages/dev/core/src/Maths/math.polar.ts
  packages/dev/core/src/Maths/math.vector.ts
  packages/dev/core/src/Meshes/GreasedLine/greasedLineBaseMesh.ts
  packages/dev/core/src/Meshes/Node/Blocks/Textures/geometryTextureBlock.ts
  packages/dev/core/src/Meshes/instancedMesh.ts
  packages/dev/core/src/Meshes/linesMesh.ts
  packages/dev/core/src/Misc/HighDynamicRange/hdr.ts
  packages/dev/core/src/Misc/HighDynamicRange/panoramaToCubemap.ts
  packages/dev/core/src/Misc/decorators.ts
  packages/dev/core/src/Misc/greasedLineTools.ts
  packages/dev/core/src/Misc/tools.ts
  packages/dev/core/src/Misc/webRequest.ts
  packages/dev/core/src/Physics/physicsRaycastResult.ts
  packages/dev/core/src/Physics/v1/physicsImpostor.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsBody.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssao2RenderingPipeline.ts
  packages/dev/core/src/XR/index.ts
  scripts/comment-analyzer.js
  scripts/typedoc-generator.js
Labels: skip changelog

#14711 Gaussian Splatting: add a gaussian splatting mesh and material
  packages/dev/core/src/Materials/GaussianSplatting/gaussianSplattingMaterial.ts
  packages/dev/core/src/Materials/index.ts
  packages/dev/core/src/Materials/uniformBuffer.ts
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/core/src/Meshes/index.ts
  packages/dev/core/src/Rendering/GaussianSplatting/gaussianSplatting.ts
  packages/dev/core/src/Rendering/GaussianSplatting/index.ts
  packages/dev/core/src/Rendering/index.ts
  packages/dev/core/src/Shaders/ShadersInclude/gaussianSplattingUboDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/gaussianSplattingVertexDeclaration.fx
  packages/dev/core/src/Shaders/gaussianSplatting.fragment.fx
  packages/dev/core/src/Shaders/gaussianSplatting.vertex.fx
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: materials, new feature

#14715 fix animation events not firing for 1 key animations
  packages/dev/core/src/Animations/runtimeAnimation.ts
Labels: bug

#14714 WebGPU: Allow to pass an offscreen canvas to the constructor
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: enhancement, WebGPU

#14716 WebXR world scaling factor
  packages/dev/core/src/XR/features/WebXRControllerTeleportation.ts
  packages/dev/core/src/XR/features/WebXREyeTracking.ts
  packages/dev/core/src/XR/features/WebXRHandTracking.ts
  packages/dev/core/src/XR/features/WebXRHitTest.ts
  packages/dev/core/src/XR/features/WebXRNearInteraction.ts
  packages/dev/core/src/XR/webXRCamera.ts
  packages/dev/core/src/XR/webXRInput.ts
  packages/dev/core/src/XR/webXRInputSource.ts
  packages/dev/core/src/XR/webXRSessionManager.ts
Labels: new feature

#14718 Basic inspector for V2 physics
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsBody.ts
  packages/dev/core/src/Physics/v2/physicsShape.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/meshPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/physics/physicsBodyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/physics/physicsMassPropertiesGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/physics/physicsMaterialGridComponent.tsx
  packages/dev/sharedUiComponents/src/lines/floatLineComponent.tsx
Labels: physics, new feature

#14721 Particle systems: When using the cylinder-directed particle emitter, fix the start direction when in local space
  packages/dev/core/src/Particles/EmitterTypes/cylinderParticleEmitter.ts
  packages/dev/core/src/Particles/IParticleSystem.ts
Labels: bug, particles

#14722 Add isSerializable flag to GUI controls
  packages/dev/gui/package.json
  packages/dev/gui/src/2D/controls/button.ts
  packages/dev/gui/src/2D/controls/container.ts
  packages/dev/gui/src/2D/controls/control.ts
  packages/dev/gui/src/2D/controls/focusableButton.ts
  packages/dev/gui/src/2D/controls/grid.ts
  packages/dev/gui/src/2D/controls/stackPanel.ts
  packages/dev/gui/test/unit/serialization.test.ts
  packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/commonControlPropertyGridComponent.tsx
Labels: enhancement, gui

#14723 Particle systems: Fix serialization and parsing of CustomParticleEmitter
  packages/dev/core/src/Particles/EmitterTypes/customParticleEmitter.ts
  packages/dev/core/src/Particles/particleSystem.ts
Labels: bug, particles

#14724 Fix audio engine unlock issue
  packages/dev/core/src/Audio/audioEngine.ts
Labels: bug

#14729 Flush for Native does nothing
  packages/dev/core/src/Engines/nativeEngine.ts
Labels: native

#14728 Add no-throw-literal eslint rule.
  .eslintrc.js
  packages/dev/core/src/Animations/pathCursor.ts
  packages/dev/core/src/Behaviors/Meshes/pointerDragBehavior.ts
  packages/dev/core/src/DeviceInput/eventFactory.ts
  packages/dev/core/src/DeviceInput/webDeviceInputSystem.ts
  packages/dev/core/src/Engines/Extensions/engine.multiview.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.readTexture.ts
  packages/dev/core/src/Engines/WebGPU/webgpuCacheRenderPipeline.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessingContext.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureHelper.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureManager.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Gizmos/cameraGizmo.ts
  packages/dev/core/src/Gizmos/gizmo.ts
  packages/dev/core/src/Loading/sceneLoader.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/fragCoordBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/frontFacingBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/screenSizeBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlockConnectionPoint.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildStateSharedData.ts
  packages/dev/core/src/Materials/Textures/Loaders/envTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/hdrTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/tgaTextureLoader.ts
  packages/dev/core/src/Materials/materialPluginManager.ts
  packages/dev/core/src/Materials/uniformBuffer.ts
  packages/dev/core/src/Meshes/GreasedLine/greasedLineRibbonMesh.ts
  packages/dev/core/src/Meshes/Node/nodeGeometry.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlockConnectionPoint.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBuildState.ts
  packages/dev/core/src/Meshes/csg.ts
  packages/dev/core/src/Misc/HighDynamicRange/hdr.ts
  packages/dev/core/src/Misc/HighDynamicRange/panoramaToCubemap.ts
  packages/dev/core/src/Misc/basis.ts
  packages/dev/core/src/Misc/videoRecorder.ts
  packages/dev/core/src/Particles/gpuParticleSystem.ts
  packages/dev/core/src/Particles/particleSystem.ts
  packages/dev/core/src/Physics/v1/Plugins/ammoJSPlugin.ts
  packages/dev/core/src/Rendering/depthRendererSceneComponent.ts
  packages/dev/core/src/XR/webXRExperienceHelper.ts
  packages/dev/core/src/XR/webXRSessionManager.ts
  packages/dev/core/test/unit/DeviceInput/babylon.inputManager.test.ts
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
  packages/dev/gui/src/2D/xmlLoader.ts
  packages/dev/inspector/src/components/sceneExplorer/entities/gui/guiTools.ts
  packages/dev/materials/src/fur/furMaterial.ts
  packages/tools/guiEditor/src/guiNodeTools.ts
Labels: skip changelog

#14726 Move delegate picking to children to container
  packages/dev/gui/src/2D/controls/button.ts
  packages/dev/gui/src/2D/controls/container.ts
  packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/containerPropertyGridComponent.tsx
Labels: enhancement, gui

#14730 glTF loader: Add an option to pass a custom root node
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_materials_variants.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/dev/loaders/src/glTF/glTFFileLoader.ts
Labels: enhancement, glTF

#14731 small fixes to physics
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsBody.ts
Labels: physics, skip changelog

#14733 glTF loader: allow no root node
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_materials_variants.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/dev/loaders/src/glTF/glTFFileLoader.ts
Labels: enhancement, glTF

#14734 Morph targets: Pass the number of active targets to the shader as a uniform
  .vscode/settings.json
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Materials/materialHelper.ts
  packages/dev/core/src/Morph/morphTargetManager.ts
  packages/dev/core/src/Shaders/ShadersInclude/morphTargetsVertex.fx
  packages/dev/core/src/Shaders/ShadersInclude/morphTargetsVertexDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/morphTargetsVertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/morphTargetsVertexDeclaration.fx
Labels: enhancement, rendering engine

#14737 Associated with #14595
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: skip changelog

#14738 Babylon Toolkit For Unity
  packages/tools/playground/public/libs/babylon.manager.d.ts
  packages/tools/playground/public/libs/babylon.manager.js
  packages/tools/playground/src/components/rendererComponent.tsx
  packages/tools/playground/src/tools/monacoManager.ts
Labels: skip changelog

#14740 Animations: Fix broken loop when speedRatio is negative
  packages/dev/core/src/Animations/runtimeAnimation.ts
Labels: bug, animations

#14743 Associated with #14595 - desaturate
  packages/dev/core/src/Meshes/Node/Blocks/geometryDesaturateBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: skip changelog, nge

#14742 If checkbox's default color is not set, use white.
  packages/dev/gui/src/2D/controls/checkbox.ts
Labels: gui

#14736 Point Proximity, Shape Proximity and Shape Cast in Havok
  packages/dev/core/src/Debug/physicsViewer.ts
  packages/dev/core/src/Physics/castingResult.ts
  packages/dev/core/src/Physics/index.ts
  packages/dev/core/src/Physics/physicsPointProximityQuery.ts
  packages/dev/core/src/Physics/physicsRaycastResult.ts
  packages/dev/core/src/Physics/physicsShapeCastQuery.ts
  packages/dev/core/src/Physics/physicsShapeProximityCastQuery.ts
  packages/dev/core/src/Physics/proximityCastResult.ts
  packages/dev/core/src/Physics/shapeCastResult.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/tools/babylonServer/public/havok/HavokPhysics.wasm
Labels: physics, new feature

#14741 Materials: Improve management of frozen materials
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Materials/Background/backgroundMaterial.ts
  packages/dev/core/src/Materials/GaussianSplatting/gaussianSplattingMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/drawWrapper.ts
  packages/dev/core/src/Materials/effect.ts
  packages/dev/core/src/Materials/effectRenderer.ts
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/Materials/pushMaterial.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/Meshes/abstractMesh.ts
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/gui/src/3D/materials/fluent/fluentMaterial.ts
  packages/dev/gui/src/3D/materials/fluentBackplate/fluentBackplateMaterial.ts
  packages/dev/gui/src/3D/materials/fluentButton/fluentButtonMaterial.ts
  packages/dev/gui/src/3D/materials/mrdl/mrdlBackglowMaterial.ts
  packages/dev/gui/src/3D/materials/mrdl/mrdlBackplateMaterial.ts
  packages/dev/gui/src/3D/materials/mrdl/mrdlFrontplateMaterial.ts
  packages/dev/gui/src/3D/materials/mrdl/mrdlInnerquadMaterial.ts
  packages/dev/gui/src/3D/materials/mrdl/mrdlSliderBarMaterial.ts
  packages/dev/gui/src/3D/materials/mrdl/mrdlSliderThumbMaterial.ts
  packages/dev/materials/src/cell/cellMaterial.ts
  packages/dev/materials/src/custom/customMaterial.ts
  packages/dev/materials/src/custom/pbrCustomMaterial.ts
  packages/dev/materials/src/fire/fireMaterial.ts
  packages/dev/materials/src/fur/furMaterial.ts
  packages/dev/materials/src/gradient/gradientMaterial.ts
  packages/dev/materials/src/grid/gridMaterial.ts
  packages/dev/materials/src/lava/lavaMaterial.ts
  packages/dev/materials/src/mix/mixMaterial.ts
  packages/dev/materials/src/normal/normalMaterial.ts
  packages/dev/materials/src/shadowOnly/shadowOnlyMaterial.ts
  packages/dev/materials/src/simple/simpleMaterial.ts
  packages/dev/materials/src/sky/skyMaterial.ts
  packages/dev/materials/src/terrain/terrainMaterial.ts
  packages/dev/materials/src/triPlanar/triPlanarMaterial.ts
  packages/dev/materials/src/water/waterMaterial.ts
Labels: enhancement, materials
