Repository BabylonJS/Babylon.js, pull requests merged in 2024-06, with the labels that each got.

#15158 Physics Velocity Limits
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsEngine.ts
Labels: enhancement, physics

#15159 Edge renderer: Add support in fast snapshot mode
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/Materials/pushMaterial.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Rendering/edgesRenderer.ts
  packages/dev/core/src/Shaders/ShadersInclude/lineUboDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/lineVertexDeclaration.fx
  packages/dev/core/src/Shaders/line.vertex.fx
Labels: enhancement, rendering engine

#15160 Make AbstractMesh a real abstract class
  packages/dev/core/src/Behaviors/Cameras/framingBehavior.ts
  packages/dev/core/src/Behaviors/Meshes/baseSixDofDragBehavior.ts
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
  packages/dev/core/src/Gizmos/lightGizmo.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Meshes/abstractMesh.ts
  packages/dev/core/src/Meshes/transformNode.ts
  packages/dev/core/src/XR/webXRInputSource.ts
  packages/tools/viewer/src/model/viewerModel.ts
Labels: breaking change

#15161 Add support for null geometry
  packages/dev/core/src/Meshes/Node/Blocks/mergeGeometryBlock.ts
Labels: bug, nge

#15151 Remove disposed body from physicsViewer
  packages/dev/core/src/Debug/physicsViewer.ts
Labels: bug, physics

#15162 Fix VertexData.ExtractFrom functions to support 3-component colors
  packages/dev/core/src/Meshes/abstractMesh.ts
  packages/dev/core/src/Meshes/mesh.vertexData.ts
Labels: bug

#15165 Fix context lost event leak
  packages/dev/core/src/Engines/thinEngine.ts
Labels: bug

#15166 Create a new picking mechanism using GPU
  packages/dev/core/src/Collisions/gpuPicker.ts
  packages/dev/core/src/Collisions/index.ts
  packages/dev/core/src/Helpers/environmentHelper.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/tools/tests/test/visualization/ReferenceImages/gpuPicker.png
  packages/tools/tests/test/visualization/config.json
Labels: picking, new feature

#15169 Fix colored layer
  packages/dev/core/src/Layers/layer.ts
Labels: bug

#15170 serialized physics fix
  packages/dev/core/src/Loading/Plugins/babylonFileLoader.ts
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug, physics

#15173 Quick fixes for GPU Picker
  packages/dev/core/src/Collisions/gpuPicker.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
Labels: skip changelog

#15172 Fix CurrentScreen
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/currentScreenBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/sceneDepthBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
Labels: skip changelog

#15175 Gpu pick2
  packages/dev/core/src/Collisions/gpuPicker.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Shaders/picking.fragment.fx
  packages/dev/core/src/Shaders/picking.vertex.fx
Labels: skip changelog

#15177 Fix WebGPU none autoplay video
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.videoTexture.ts
Labels: bug, WebGPU

#15176 Address feedback
  packages/dev/core/src/Collisions/gpuPicker.ts
  packages/dev/core/src/Shaders/picking.vertex.fx
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15179 fix CI
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15181 Fix SVG loader for GUI
  packages/dev/gui/src/2D/controls/image.ts
Labels: bug

#15174 Heightfield physics shape
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsAggregate.ts
  packages/dev/core/src/Physics/v2/physicsShape.ts
Labels: enhancement, physics

#15180 Add new Grid mode for NGE Instantiate on Volume
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVolumeBlock.ts
Labels: new feature

#15185 Fix svg image
  packages/dev/gui/src/2D/controls/image.ts
Labels: skip changelog

#15187 Add a try catch to protect from invalid data
  packages/dev/loaders/src/glTF/glTFFileLoader.ts
Labels: bug

#15191 Nme webgpu 7
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Materials/Node/Blocks/Input/inputBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Particle/particleBlendMultiplyBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Particle/particleRampGradientBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Particle/particleTextureBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildState.ts
  packages/dev/core/src/Particles/particleSystemComponent.ts
  packages/dev/core/src/ShadersWGSL/ShadersInclude/fogVertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/fogVertexDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/logDepthDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/logDepthVertex.fx
  packages/dev/core/src/ShadersWGSL/particles.vertex.fx
Labels: skip changelog

#15188 ImageProcessingBlock ported to WebGPU support
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/imageProcessingBlock.ts
  packages/dev/core/src/ShadersWGSL/ShadersInclude/imageProcessingDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/imageProcessingFunctions.fx
Labels: skip changelog

#15189 Improve clarity about how mesh.sideOrientation works
  packages/dev/core/src/Layers/effectLayer.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/Meshes/Builders/decalBuilder.ts
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/core/src/Rendering/depthRenderer.ts
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/commonMaterialPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/meshPropertyGridComponent.tsx
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/dev/serializers/src/OBJ/objSerializer.ts
  packages/dev/serializers/src/glTF/2.0/glTFExporter.ts
Labels: new feature, breaking change

#15194 Add missing side-effects import to nativeEngine.ts
  packages/dev/core/src/Engines/nativeEngine.ts
Labels: bug

#15193 Improve GS quality with XR Camera
  packages/dev/core/src/Materials/GaussianSplatting/gaussianSplattingMaterial.ts
Labels: enhancement

#15195 Inspector: allows to change outline width
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/meshes/meshPropertyGridComponent.tsx
Labels: enhancement, inspector

#15197 Fix UI in property manager for sideOrientation
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/commonMaterialPropertyGridComponent.tsx
Labels: skip changelog

#15196 Finishing particles for nme Webgpu
  packages/dev/core/src/Materials/Node/Blocks/Input/inputBlock.ts
  packages/tools/nodeEditor/public/index.js
  packages/tools/nodeEditor/src/components/propertyTab/propertyTabComponent.tsx
  packages/tools/nodeEditor/src/globalState.ts
Labels: skip changelog

#15198 ReflectionTextureBlock
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/reflectionTextureBaseBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/reflectionTextureBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/reflectionBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildState.ts
  packages/dev/core/src/ShadersWGSL/ShadersInclude/reflectionFunction.fx
  packages/tools/nodeEditor/src/main.scss
Labels: skip changelog

#15199 Restore back compat
  packages/dev/core/src/Meshes/mesh.ts
Labels: skip changelog

#15201 Fix backcompat
  packages/dev/core/src/Meshes/abstractMesh.ts
  packages/dev/core/src/Meshes/mesh.ts
Labels: skip changelog

#15202 Nmegltf test
  packages/tools/tests/test/visualization/ReferenceImages/nmegltf.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15203 Stronger defense for Back compat
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Meshes/abstractMesh.ts
Labels: skip changelog

#15204 fix fragdepthblock issue
  packages/dev/core/src/Materials/Node/Blocks/Fragment/fragDepthBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/shadowMapBlock.ts
  packages/tools/tests/test/visualization/ReferenceImages/nmeshadowmap.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15206 Mesh: Fix back compat for sideOrientation when parsing mesh
  packages/dev/core/src/Meshes/mesh.ts
  packages/tools/tests/test/visualization/config.json
Labels: bug, rendering engine

#15211 Fluid renderer: Don't dispose of effects when disposing of fluid objects
  packages/dev/core/src/Materials/effectRenderer.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingObject.ts
Labels: bug, rendering engine

#15216 New BoundingBoxHelper class used to compute Bounding Box info with GPU
  packages/dev/core/src/Culling/Helper/boundingInfoHelper.ts
  packages/dev/core/src/Culling/Helper/webgl2BoundingHelper.ts
  packages/dev/core/src/Culling/index.ts
  packages/dev/core/src/Engines/Extensions/engine.transformFeedback.ts
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/core/src/Shaders/gpuTransform.fragment.fx
  packages/dev/core/src/Shaders/gpuTransform.vertex.fx
Labels: new feature

#15217 Fix shader compile issue with non-float vertex buffers for native
  packages/dev/core/src/Engines/nativeEngine.ts
Labels: bug

#15221 Bbhelper 2 - compute shaders
  packages/dev/buildTools/src/addJSToCompiledFiles.ts
  packages/dev/core/src/Compute/computeEffect.ts
  packages/dev/core/src/Culling/Helper/IBoundingInfoHelperPlatform.ts
  packages/dev/core/src/Culling/Helper/boundingInfoHelper.ts
  packages/dev/core/src/Culling/Helper/computeShaderBoundingHelper.ts
  packages/dev/core/src/Culling/Helper/transformFeedbackBoundingHelper.ts
  packages/dev/core/src/Culling/Helper/webgl2BoundingHelper.ts
  packages/dev/core/src/Culling/index.ts
  packages/dev/core/src/Engines/Processors/shaderProcessingOptions.ts
  packages/dev/core/src/Engines/Processors/shaderProcessor.ts
  packages/dev/core/src/Meshes/abstractMesh.ts
  packages/dev/core/src/Morph/morphTargetManager.ts
  packages/dev/core/src/ShadersWGSL/boundingInfo.compute.fx
  packages/tools/tests/test/visualization/ReferenceImages/bbhelper.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15226 SpriteMap: Fix WebGPU compilation
  packages/dev/core/src/Shaders/spriteMap.fragment.fx
Labels: bug, WebGPU

#15225 BoundingBox helper: add batch methods
  packages/dev/core/src/Culling/Helper/IBoundingInfoHelperPlatform.ts
  packages/dev/core/src/Culling/Helper/boundingInfoHelper.ts
  packages/dev/core/src/Culling/Helper/computeShaderBoundingHelper.ts
  packages/dev/core/src/Culling/Helper/transformFeedbackBoundingHelper.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/ShadersWGSL/boundingInfo.compute.fx
Labels: enhancement, rendering engine

#15227 Physics Prestep Types
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsBody.ts
Labels: enhancement, physics
