Repository BabylonJS/Babylon.js, pull requests merged in 2024-05, with the labels that each got.

#15055 Fix water material refraction
  packages/dev/materials/src/water/waterMaterial.ts
Labels: bug, materials

#15054 Add Neutral Tone Mapping
  packages/dev/core/src/Materials/Background/backgroundMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/imageProcessingConfiguration.defines.ts
  packages/dev/core/src/Materials/imageProcessingConfiguration.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/PostProcesses/imageProcessingPostProcess.ts
  packages/dev/core/src/Shaders/ShadersInclude/imageProcessingFunctions.fx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/postProcesses/defaultRenderingPipelinePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/scenePropertyGridComponent.tsx
  packages/dev/materials/src/water/waterMaterial.ts
Labels: enhancement, materials

#15056 Fix CleanURL override
  packages/dev/core/src/Misc/fileTools.ts
  packages/dev/core/src/Misc/tools.ts
Labels: bug

#15050 Adding new debug tools to the scene Inspector : copyCommandToClipboard & window.debugNode
  packages/dev/core/src/Audio/sound.ts
  packages/dev/core/src/Cameras/arcRotateCamera.ts
  packages/dev/core/src/Cameras/flyCamera.ts
  packages/dev/core/src/Cameras/followCamera.ts
  packages/dev/core/src/Cameras/freeCamera.ts
  packages/dev/core/src/Lights/directionalLight.ts
  packages/dev/core/src/Lights/hemisphericLight.ts
  packages/dev/core/src/Lights/pointLight.ts
  packages/dev/core/src/Lights/spotLight.ts
  packages/dev/core/src/Materials/imageProcessingConfiguration.ts
  packages/dev/core/src/Materials/materialPluginBase.ts
  packages/dev/core/src/Meshes/instancedMesh.ts
  packages/dev/core/src/Misc/typeStore.ts
  packages/dev/core/src/Particles/baseParticleSystem.ts
  packages/dev/core/src/abstractScene.ts
  packages/dev/core/src/scene.ts
  packages/dev/inspector/src/components/actionTabs/actionTabs.scss
  packages/dev/inspector/src/components/actionTabs/lines/quaternionLineComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/entities/sceneTreeItemComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/treeItemSelectableComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/treeNodeDebugger.ts
  packages/dev/sharedUiComponents/src/copyCommandToClipboard.ts
  packages/dev/sharedUiComponents/src/lines/checkBoxLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/colorLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/floatLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/optionsLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/sliderLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/vector3LineComponent.tsx
Labels: inspector, new feature

#15027 xrCompatible false per default, canvas made compatible on demand
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/XR/webXRManagedOutputCanvas.ts
Labels: breaking change

#15067 SSR: Fix in orthographic mode
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssrRenderingPipeline.ts
  packages/dev/core/src/Shaders/ShadersInclude/screenSpaceRayTrace.fx
  packages/dev/core/src/Shaders/screenSpaceReflection2.fragment.fx
Labels: bug, rendering engine

#15069 Quick Workaround on thin engine build issues
  packages/dev/core/src/Buffers/storageBuffer.ts
  packages/dev/core/src/Engines/Extensions/engine.externalTexture.ts
  packages/dev/core/src/Engines/Extensions/engine.storageBuffer.ts
  packages/dev/core/src/Engines/Extensions/engine.textureSampler.ts
  packages/dev/core/src/Engines/Extensions/index.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.externalTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.storageBuffer.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.textureSampler.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/index.ts
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
  packages/dev/core/src/Materials/Textures/htmlElementTexture.ts
  packages/dev/core/src/Materials/Textures/videoTexture.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Particles/computeShaderParticleSystem.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingTargetRenderer.ts
Labels: bug, build

#15070 WebGPU: Fix SSAO
  packages/dev/core/src/Shaders/ssao2.fragment.fx
Labels: bug, WebGPU

#15073 WebGPU: Fix this being undefined in some callbacks
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
  packages/dev/core/src/Materials/Textures/htmlElementTexture.ts
  packages/dev/core/src/Materials/Textures/videoTexture.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingTargetRenderer.ts
Labels: bug, WebGPU

#15080 Fixes for playground and sandbox
  packages/tools/playground/src/tools/monacoManager.ts
  packages/tools/sandbox/src/components/footer.tsx
Labels: skip changelog

#15091 Fluid renderer: Add compositeMode property
  packages/dev/core/src/Rendering/fluidRenderer/fluidRenderingTargetRenderer.ts
  packages/dev/core/src/Shaders/fluidRenderingRender.fragment.fx
Labels: enhancement, rendering engine

#15085 SSAO2: Don't clear post processes if not necessary
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssao2RenderingPipeline.ts
Labels: enhancement, post-process

#15074 Add visual test for two position vertex buffers pointing to same buffer
  packages/tools/tests/test/visualization/ReferenceImages/two-vertex-buffers.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15088 Sprites: Add logarithmic depth support
  packages/dev/core/src/Shaders/sprites.fragment.fx
  packages/dev/core/src/Shaders/sprites.vertex.fx
  packages/dev/core/src/Sprites/spriteManager.ts
  packages/dev/core/src/Sprites/spriteRenderer.ts
Labels: enhancement, sprite

#15089 Add directly constructed Nodes to rootNodes
  packages/dev/core/src/Bones/bone.ts
  packages/dev/core/src/Cameras/camera.ts
  packages/dev/core/src/Lights/light.ts
  packages/dev/core/src/Meshes/transformNode.ts
  packages/dev/core/src/node.ts
Labels: bug

#15095 Add comments for render loop code
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/engine.ts
Labels: skip changelog

#15096 Mesh: Fix convertToUnindexedMesh when stride is not equal to size
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug, rendering engine

#15099 Animation: Fix makeAdditiveAnimation
  packages/dev/core/src/Animations/animation.ts
Labels: bug, animations

#15102 Address comments
  packages/dev/core/src/Engines/constants.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/lightBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/frontFacingBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/biPlanarBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/conditionalBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/curveBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildState.ts
Labels: skip changelog

#15103 WebGPU: Fix disabling UA
  packages/dev/core/src/Shaders/ShadersInclude/shadowsFragmentFunctions.fx
  packages/dev/core/src/Shaders/fluidRenderingRender.fragment.fx
Labels: bug, WebGPU

#15097 GS and physics small fixes
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
Labels: bug

#15105 Shadows: Fix shadows in right-handed mode
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/tools/tests/test/visualization/ReferenceImages/shadows-rhs.png
  packages/tools/tests/test/visualization/config.json
Labels: bug, shadows

#15113 GS ratio
  packages/dev/core/src/Materials/GaussianSplatting/gaussianSplattingMaterial.ts
  packages/dev/core/src/Shaders/gaussianSplatting.vertex.fx
Labels: bug

#15118 BoundingBox: Fix doc for extendSize and extendSizeWorld
  packages/dev/core/src/Culling/boundingBox.ts
Labels: bug, rendering engine

#15115 _pointerDownEvent now reuses the _activeTouchIds slot if _pointerMove…
  packages/dev/core/src/DeviceInput/webDeviceInputSystem.ts
Labels: bug

#15122 Mesh: Fix bounding infos when calling convertToUnIndexedMesh
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug, rendering engine

#15120 Add WebDeviceInputSystem unit tests to cover pointermove before pointerdown cases
  packages/dev/core/src/Engines/nullEngine.ts
  packages/dev/core/test/unit/DeviceInput/babylon.webDeviceInputSystem.test.ts
Labels: tests

#15123 Nme webgpu3
  packages/dev/core/src/Materials/Node/Blocks/Vertex/lightInformationBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Vertex/morphTargetsBlock.ts
Labels: new feature

#15126 Animation: Use the right weight when calling RuntimeAnimation.goToFrame
  packages/dev/core/src/Animations/animatable.ts
  packages/dev/core/src/Animations/runtimeAnimation.ts
Labels: bug, animations

#15127 Add globalThis definitions to Draco modules
  packages/tools/babylonServer/public/draco_decoder.js
  packages/tools/babylonServer/public/draco_wasm_wrapper.js
  packages/tools/babylonServer/public/draco_wasm_wrapper_gltf.js
Labels: skip changelog

#14907 6Dof mesh flip fix for LH scene
  packages/dev/core/src/Behaviors/Meshes/sixDofDragBehavior.ts
Labels: bug, enhancement, physics, gizmos, stale

#15131 More nodes to support WebGPU
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/TBNBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/perturbNormalBlock.ts
  packages/dev/core/src/ShadersWGSL/ShadersInclude/bumpFragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/bumpFragmentFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/bumpFragmentMainFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/samplerFragmentDeclaration.fx
Labels: skip changelog

#15133 Nme webgpu5
  packages/dev/core/src/Materials/Node/Blocks/Fragment/heightToNormalBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/screenSizeBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/screenSpaceBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/biPlanarBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/cloudBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/triPlanarBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildState.ts
Labels: skip changelog

#15130 Fixes and enhancement on Havok & volumes
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsAggregate.ts
  packages/dev/core/src/Physics/v2/physicsBody.ts
Labels: bug, enhancement, physics

#15135 Fix Doc
  packages/dev/core/src/Morph/morphTargetManager.ts
Labels: skip changelog

#15137 WebGPU: Fix view support
  packages/dev/core/src/Engines/AbstractEngine/abstractEngine.views.ts
  packages/dev/core/src/Engines/AbstractEngine/index.ts
  packages/dev/core/src/Engines/Extensions/index.ts
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/engine.ts
Labels: bug, WebGPU

#15138 Fix ThinEngine compilation and abstract engine split
  packages/dev/core/src/Engines/AbstractEngine/abstractEngine.states.ts
  packages/dev/core/src/Engines/Extensions/engine.alpha.ts
  packages/dev/core/src/Engines/Extensions/engine.cubeTexture.ts
  packages/dev/core/src/Engines/Extensions/engine.dynamicBuffer.ts
  packages/dev/core/src/Engines/Extensions/engine.dynamicTexture.ts
  packages/dev/core/src/Engines/Extensions/engine.multiRender.ts
  packages/dev/core/src/Engines/Extensions/engine.prefilteredCubeTexture.ts
  packages/dev/core/src/Engines/Extensions/engine.rawTexture.ts
  packages/dev/core/src/Engines/Extensions/engine.readTexture.ts
  packages/dev/core/src/Engines/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/Extensions/engine.renderTargetCube.ts
  packages/dev/core/src/Engines/Extensions/engine.renderTargetTexture.ts
  packages/dev/core/src/Engines/Extensions/engine.videoTexture.ts
  packages/dev/core/src/Engines/Extensions/index.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.alpha.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.cubeTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.dynamicTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.multiRender.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.rawTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.readTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTargetCube.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTargetTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.videoTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/index.ts
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/engine.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/Textures/Filtering/hdrFiltering.ts
  packages/dev/core/src/Materials/Textures/Loaders/basisTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/ddsTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/ktxTextureLoader.ts
  packages/dev/core/src/Materials/Textures/baseTexture.ts
  packages/dev/core/src/Materials/Textures/cubeTexture.ts
  packages/dev/core/src/Materials/Textures/dynamicTexture.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/Materials/effect.ts
  packages/dev/core/src/Misc/dds.ts
  packages/dev/core/src/Misc/minMaxReducer.ts
  packages/dev/core/src/Misc/screenshotTools.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/Rendering/depthPeelingRenderer.ts
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/core/src/Rendering/prePassRenderer.ts
  packages/dev/serializers/src/glTF/2.0/glTFMaterialExporter.ts
Labels: skip changelog

#15143 NME FragmentOutputBlock: Fix deserialization
  packages/dev/core/src/Materials/Node/Blocks/Fragment/fragmentOutputBlock.ts
Labels: bug, nme

#15144 Lens flare: Fix off-centered flare in cases where the viewport is not full sized
  packages/dev/core/src/LensFlares/lensFlareSystem.ts
Labels: bug, rendering engine

#15147 GS BBox Sync, Collision notification fix
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
Labels: bug, physics, gizmos
