Repository BabylonJS/Babylon.js, pull requests merged in 2024-03, with the labels that each got.

#14824 New ThinParticleSystem
  packages/dev/core/src/Engines/Extensions/engine.rawTexture.ts
  packages/dev/core/src/Materials/imageProcessingConfiguration.ts
  packages/dev/core/src/Materials/materialHelper.ts
  packages/dev/core/src/Maths/math.color.ts
  packages/dev/core/src/Maths/math.scalar.functions.ts
  packages/dev/core/src/Maths/math.scalar.ts
  packages/dev/core/src/Maths/math.vector.ts
  packages/dev/core/src/Misc/tools.functions.ts
  packages/dev/core/src/Misc/tools.ts
  packages/dev/core/src/Particles/EmitterTypes/boxParticleEmitter.ts
  packages/dev/core/src/Particles/baseParticleSystem.ts
  packages/dev/core/src/Particles/gpuParticleSystem.ts
  packages/dev/core/src/Particles/particle.ts
  packages/dev/core/src/Particles/particleSystem.functions.ts
  packages/dev/core/src/Particles/particleSystem.ts
  packages/dev/core/src/Particles/thinParticleSystem.ts
Labels: modules, new feature

#14827 TargetCamera: Add Node Constructor code for TargetCamera
  packages/dev/core/src/Cameras/targetCamera.ts
Labels: bug, loaders

#14830 Fix #14823
  packages/dev/core/src/Meshes/Node/Blocks/Set/setColorsBlock.ts
  packages/dev/core/src/Meshes/mesh.vertexData.ts
Labels: skip changelog, nge

#14831 Fix #14822
  packages/dev/sharedUiComponents/src/lines/numericInputComponent.tsx
Labels: skip changelog

#14832 Mesh: Fix setPivotMatrix when cloning mesh
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug, rendering engine

#14833 ComputeShader: Allow DataBuffer to be passed for uniform / storage buffer
  packages/dev/core/src/Compute/computeShader.ts
  packages/dev/core/src/Engines/Extensions/engine.computeShader.ts
  packages/dev/core/src/Engines/WebGPU/webgpuComputeContext.ts
Labels: enhancement, rendering engine

#14235 Tensor: Standardize Vector2, Vector3, Vector4, Color3, Color4, Quaternion, and Matrix
  packages/dev/core/src/Bones/skeleton.ts
  packages/dev/core/src/Cameras/camera.ts
  packages/dev/core/src/Debug/directionalLightFrustumViewer.ts
  packages/dev/core/src/Engines/Native/nativePipelineContext.ts
  packages/dev/core/src/Engines/WebGL/webGLPipelineContext.ts
  packages/dev/core/src/Materials/uniformBuffer.ts
  packages/dev/core/src/Maths/math.color.ts
  packages/dev/core/src/Maths/math.like.ts
  packages/dev/core/src/Maths/math.plane.ts
  packages/dev/core/src/Maths/math.polar.ts
  packages/dev/core/src/Maths/math.vector.ts
  packages/dev/core/src/Maths/math.viewport.ts
  packages/dev/core/src/Maths/tensor.ts
  packages/dev/core/src/Misc/arrayTools.ts
  packages/dev/core/src/types.ts
  packages/dev/core/test/unit/Meshes/babylon.transformNode.test.ts
  packages/tools/tests/test/visualization/config.json
Labels: new feature

#14844 Fix vertexAlpha
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
Labels: skip changelog

#14838 Fix Scene sprites serialize/parse
  packages/dev/core/src/Loading/Plugins/babylonFileLoader.ts
  packages/dev/core/src/Loading/sceneLoader.ts
  packages/dev/core/src/Misc/sceneSerializer.ts
  packages/dev/core/src/Sprites/spriteManager.ts
  packages/dev/loaders/src/OBJ/objFileLoader.ts
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
  packages/dev/loaders/src/glTF/1.0/glTFLoader.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: enhancement, sprite

#14846 Associated with #14843
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTab.scss
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/genericNodePropertyComponent.tsx
Labels: skip changelog

#14845 Fix #14841
  packages/dev/core/src/Meshes/Node/Blocks/Set/setColorsBlock.ts
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTab.scss
Labels: skip changelog

#14849 AnimationGroup: Fix usage of mask
  packages/dev/core/src/Animations/animationGroup.ts
Labels: bug, animations

#14851 fix clone for ADT
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
Labels: bug

#14847 Baked Vertex Animations: allows you to pass a skeleton instead of a mesh
  packages/dev/core/src/BakedVertexAnimation/vertexAnimationBaker.ts
  packages/dev/core/src/Bones/skeleton.ts
Labels: enhancement, animations

#14853 Fix NME Preview loading with reflectionTexture
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
Labels: bug, nme

#14863 PLY stream offset fix
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
Labels: skip changelog

#14878 WebGPU: Fix vertex buffer creation when byte offset is not a multiple of 4
  packages/dev/core/src/Buffers/buffer.align.ts
  packages/dev/core/src/Engines/engineFeatures.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/nullEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: bug, WebGPU

#14880 Disable Physics Sync for static/kinematic bodies
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsBody.ts
Labels: enhancement, physics

#14881 Relax `AssetContainer` heirarchy check to allow `InstancedMesh` parents
  packages/dev/core/src/assetContainer.ts
Labels: bug

#14886 Mesh: Fix missing serialization for some properties
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug, rendering engine

#14868 fix cancel render loop
  packages/dev/core/src/Engines/engine.ts
  packages/dev/core/src/Engines/thinEngine.ts
Labels: bug, rendering engine

#14890 Posterize nge
  packages/dev/core/src/Materials/Node/Blocks/posterizeBlock.ts
  packages/dev/core/src/Maths/index.ts
  packages/dev/core/src/Maths/math.vector.functions.ts
  packages/dev/core/src/Meshes/Node/Blocks/debugBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryPosterizeBlock.ts
  packages/dev/sharedUiComponents/src/lines/textLineComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/debugNodePropertyComponent.tsx
Labels: nme, skip changelog, nge

#14891 Add edit icon for NG meshes
  packages/dev/inspector/src/components/sceneExplorer/entities/meshTreeItemComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/sceneExplorer.scss
Labels: skip changelog, nge

#14898 Fix #14896
  packages/dev/core/src/Meshes/Node/Blocks/geometryTrigonometryBlock.ts
Labels: bug, skip changelog

#14899 Removed int from Distance/dot/length
  packages/dev/core/src/Meshes/Node/Blocks/geometryDistanceBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryDotBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryLengthBlock.ts
Labels: bug, skip changelog

#14904 Global Illumination: small fixes to the GI code
  packages/dev/core/src/Rendering/GlobalIllumination/giRSMManager.ts
  packages/dev/core/src/Rendering/reflectiveShadowMap.ts
Labels: skip changelog

#14901 Thin instances: Automatic buffer recreation when static buffer changes
  packages/dev/core/src/Meshes/thinInstanceMesh.ts
Labels: enhancement, rendering engine

#14910 PBR: fix the "eho" debug mode
  packages/dev/core/src/Shaders/ShadersInclude/pbrDebug.fx
Labels: bug, materials

#14912 Fix matrix usage on pbr sheen roughness
  packages/dev/core/src/Shaders/pbr.vertex.fx
Labels: bug, materials

#14917 Fix PBR sub surface Dirty mecanism on textures
  packages/dev/core/src/Materials/PBR/pbrSubSurfaceConfiguration.ts
Labels: bug, materials

#14919 Fix PBR Sub Surface
  packages/dev/core/src/Materials/PBR/pbrSubSurfaceConfiguration.ts
Labels: bug, materials, skip changelog

#14922 WebGPU: Fix typo when declaring "highp sampler2DArray" in the NME
  packages/dev/core/src/Materials/Node/nodeMaterialBuildState.ts
Labels: bug, WebGPU

#14925 ReflectiveShadowMap: Fix typo in the "no ubo support" path
  packages/dev/core/src/Rendering/reflectiveShadowMap.ts
Labels: bug, rendering engine

#14933 Ported clearQuad to avoid using twgsl by default
  packages/dev/core/src/Engines/WebGPU/webgpuClearQuad.ts
  packages/dev/core/src/Shaders/clearQuad.fragment.fx
  packages/dev/core/src/Shaders/clearQuad.vertex.fx
  packages/dev/core/src/ShadersWGSL/clearQuad.fragment.fx
  packages/dev/core/src/ShadersWGSL/clearQuad.vertex.fx
Labels: WebGPU
