Repository BabylonJS/Babylon.js, pull requests merged in 2024-11, with the labels that each got.

#15757 Ensure pointerDown and pointerUp calls are paired
  packages/dev/core/src/Inputs/scene.inputManager.ts
Labels: bug

#15760 Glow layer: Fix crash when using vertex alpha in WebGPU
  packages/dev/core/src/ShadersWGSL/background.vertex.fx
  packages/dev/core/src/ShadersWGSL/glowMapGeneration.fragment.fx
  packages/dev/core/src/ShadersWGSL/glowMapGeneration.vertex.fx
  packages/tools/tests/test/visualization/ReferenceImages/Glow-layer-with-vertex-alpha.png
  packages/tools/tests/test/visualization/config.json
Labels: bug, WebGPU

#15764 update ngre back color
  packages/tools/nodeRenderGraphEditor/src/main.scss
Labels: skip changelog

#15766 Allow user to disable undo/redo for NGE
  packages/dev/sharedUiComponents/src/historyStack.ts
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTabComponent.tsx
  packages/tools/nodeGeometryEditor/src/globalState.ts
  packages/tools/nodeGeometryEditor/src/graphEditor.tsx
Labels: skip changelog

#15768 Fix various issues
  .build/config.json
  packages/dev/core/src/Materials/Node/Blocks/Input/inputBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
Labels: skip changelog

#15772 Allow both CSG in NGE
  .build/config.json
  packages/dev/core/src/Meshes/Node/Blocks/booleanGeometryBlock.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/automaticProperties.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/tools/nodeEditor/src/components/propertyTab/propertyTabComponent.tsx
Labels: skip changelog

#15774 Better float UI
  packages/dev/core/src/Materials/Node/Blocks/Fragment/fragmentOutputBlock.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
Labels: skip changelog

#15776 Collapsible nodes for node editors
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraph.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Meshes/Node/nodeGeometry.ts
  packages/dev/sharedUiComponents/src/imgs/dropdownArrowIcon_white.svg
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/interfaces/nodeLocationInfo.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.ts
  packages/tools/nodeEditor/src/serializationTools.ts
  packages/tools/nodeGeometryEditor/src/serializationTools.ts
  packages/tools/nodeRenderGraphEditor/src/serializationTools.ts
Labels: new feature

#15779 EffectWrapper: Fix backward compatibility for alpha mode
  packages/dev/core/src/Materials/effectRenderer.ts
Labels: bug, rendering engine

#15787 Fix #15786
  packages/dev/addons/src/htmlMesh/htmlMeshRenderer.ts
  packages/dev/core/src/PostProcesses/volumetricLightScatteringPostProcess.ts
  packages/dev/core/src/Shaders/volumetricLightScattering.fragment.fx
Labels: bug

#15791 Layer: Add support for linear colors
  packages/dev/core/src/Layers/layer.ts
  packages/dev/core/src/Shaders/layer.fragment.fx
  packages/dev/core/src/ShadersWGSL/layer.fragment.fx
Labels: enhancement, rendering engine

#15785 Frame Graph: Add TAA task + support for history textures
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/baseObjectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/objectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/taaObjectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/index.ts
  packages/dev/core/src/FrameGraph/Passes/renderPass.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/taaObjectRendererTask.ts
  packages/dev/core/src/FrameGraph/frameGraph.ts
  packages/dev/core/src/FrameGraph/frameGraphRenderContext.ts
  packages/dev/core/src/FrameGraph/frameGraphTask.ts
  packages/dev/core/src/FrameGraph/frameGraphTextureManager.ts
  packages/dev/core/src/FrameGraph/frameGraphTypes.ts
  packages/dev/core/src/FrameGraph/index.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/index.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/taaRenderingPipeline.ts
  packages/dev/core/src/PostProcesses/thinTAAPostProcess.ts
  packages/dev/core/src/ShadersWGSL/taa.fragment.fx
  packages/tools/nodeRenderGraphEditor/src/blockTools.ts
  packages/tools/nodeRenderGraphEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/components/preview/previewManager.ts
Labels: enhancement, rendering engine

#15778 GS WebGPU + NME ui fixes
  packages/dev/core/src/Materials/GaussianSplatting/gaussianSplattingMaterial.ts
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/gaussianBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/gaussianSplattingBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/index.ts
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/splatReaderBlock.ts
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/core/src/ShadersWGSL/ShadersInclude/gaussianSplatting.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/gaussianSplattingFragmentDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/gaussianSplattingUboDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/gaussianSplattingVertexDeclaration.fx
  packages/dev/core/src/ShadersWGSL/gaussianSplatting.fragment.fx
  packages/dev/core/src/ShadersWGSL/gaussianSplatting.vertex.fx
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
  packages/tools/nodeEditor/src/components/preview/previewType.ts
  packages/tools/nodeEditor/src/components/propertyTab/propertyTabComponent.tsx
Labels: enhancement, WebGPU

#15798 Adding support to mimetype autodetection
  packages/dev/core/src/Loading/sceneLoader.ts
  packages/dev/core/src/Misc/webRequest.fetch.ts
  packages/dev/loaders/src/glTF/glTFFileLoader.metadata.ts
  packages/tools/tests/test/visualization/config.json
  packages/tools/viewer/src/loader/modelLoader.ts
Labels: new feature, breaking change

#15805 Geometry buffer renderer: Fix normals not transformed by the world matrix when using normal maps
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/core/src/Shaders/geometry.vertex.fx
  packages/dev/core/src/ShadersWGSL/geometry.vertex.fx
Labels: bug, rendering engine

#15818 Animations goToFrame: Fix breaking change introduced in #15126
  packages/dev/core/src/Animations/animatable.core.ts
  packages/dev/core/src/Animations/animationGroup.ts
Labels: bug, animations

#15829 Fix Hotspot normal computation//add missing gizmo dispose
  packages/dev/core/src/Gizmos/positionGizmo.ts
  packages/dev/core/src/Gizmos/rotationGizmo.ts
  packages/dev/core/src/Meshes/abstractMesh.hotSpot.ts
Labels: skip changelog

#15830 WebGPU: Add occlusion query module to the core WebGPU engine
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.query.ts
  packages/dev/core/src/Engines/thinWebGPUEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: skip changelog

#15821 Extract ObjectRenderer from RenderTargetTexture
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/baseObjectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/geometryRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/objectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/taaObjectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/geometryRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/objectRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/taaObjectRendererTask.ts
  packages/dev/core/src/FrameGraph/frameGraphRenderContext.ts
  packages/dev/core/src/Materials/Textures/multiRenderTarget.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/Rendering/index.ts
  packages/dev/core/src/Rendering/objectRenderer.ts
  packages/tools/nodeRenderGraphEditor/src/components/preview/previewManager.ts
Labels: enhancement, rendering engine

#15831 WebGPU: Fix crash when using sub-surface scattering
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockPrePass.fx
Labels: bug, WebGPU

#15832 PBR material: Fix isScatteringEnabled switch not working as expected
  packages/dev/core/src/Materials/PBR/pbrSubSurfaceConfiguration.ts
Labels: bug, materials

#15840 GPUPicker: Fix class doc
  packages/dev/core/src/Collisions/gpuPicker.ts
Labels: skip changelog

#15847 Move tags to all entities
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGridTabComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/commonPropertyGridComponent.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.module.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
Labels: skip changelog

#15848 Goal of this PR is to make sure we raise the onNewXXX when the entity…
  packages/dev/core/src/scene.ts
Labels: bug

#15852 Split container - Remove dependencies on split.js
  packages/dev/sharedUiComponents/src/split/splitContainer.module.scss
  packages/dev/sharedUiComponents/src/split/splitContainer.tsx
  packages/dev/sharedUiComponents/src/split/splitContext.ts
  packages/dev/sharedUiComponents/src/split/splitter.tsx
  packages/tools/nodeEditor/src/components/log/log.scss
  packages/tools/nodeEditor/src/components/preview/previewAreaComponent.tsx
  packages/tools/nodeEditor/src/graphEditor.tsx
  packages/tools/nodeEditor/src/main.scss
  packages/tools/nodeGeometryEditor/src/components/log/log.scss
  packages/tools/nodeGeometryEditor/src/components/preview/previewAreaComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphEditor.tsx
  packages/tools/nodeGeometryEditor/src/main.scss
  packages/tools/nodeRenderGraphEditor/src/components/log/log.scss
  packages/tools/nodeRenderGraphEditor/src/components/preview/previewAreaComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/graphEditor.tsx
  packages/tools/nodeRenderGraphEditor/src/main.scss
  packages/tools/playground/package.json
  packages/tools/playground/src/components/monacoComponent.tsx
  packages/tools/playground/src/custom.d.ts
  packages/tools/playground/src/playground.tsx
  packages/tools/playground/src/scss/header.scss
  packages/tools/playground/src/scss/main.scss
  packages/tools/playground/webpack.config.js
Labels: skip changelog

#15854 Switch to Manifold 3.0
  packages/dev/core/src/Meshes/csg2.ts
Labels: skip changelog

#15844 PointerDragBehavior: Support all dragAxis
  packages/dev/core/src/Behaviors/Meshes/pointerDragBehavior.ts
Labels: bug

#15855 Better style and popup management for editors
  packages/dev/inspector/src/components/popupComponent.tsx
  packages/dev/inspector/src/inspector.ts
  packages/dev/sharedUiComponents/src/lines/popup.ts
  packages/dev/sharedUiComponents/src/popupHelper.ts
  packages/dev/sharedUiComponents/src/styleHelper.ts
  packages/tools/guiEditor/src/components/propertyTab/propertyGrids/gui/commonControlPropertyGridComponent.tsx
  packages/tools/guiEditor/src/guiEditor.ts
  packages/tools/guiEditor/src/workbenchEditor.tsx
  packages/tools/nodeEditor/src/graphEditor.tsx
  packages/tools/nodeEditor/src/nodeEditor.ts
  packages/tools/nodeEditor/src/sharedComponents/popup.tsx
  packages/tools/nodeGeometryEditor/src/graphEditor.tsx
  packages/tools/nodeGeometryEditor/src/nodeGeometryEditor.ts
  packages/tools/nodeGeometryEditor/src/sharedComponents/popup.tsx
  packages/tools/nodeRenderGraphEditor/src/graphEditor.tsx
  packages/tools/nodeRenderGraphEditor/src/nodeRenderGraphEditor.ts
  packages/tools/nodeRenderGraphEditor/src/sharedComponents/popup.tsx
  packages/tools/vsm/src/vsm.ts
Labels: skip changelog

#15859 PostProcess: fix shader imports not being ready in ES6
  packages/dev/core/src/PostProcesses/postProcess.ts
Labels: bug, post-process

#15866 Clipping for GridMaterial
  packages/dev/materials/src/grid/grid.fragment.fx
  packages/dev/materials/src/grid/grid.vertex.fx
  packages/dev/materials/src/grid/gridMaterial.ts
Labels: enhancement

#15887 New visual clue for type conversions
  packages/dev/core/src/Materials/Node/Blocks/Fragment/fragmentOutputBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlock.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodeLink.ts
Labels: new feature

#15891 Solve preview height issue
  packages/tools/nodeEditor/src/graphEditor.tsx
  packages/tools/nodeEditor/src/main.scss
  packages/tools/nodeGeometryEditor/src/graphEditor.tsx
  packages/tools/nodeGeometryEditor/src/main.scss
  packages/tools/nodeRenderGraphEditor/src/graphEditor.tsx
  packages/tools/nodeRenderGraphEditor/src/main.scss
Labels: bug

#15890 Allow node editors to let the properties be injected onto the nodes
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraphBlockConnectionPoint.ts
  packages/dev/core/src/Materials/Node/Blocks/conditionalBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlockConnectionPoint.ts
  packages/dev/core/src/Meshes/Node/Blocks/Matrices/rotationXBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Matrices/rotationYBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Matrices/rotationZBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Set/latticeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/conditionBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryClampBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryLerpBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryNLerpBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryReplaceColorBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryRotate2dBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometrySmoothStepBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/geometryStepBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometry.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlockConnectionPoint.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/common.module.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.module.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/interfaces/portData.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.module.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/tools.ts
  packages/tools/nodeGeometryEditor/src/graphEditor.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/connectionPointPortData.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/genericNodePropertyComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/registerDefaultInput.ts
Labels: new feature

#15896 WebGPU: Fix crash when using depth bias with line and point topology
  packages/dev/core/src/Engines/WebGPU/webgpuCacheRenderPipeline.ts
Labels: bug, WebGPU

#15888 MSAA render targets: Resolve the depth texture (if any) and allow for manual resolve
  packages/dev/core/src/Engines/Extensions/engine.multiRender.ts
  packages/dev/core/src/Engines/WebGL/webGLRenderTargetWrapper.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.multiRender.ts
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/renderTargetWrapper.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: rendering engine, new feature

#15874 Frame graph: refactor to use InternalTexture instead of RenderTargetWrapper + misc changes
  packages/dev/core/src/Engines/Extensions/engine.multiRender.ts
  packages/dev/core/src/Engines/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/WebGL/webGLRenderTargetWrapper.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.multiRender.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/WebGPU/webgpuHardwareTexture.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureManager.ts
  packages/dev/core/src/Engines/renderTargetWrapper.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/thinWebGPUEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/clearBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/inputBlock.ts
  packages/dev/core/src/FrameGraph/Passes/renderPass.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/bloomTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldMergeTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/postProcessTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/cullObjectsTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/geometryRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/objectRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/taaObjectRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Texture/clearTextureTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Texture/copyToTextureTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Texture/generateMipMapsTask.ts
  packages/dev/core/src/FrameGraph/frameGraph.ts
  packages/dev/core/src/FrameGraph/frameGraphRenderContext.ts
  packages/dev/core/src/FrameGraph/frameGraphRenderTarget.ts
  packages/dev/core/src/FrameGraph/frameGraphTask.ts
  packages/dev/core/src/FrameGraph/frameGraphTextureManager.ts
  packages/dev/core/src/FrameGraph/frameGraphTypes.ts
  packages/dev/core/src/FrameGraph/index.ts
  packages/dev/core/src/Materials/Textures/internalTexture.ts
  packages/dev/core/src/Materials/Textures/multiRenderTarget.ts
  packages/dev/core/src/Materials/Textures/textureCreationOptions.ts
  packages/dev/gui/src/2D/FrameGraph/guiTask.ts
  packages/tools/nodeRenderGraphEditor/src/graphEditor.tsx
  packages/tools/nodeRenderGraphEditor/src/graphSystem/properties/inputNodePropertyComponent.tsx
Labels: enhancement, rendering engine

#15906 Snapshot rendering helper: add support for gaussian splatting meshes
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/core/src/Misc/snapshotRenderingHelper.ts
Labels: enhancement, rendering engine, WebGPU

#15907 Fix grad
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodeLink.ts
Labels: skip changelog

#15909 Fix deref being GCed too early
  packages/dev/core/src/Misc/observable.ts
Labels: bug, skip changelog

#15910 Fix disposing of effects for submeshes
  .build/config.json
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Materials/drawWrapper.ts
  packages/dev/core/src/Materials/effect.ts
  packages/dev/core/src/Meshes/abstractMesh.ts
  packages/dev/core/src/Meshes/subMesh.ts
Labels: skip changelog

#15912 WebGPU: fix OIT
  packages/dev/core/src/Meshes/linesMesh.ts
  packages/dev/core/src/ShadersWGSL/ShadersInclude/oitFragment.fx
  packages/tools/tests/test/visualization/ReferenceImages/LineEdgesRenderer.png
Labels: bug, rendering engine, WebGPU

#15915 WebGL1: Fix test
  packages/tools/tests/test/visualization/ReferenceImages/LineEdgesRenderer.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog
