Repository BabylonJS/Babylon.js, pull requests merged in 2024-09, with the labels that each got.

#15502 [GUI] Fit texture scale to slate dimensions
  packages/dev/gui/src/3D/controls/contentDisplay3D.ts
  packages/dev/gui/src/3D/controls/control3D.ts
  packages/dev/gui/src/3D/controls/holographicSlate.ts
Labels: new feature

#15501 PLY Pointcloud
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: skip changelog

#15508 WebGL: Fix MSAA depth/stencil textures not working
  packages/dev/core/src/Engines/Extensions/engine.cubeTexture.ts
  packages/dev/core/src/Engines/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.cubeTexture.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/renderTargetWrapper.ts
  packages/dev/core/src/Engines/thinEngine.ts
Labels: bug, rendering engine

#15510 Fix memory leak following WebGPU migration
  packages/dev/core/src/Meshes/meshUVSpaceRenderer.ts
  packages/dev/core/src/Sprites/spriteRenderer.ts
Labels: skip changelog

#15514 TAA rendering pipeline: Fix ghosting issues at start
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/taaRenderingPipeline.ts
Labels: bug, rendering engine

#15517 SEO baby
  packages/tools/nodeEditor/public/index.html
  packages/tools/nodeGeometryEditor/public/index.html
  packages/tools/playground/public/debug.html
  packages/tools/playground/public/frame.html
  packages/tools/playground/public/full.html
  packages/tools/playground/public/index.html
  packages/tools/sandbox/public/index.html
Labels: skip changelog

#15522 Fix #15518
  packages/dev/inspector/src/components/actionTabs/lines/textureLinkLineComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/texturePropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/textures/propertiesBar.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/particleSystemPropertyGridComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/properties/texturePropertyTabComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/textureNodePropertyComponent.tsx
Labels: skip changelog

#15516 UniformBuffer: Add setTextureArray to uniform buffers
  packages/dev/core/src/Materials/uniformBuffer.ts
Labels: enhancement, materials

#15523 Fix layer position issue when reloading
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
Labels: skip changelog

#15524 Fix error handling with NME
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildStateSharedData.ts
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
  packages/tools/nodeEditor/src/globalState.ts
  packages/tools/nodeEditor/src/graphEditor.tsx
Labels: skip changelog

#15526 Use `Sound.play` `offset` arg for sounds with `streaming` set to `true`
  packages/dev/core/src/Audio/sound.ts
Labels: bug

#15528 Babylon native #395
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15533 Dispose sound HTMLAudioElement and streaming source node
  packages/dev/core/src/Audio/sound.ts
Labels: bug

#15543 Reduce render count use
  .vscode/launch.json
  packages/tools/tests/test/visualization/ReferenceImages/decal-map-pp.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15547 go away flaky test
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15546 Add undo / redo support to NME
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/tools/nodeEditor/src/components/propertyTab/propertyTabComponent.tsx
  packages/tools/nodeEditor/src/globalState.ts
  packages/tools/nodeEditor/src/graphEditor.tsx
  packages/tools/nodeEditor/src/historyStack.ts
  packages/tools/nodeEditor/src/serializationTools.ts
Labels: new feature, nme

#15521 IBL shadows to WebGPU
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
  packages/dev/core/src/Engines/engineCapabilities.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/nullEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/Textures/Filtering/hdrFiltering.ts
  packages/dev/core/src/Materials/Textures/Procedurals/proceduralTexture.ts
  packages/dev/core/src/Materials/Textures/index.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/postProcessRenderPipeline.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
  packages/dev/core/src/Rendering/IBLShadows/iblShadowsAccumulationPass.ts
  packages/dev/core/src/Rendering/IBLShadows/iblShadowsImportanceSamplingRenderer.ts
  packages/dev/core/src/Rendering/IBLShadows/iblShadowsRenderPipeline.ts
  packages/dev/core/src/Rendering/IBLShadows/iblShadowsSpatialBlurPass.ts
  packages/dev/core/src/Rendering/IBLShadows/iblShadowsVoxelRenderer.ts
  packages/dev/core/src/Rendering/IBLShadows/iblShadowsVoxelTracingPass.ts
  packages/dev/core/src/Rendering/index.ts
  packages/dev/core/src/Shaders/iblCombineVoxelGrids.fragment.fx
  packages/dev/core/src/Shaders/iblGenerateVoxelMip.fragment.fx
  packages/dev/core/src/Shaders/iblShadowsImportanceSamplingDebug.fragment.fx
  packages/dev/core/src/Shaders/iblVoxelGrid.fragment.fx
  packages/dev/core/src/Shaders/iblVoxelGrid.vertex.fx
  packages/dev/core/src/Shaders/iblVoxelGrid2dArrayDebug.fragment.fx
  packages/dev/core/src/Shaders/iblVoxelGrid3dDebug.fragment.fx
  packages/dev/core/src/Shaders/iblVoxelSlabDebug.fragment.fx
  packages/dev/core/src/Shaders/iblVoxelSlabDebug.vertex.fx
  packages/dev/core/src/ShadersWGSL/copyTexture3DLayerToTexture.fragment.fx
  packages/dev/core/src/ShadersWGSL/default.fragment.fx
  packages/dev/core/src/ShadersWGSL/hdrFiltering.fragment.fx
  packages/dev/core/src/ShadersWGSL/hdrFiltering.vertex.fx
  packages/dev/core/src/ShadersWGSL/iblCombineVoxelGrids.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblGenerateVoxelMip.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblShadowAccumulation.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblShadowDebug.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblShadowGBufferDebug.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblShadowSpatialBlur.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblShadowVoxelTracing.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblShadowsCdfx.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblShadowsCdfy.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblShadowsCombine.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblShadowsIcdfx.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblShadowsIcdfy.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblShadowsImportanceSamplingDebug.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblVoxelGrid.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblVoxelGrid.vertex.fx
  packages/dev/core/src/ShadersWGSL/iblVoxelGrid2dArrayDebug.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblVoxelGrid3dDebug.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblVoxelSlabDebug.fragment.fx
  packages/dev/core/src/ShadersWGSL/iblVoxelSlabDebug.vertex.fx
  packages/dev/core/src/ShadersWGSL/pbr.fragment.fx
  packages/dev/core/src/ShadersWGSL/procedural.vertex.fx
Labels: skip changelog

#15552 Fix replacement issue when webGPU
  packages/dev/core/src/Materials/Node/Blocks/Dual/lightBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/ShadersWGSL/ShadersInclude/lightFragment.fx
Labels: skip changelog

#15562 Fix PowBlock for WebGPU
  packages/dev/core/src/Materials/Node/Blocks/Vertex/lightInformationBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/powBlock.ts
Labels: bug

#15561 Removing zip, using delta and externalizing the class
  packages/dev/core/src/Materials/Node/nodeMaterialBlockConnectionPoint.ts
  packages/dev/sharedUiComponents/src/historyStack.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/tools/nodeEditor/package.json
  packages/tools/nodeEditor/src/graphEditor.tsx
  packages/tools/nodeEditor/src/historyStack.ts
Labels: skip changelog

#15565 Fix issue with base
  packages/dev/sharedUiComponents/src/historyStack.ts
Labels: skip changelog

#15567 Mesh: Don't delete sub-meshes when calling flipFaces
  packages/dev/core/src/Meshes/geometry.ts
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug, rendering engine

#15568 Fix wrong adjusted coordinates
  packages/dev/core/src/Collisions/gpuPicker.ts
Labels: skip changelog

#15566 PBR: Fix wrong parameter passed to clearcoat
  packages/dev/core/src/Materials/Node/Blocks/PBR/clearCoatBlock.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockClearcoat.fx
  packages/dev/core/src/Shaders/pbr.fragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockClearcoat.fx
  packages/dev/core/src/ShadersWGSL/pbr.fragment.fx
Labels: bug, materials

#15574 NodeMaterial: Fixes for prepass support
  packages/dev/core/src/Materials/Node/Blocks/Fragment/prePassOutputBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Input/prePassTextureBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Rendering/prePassRenderer.ts
Labels: bug, materials

#15575 Fix gpu picking leak
  packages/dev/core/src/Collisions/gpuPicker.ts
Labels: skip changelog

#15571 Fix color space nme
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/loaders/test/integration/babylon.sceneLoader.test.ts
Labels: bug

#15577 Dynamic update of GS
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
Labels: enhancement

#15590 Better stack management
  packages/dev/sharedUiComponents/src/historyStack.ts
Labels: skip changelog

#15592 Adding Undo / Redo to NGE
  packages/dev/sharedUiComponents/src/historyStack.ts
  packages/tools/nodeEditor/src/graphEditor.tsx
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTabComponent.tsx
  packages/tools/nodeGeometryEditor/src/globalState.ts
  packages/tools/nodeGeometryEditor/src/graphEditor.tsx
Labels: new feature

#15594 Add support for color space convertion node for NME
  packages/dev/core/src/Materials/Node/Blocks/colorConverterBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/index.ts
  packages/tools/nodeEditor/src/blockTools.ts
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
Labels: new feature

#15596 Fix splat increase when updating GS data
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
Labels: skip changelog

#15601 Add focus mode for frames
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphFrame.modules.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphFrame.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodeLink.ts
Labels: new feature, nme

#15599 Introducing loop support for NME
  packages/dev/core/src/Materials/Node/Blocks/Dual/imageSourceBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/index.ts
  packages/dev/core/src/Materials/Node/Blocks/loopBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/storageReadBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/storageWriteBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlockConnectionPoint.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildState.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphFrame.ts
  packages/tools/nodeEditor/src/blockTools.ts
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/display/loopDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/registerToDisplayLedger.ts
Labels: new feature

#15604 Adding test for NME loop
  packages/tools/tests/test/visualization/ReferenceImages/nme-loop.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15605 Fix side detection (copy paste error)
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
Labels: skip changelog

#15613 Fix HeightToNormal block
  packages/dev/core/src/Materials/Node/Blocks/Fragment/heightToNormalBlock.ts
Labels: bug

#15612 Fix issue when sprite texture was modified during animation
  .build/config.json
  packages/dev/core/src/Sprites/spriteRenderer.ts
Labels: bug

#15619 Moving BabylonFileParser out of the scene
  packages/dev/core/src/Audio/audioSceneComponent.ts
  packages/dev/core/src/Layers/effectLayerSceneComponent.ts
  packages/dev/core/src/LensFlares/lensFlareSystemSceneComponent.ts
  packages/dev/core/src/Lights/Shadows/shadowGeneratorSceneComponent.ts
  packages/dev/core/src/Loading/Plugins/babylonFileLoader.ts
  packages/dev/core/src/Loading/Plugins/babylonFileParser.function.ts
  packages/dev/core/src/Loading/Plugins/index.ts
  packages/dev/core/src/Particles/particleSystemComponent.ts
  packages/dev/core/src/Rendering/subSurfaceSceneComponent.ts
  packages/dev/core/src/abstractScene.ts
Labels: breaking change

#15622 Material: Fix wireframe mode for unindexed meshes
  packages/dev/core/src/Meshes/mesh.ts
Labels: bug, materials

#15625 DecalMap: Fix no uv when using decalmap and no other textures
  packages/dev/core/src/Materials/material.decalMapConfiguration.ts
Labels: bug, materials

#15629 Fix customMaterial waiting for shaders to be loaded
  packages/dev/materials/src/custom/customMaterial.ts
  packages/dev/materials/src/custom/pbrCustomMaterial.ts
Labels: bug

#15631 Fix missing import for Screenshots
  packages/dev/core/src/Misc/screenshotTools.ts
Labels: bug

#15626 Inspector: Fix texture preview in WebGPU
  packages/dev/core/src/Misc/index.ts
  packages/dev/core/src/Misc/textureTools.ts
  packages/dev/core/src/Shaders/lod.fragment.fx
  packages/dev/core/src/Shaders/lodCube.fragment.fx
  packages/dev/core/src/ShadersWGSL/lod.fragment.fx
  packages/dev/core/src/ShadersWGSL/lodCube.fragment.fx
Labels: bug, inspector

#15630 Add subdivisions for PlaneBlock
  packages/dev/core/src/Meshes/Builders/groundBuilder.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/planeBlock.ts
Labels: new feature

#15632 Fix wacky test
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#15640 Decal: Misc fixes for decal management
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Meshes/meshUVSpaceRenderer.ts
Labels: bug, materials

#15633 WebGPU: fixed incorrect snapshot mode when reset is called while snapshot recording is active
  packages/dev/core/src/Engines/WebGPU/webgpuSnapshotRendering.ts
Labels: bug, WebGPU

#15647 Camera: Add warnings about re-entrance in onViewMatrixChanged observables
  packages/dev/core/src/Cameras/camera.ts
Labels: enhancement, documentation

#15403 Sandbox error msg for unhanled errors
  packages/dev/loaders/src/OBJ/solidParser.ts
  packages/tools/sandbox/src/components/footer.tsx
  packages/tools/sandbox/src/components/renderingZone.tsx
  packages/tools/sandbox/src/sandbox.tsx
  packages/tools/sandbox/src/scss/main.scss
Labels: stale

#15652 Fix #15642
  packages/dev/core/src/Meshes/Node/Blocks/geometryOptimizeBlock.ts
Labels: nge

#15654 Fix #15653
  packages/dev/core/src/Meshes/Node/Blocks/Set/setPositionsBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/nullBlock.ts
Labels: nge
