Repository BabylonJS/Babylon.js, pull requests merged in 2024-04, with the labels that each got.

#14932 Allow CreateFromBase64String and LoadFromDataString to specifiy exten…
  packages/dev/core/src/Materials/Textures/texture.ts
Labels: enhancement, new feature

#14938 PBR: Fix crash when using refraction
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockSubSurface.fx
Labels: bug, materials

#14937 PBR materials: Add ambient occlusion color to debug mode
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrDebug.fx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/pbrMaterialPropertyGridComponent.tsx
Labels: enhancement, materials

#14857 Make NME and NGE math blocks agnostic to order of operations and left vs. right input
  packages/dev/core/src/Materials/Node/Blocks/addBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/baseMathBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/divideBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/multiplyBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/subtractBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlockConnectionPoint.ts
  packages/dev/core/src/Meshes/Node/Blocks/mathBlock.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlockConnectionPoint.ts
Labels: new feature

#13370 EXT_texture_avif implementation
  packages/dev/inspector/src/components/actionTabs/tabs/tools/gltfComponent.tsx
  packages/dev/inspector/src/components/globalState.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/EXT_texture_avif.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/index.ts
  packages/dev/serializers/src/glTF/2.0/glTFMaterialExporter.ts
  packages/public/glTF2Interface/babylon.glTF2Interface.d.ts
Labels: loaders, glTF, new feature, stale

#14944 WebGPU: Add support for the predeclared alias in WGSL
  packages/dev/core/src/Engines/WebGPU/webgpuClearQuad.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessor.ts
  packages/dev/core/src/Engines/WebGPU/webgpuShaderProcessorsWGSL.ts
Labels: bug, WebGPU

#14946 Slider3D: Add getters for internal meshes
  packages/dev/gui/src/3D/controls/slider3D.ts
Labels: enhancement, gui

#14948 Remove render count from some visual tests
  packages/tools/tests/test/visualization/ReferenceImages/scissor-test-2.png
  packages/tools/tests/test/visualization/ReferenceImages/scissor-test-3.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#14953 Baked Vertex Animations: Add shadow support
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
Labels: enhancement, rendering engine

#14952 ComputeEffect: Implement onError callback
  packages/dev/core/src/Compute/computeEffect.ts
  packages/dev/core/src/Engines/Extensions/engine.computeShader.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.computeShader.ts
  packages/dev/core/src/Engines/WebGPU/webgpuComputePipelineContext.ts
Labels: bug, rendering engine

#14954 Fix Matrix.multiplyByFloats and Vector3.Project in WebGPU
  packages/dev/core/src/Maths/math.vector.ts
Labels: bug, math

#14955 ComputeShader: follow up to #14952
  packages/dev/core/src/Compute/computeEffect.ts
  packages/dev/core/src/Engines/Extensions/engine.computeShader.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.computeShader.ts
Labels: skip changelog

#14958 Fix scale gizmo isHovered flag
  packages/dev/core/src/Gizmos/axisScaleGizmo.ts
  packages/dev/core/src/Gizmos/scaleGizmo.ts
Labels: bug, gizmos

#14959 WebGPU: fix when depth texture is 2DArray
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureManager.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Lights/Shadows/cascadedShadowGenerator.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
Labels: bug, WebGPU

#14962 fix releaseDrag for bbox gizmo
  packages/dev/core/src/Gizmos/boundingBoxGizmo.ts
Labels: bug, gizmos

#14964 Fix khr-animation-pointer with uv transforms
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_animation_pointer.data.ts
Labels: bug, glTF

#14972 Physics Angular Impulse + Misc
  packages/dev/core/src/Physics/v2/IPhysicsEnginePlugin.ts
  packages/dev/core/src/Physics/v2/Plugins/havokPlugin.ts
  packages/dev/core/src/Physics/v2/physicsBody.ts
  packages/dev/core/src/Physics/v2/physicsEngineComponent.ts
Labels: bug, enhancement, physics

#14974 Set the XR camera's fov
  packages/dev/core/src/XR/webXRCamera.ts
Labels: new feature

#14977 FIX PBR Sub surface configuration
  packages/dev/core/src/Materials/Node/Blocks/PBR/subSurfaceBlock.ts
  packages/dev/core/src/Materials/PBR/pbrSubSurfaceConfiguration.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockSubSurface.fx
Labels: bug, materials

#14985 Fix NME MatrixTransposeBlock
  packages/dev/core/src/Materials/Node/Blocks/matrixTransposeBlock.ts
Labels: bug, nme

#14993 Fix particle cell ID computation
  packages/dev/core/src/Particles/particle.ts
Labels: bug

#14970 Add compute dispatch indirect API
  packages/dev/core/src/Compute/computeShader.ts
  packages/dev/core/src/Engines/Extensions/engine.computeShader.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.computeShader.ts
Labels: new feature, WebGPU

#14994 Fix #14992
  packages/dev/core/src/Animations/runtimeAnimation.ts
Labels: bug

#14987 BoneLookController: Fix bone scaling being lost
  packages/dev/core/src/Bones/boneLookController.ts
Labels: bug, bones

#14998 Fix void checks in Geometry Buffers
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
Labels: bug, post-process

#14999 Fix sandbox
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Misc/filesInput.ts
  packages/dev/core/src/Misc/screenshotTools.ts
  packages/tools/sandbox/src/components/renderingZone.tsx
Labels: skip changelog

#15005 Fix unpack for webgpu
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: skip changelog

#15007 Fix adding child nodes to the html twin tree
  packages/tools/accessibility/src/HtmlTwin/htmlTwinItemAdapter.tsx
Labels: bug, accessibility

#15011 Fix #15006
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/particleSystemPropertyGridComponent.tsx
Labels: skip changelog

#15012 WebGPU: Fix equirectangular cube textures
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.rawTexture.ts
  packages/dev/core/src/Engines/WebGPU/webgpuHardwareTexture.ts
  packages/dev/core/src/Materials/Textures/equiRectangularCubeTexture.ts
Labels: bug, WebGPU

#15013 Playground: Fix missing override keyword
  packages/tools/playground/src/components/commandBarComponent.tsx
  packages/tools/playground/src/components/commandButtonComponent.tsx
  packages/tools/playground/src/components/commandDropdownComponent.tsx
  packages/tools/playground/src/components/errorDisplayComponent.tsx
  packages/tools/playground/src/components/examplesComponent.tsx
  packages/tools/playground/src/components/footerComponent.tsx
  packages/tools/playground/src/components/hamburgerMenu.tsx
  packages/tools/playground/src/components/headerComponent.tsx
  packages/tools/playground/src/components/metadataComponent.tsx
  packages/tools/playground/src/components/monacoComponent.tsx
  packages/tools/playground/src/components/qrCodeComponent.tsx
  packages/tools/playground/src/components/rendererComponent.tsx
  packages/tools/playground/src/components/waitRingComponent.tsx
  packages/tools/playground/src/playground.tsx
Labels: skip changelog

#15014 WebGPU: Fix onResize not triggered on the engine
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/engine.ts
Labels: bug, WebGPU

#15019 NME: Fix wrong type casting for TextureBlock output
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
Labels: bug, nme

#15020 NME: Fix sampler name in TextureBlock
  packages/dev/core/src/Materials/Node/Blocks/Dual/textureBlock.ts
Labels: bug, nme

#15033 Final fix for allowCanvas
  packages/dev/gui/src/2D/controls/control.ts
Labels: skip changelog

#15034 Mesh debug material plugin: Fix crash when showing uvs
  packages/dev/core/src/Materials/meshDebugPluginMaterial.ts
Labels: bug, rendering engine

#15037 Inspector: Move shader code to core
  packages/dev/core/src/Misc/textureTools.ts
  packages/dev/core/src/Shaders/lod.fragment.fx
  packages/dev/core/src/Shaders/lodCube.fragment.fx
  packages/dev/inspector/src/textureHelper.ts
Labels: bug, inspector

#15038 Allow defines the shader name that appears in spector.
  packages/dev/core/src/Materials/effect.ts
Labels: enhancement, rendering engine

#15041 AA in sandbox
  packages/tools/sandbox/src/components/renderingZone.tsx
Labels: enhancement, sandbox

#15043 Fix mod
  packages/dev/core/src/Materials/Node/Blocks/modBlock.ts
Labels: skip changelog

#15044 Fix node port export
  packages/dev/core/src/Meshes/Node/nodeGeometryBlockConnectionPoint.ts
Labels: skip changelog

#15048 Fix edge renderer
  packages/dev/core/src/Rendering/renderingGroup.ts
Labels: skip changelog
