Repository BabylonJS/Babylon.js, pull requests merged in 2025-03, with the labels that each got.

#16238 WebGPU: Fix crash when processing a env cube
  packages/dev/core/src/Engines/WebGPU/webgpuTextureManager.ts
  packages/dev/core/src/Misc/environmentTextureTools.ts
Labels: bug, WebGPU

#16240 WebGPU: Fix crash in fast snapshot rendering mode
  packages/dev/core/src/scene.ts
Labels: bug, WebGPU

#16243 Effect layers: Fix effect layers readiness check
  packages/dev/core/src/Layers/effectLayer.ts
  packages/dev/core/src/scene.ts
Labels: bug, rendering engine

#16244 Material: Fix scene ubo still bound to material effect after material is unbound
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/scene.ts
Labels: bug, materials

#16237 Fix USDZ export of instances
  packages/dev/core/src/Meshes/instancedMesh.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: bug

#15839 Add audio engine v2
  packages/dev/core/src/AudioV2/abstractAudio/abstractAudioBus.ts
  packages/dev/core/src/AudioV2/abstractAudio/abstractAudioNode.ts
  packages/dev/core/src/AudioV2/abstractAudio/abstractSound.ts
  packages/dev/core/src/AudioV2/abstractAudio/abstractSoundInstance.ts
  packages/dev/core/src/AudioV2/abstractAudio/audioBus.ts
  packages/dev/core/src/AudioV2/abstractAudio/audioEngineV2.ts
  packages/dev/core/src/AudioV2/abstractAudio/index.ts
  packages/dev/core/src/AudioV2/abstractAudio/mainAudioBus.ts
  packages/dev/core/src/AudioV2/abstractAudio/mainAudioOut.ts
  packages/dev/core/src/AudioV2/abstractAudio/staticSound.ts
  packages/dev/core/src/AudioV2/abstractAudio/staticSoundBuffer.ts
  packages/dev/core/src/AudioV2/abstractAudio/staticSoundInstance.ts
  packages/dev/core/src/AudioV2/abstractAudio/streamingSound.ts
  packages/dev/core/src/AudioV2/abstractAudio/streamingSoundInstance.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/abstractAudioSubGraph.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/abstractAudioSubNode.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/audioSubNode.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/spatialAudioSubNode.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/stereoAudioSubNode.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/volumeAudioSubNode.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/abstractSpatialAudio.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/abstractSpatialAudioListener.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/abstractStereoAudio.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/index.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/spatialAudio.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/spatialAudioListener.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/stereoAudio.ts
  packages/dev/core/src/AudioV2/audioUtils.ts
  packages/dev/core/src/AudioV2/index.ts
  packages/dev/core/src/AudioV2/soundState.ts
  packages/dev/core/src/AudioV2/webAudio/index.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/spatialWebAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/stereoWebAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/volumeWebAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/webAudioBaseSubGraph.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/webAudioBusAndSoundSubGraph.ts
  packages/dev/core/src/AudioV2/webAudio/subProperties/spatialWebAudio.ts
  packages/dev/core/src/AudioV2/webAudio/subProperties/spatialWebAudioListener.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioBus.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioEngine.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioMainBus.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioMainOut.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioNode.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioStaticSound.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioStreamingSound.ts
  packages/dev/core/src/index.ts
Labels: new feature

#16249 Update playground for audio engine compatibility
  packages/dev/core/src/Audio/Interfaces/IAudioEngineOptions.ts
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/engine.common.ts
  packages/dev/core/src/Engines/engine.ts
  packages/tools/playground/src/components/rendererComponent.tsx
Labels: breaking change

#16256 corrected property assignment
  packages/dev/sharedUiComponents/src/lines/textLineComponent.tsx
Labels: skip changelog

#16251 Add spatial audio attach to camera, mesh and transform node capabilities to audio engine v2
  packages/dev/core/src/AudioV2/abstractAudio/abstractSound.ts
  packages/dev/core/src/AudioV2/abstractAudio/audioBus.ts
  packages/dev/core/src/AudioV2/abstractAudio/audioEngineV2.ts
  packages/dev/core/src/AudioV2/abstractAudio/components/spatialAudioAttacherComponent.ts
  packages/dev/core/src/AudioV2/abstractAudio/staticSound.ts
  packages/dev/core/src/AudioV2/abstractAudio/streamingSound.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/spatialAudioSubNode.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/abstractSpatialAudio.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/abstractSpatialAudioListener.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/spatialAudio.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/spatialAudioListener.ts
  packages/dev/core/src/AudioV2/index.ts
  packages/dev/core/src/AudioV2/spatialAudioAttachmentType.ts
  packages/dev/core/src/AudioV2/webAudio/components/spatialWebAudioUpdaterComponent.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/spatialWebAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subProperties/spatialWebAudio.ts
  packages/dev/core/src/AudioV2/webAudio/subProperties/spatialWebAudioListener.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioBus.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioEngine.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioStaticSound.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioStreamingSound.ts
Labels: audio

#16263 Particle create custom effect: Allow to pass the vertex shader name
  packages/dev/core/src/Particles/particleSystemComponent.ts
Labels: enhancement, particles

#16267 Fix Typo
  packages/dev/serializers/src/glTF/2.0/glTFExporter.ts
Labels: skip changelog

#16268 Mesh: Fix crash when cloning mesh
  packages/dev/core/src/Meshes/geometry.ts
Labels: bug, rendering engine

#16262 FrameGraph: add support for SSR
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Engines/nullEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/bloomPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/depthOfFieldPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/ssrPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/geometryRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/index.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraph.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/bloomTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/blurTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/postProcessTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/ssrBlurTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/ssrRenderingPipelineTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/ssrTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/geometryRendererTask.ts
  packages/dev/core/src/FrameGraph/frameGraph.ts
  packages/dev/core/src/FrameGraph/frameGraphTextureManager.ts
  packages/dev/core/src/FrameGraph/index.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/materialHelper.geometryrendering.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssrRenderingPipeline.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/thinSSRRenderingPipeline.ts
  packages/dev/core/src/PostProcesses/thinDepthOfFieldEffect.ts
  packages/dev/core/src/PostProcesses/thinSSRBlurCombinerPostProcess.ts
  packages/dev/core/src/PostProcesses/thinSSRBlurPostProcess.ts
  packages/dev/core/src/PostProcesses/thinSSRPostProcess.ts
  packages/dev/core/src/Shaders/screenSpaceReflection2BlurCombiner.fragment.fx
  packages/dev/core/src/ShadersWGSL/geometry.fragment.fx
  packages/dev/core/src/ShadersWGSL/screenSpaceReflection2BlurCombiner.fragment.fx
  packages/tools/nodeRenderGraphEditor/src/blockTools.ts
  packages/tools/nodeRenderGraphEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-nrge-SSR-HillValley.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-nrge-SSR-cube.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-nrge-SSR-neon.png
  packages/tools/tests/test/visualization/ReferenceImages/customRTT.png
  packages/tools/tests/test/visualization/config.json
Labels: new feature, frame graph

#16260 Add audio analyzer feature to audio engine v2 sound and bus classes
  packages/dev/core/src/AudioV2/abstractAudio/abstractAudioBus.ts
  packages/dev/core/src/AudioV2/abstractAudio/abstractSound.ts
  packages/dev/core/src/AudioV2/abstractAudio/audioBus.ts
  packages/dev/core/src/AudioV2/abstractAudio/mainAudioBus.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/abstractAudioSubGraph.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/audioAnalyzerSubNode.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/audioSubNode.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/stereoAudioSubNode.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/abstractAudioAnalyzer.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/audioAnalyzer.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/index.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/webAudioAnalyzerSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/webAudioBaseSubGraph.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/webAudioBusAndSoundSubGraph.ts
Labels: audio

#16278 Allow old audio engine to be enabled using engine's `audioEngine` option
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/engine.common.ts
Labels: bug, audio

#16288 NRGE: Show popup for alpha stage
  packages/tools/nodeRenderGraphEditor/src/nodeRenderGraphEditor.ts
Labels: skip changelog

#16279 Fix spatial audio init issues
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/abstractAudioSubGraph.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/spatialAudio.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/webAudioBaseSubGraph.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/webAudioBusAndSoundSubGraph.ts
Labels: bug, audio

#16290 Post-Process: Add missing dispose calls
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/PostProcesses/postProcess.ts
Labels: bug, post-process

#16292 Update sandbox.tsx
  packages/tools/sandbox/src/sandbox.tsx
Labels: skip changelog

#16298 Material:Fix pre-pass dirty flag
  packages/dev/core/src/Materials/materialDefines.ts
Labels: bug, materials

#16300 Frame Graph: refactoring + more post-processes supported
  packages/dev/core/src/FrameGraph/Node/Blocks/Layers/glowLayerBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Layers/highlightLayerBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/anaglyphPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/basePostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/chromaticAberrationPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/baseObjectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/utilityLayerRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/clearBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/copyTextureBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/generateMipmapsBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/index.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraph.ts
  packages/dev/core/src/FrameGraph/Tasks/Layers/baseLayerTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/anaglyphTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/bloomTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/chromaticAberrationTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/postProcessTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/ssrRenderingPipelineTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/objectRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/taaObjectRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/utilityLayerRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Texture/clearTextureTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Texture/copyToTextureTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Texture/generateMipMapsTask.ts
  packages/dev/core/src/FrameGraph/index.ts
  packages/dev/core/src/PostProcesses/anaglyphPostProcess.ts
  packages/dev/core/src/PostProcesses/chromaticAberrationPostProcess.ts
  packages/dev/core/src/PostProcesses/index.ts
  packages/dev/core/src/PostProcesses/thinAnaglyphPostProcess.ts
  packages/dev/core/src/PostProcesses/thinChromaticAberrationPostProcess.ts
  packages/dev/gui/src/2D/FrameGraph/guiTask.ts
  packages/dev/gui/src/2D/FrameGraph/renderGraphGUIBlock.ts
  packages/tools/nodeRenderGraphEditor/src/blockTools.ts
  packages/tools/nodeRenderGraphEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/graphEditor.tsx
  packages/tools/nodeRenderGraphEditor/src/graphSystem/registerToDisplayLedger.ts
  packages/tools/tests/test/visualization/config.json
Labels: enhancement, frame graph

#16311 Get old audio engine working in playgrounds that use `BABYLON.Sound`
  packages/dev/core/src/Engines/abstractEngine.ts
Labels: bug, audio

#16318 Improve audio engine API
  packages/dev/core/src/AudioV2/abstractAudio/components/spatialAudioAttacherComponent.ts
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/spatialAudioSubNode.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/abstractSpatialAudio.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/abstractSpatialAudioListener.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/spatialAudio.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/spatialAudioListener.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/spatialWebAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subProperties/spatialWebAudioListener.ts
Labels: audio

#16316 Fix lattice ejecting vertices too early
  packages/dev/core/src/Maths/math.scalar.functions.ts
  packages/dev/core/src/Meshes/lattice.ts
Labels: bug

#16319 Daily interactivity fixes
  packages/dev/core/src/FlowGraph/Blocks/Execution/Animation/flowGraphPlayAnimationBlock.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/dynamic.ts
Labels: skip changelog

#16321 Viewer and configurator tiny fixes
  packages/tools/viewer-configurator/src/components/configurator/configurator.scss
  packages/tools/viewer-configurator/src/components/configurator/configurator.tsx
  packages/tools/viewer/src/viewerAnnotationElement.ts
  packages/tools/viewer/test/apps/web/index.html
Labels: skip changelog

#16323 flag missing loaders as internal
  packages/dev/core/src/Materials/Textures/Loaders/basisTextureLoader.ts
  packages/dev/core/src/Materials/Textures/Loaders/exrTextureLoader.ts
Labels: skip changelog

#16327 Fix spatial audio `attach` feature position tracking
  packages/dev/core/src/AudioV2/abstractAudio/components/spatialAudioAttacherComponent.ts
Labels: bug, audio

#16326 Make sound `pitch` and `playbackRate` properties change continuously
  packages/dev/core/src/AudioV2/abstractAudio/abstractSound.ts
  packages/dev/core/src/AudioV2/abstractAudio/staticSound.ts
  packages/dev/core/src/AudioV2/abstractAudio/staticSoundInstance.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioStaticSound.ts
Labels: audio

#16328 Update playground links in typedoc comments
  packages/dev/addons/src/htmlMesh/htmlMesh.ts
  packages/dev/core/src/Lights/IES/iesLoader.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Lights/spotLight.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/prePassOutputBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/Textures/Loaders/exrTextureLoader.ts
  packages/dev/core/src/Meshes/csg2.ts
  packages/dev/core/src/Meshes/lattice.material.ts
  packages/dev/core/src/Meshes/lattice.ts
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/core/src/Misc/fileTools.ts
  packages/dev/core/src/Rendering/IBLShadows/iblShadowsVoxelRenderer.ts
  packages/dev/serializers/src/USDZ/usdzExporter.ts
Labels: skip changelog

#16334 set _blockEntityCollection value when loading splat files
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: skip changelog

#16338 Fix label picking for checkboxes
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
Labels: nme, skip changelog, nge, nrge

#16337 PBR: Fix diffuse transmission
  packages/dev/core/src/Materials/PBR/pbrSubSurfaceConfiguration.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockFinalLitComponents.fx
  packages/dev/core/src/Shaders/pbr.fragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockFinalLitComponents.fx
  packages/dev/core/src/ShadersWGSL/pbr.fragment.fx
  packages/tools/tests/test/visualization/ReferenceImages/KHR-diffuse-transmission.png
  packages/tools/tests/test/visualization/ReferenceImages/nme-multi-build.png
  packages/tools/tests/test/visualization/ReferenceImages/node-material-pbr-1.png
  packages/tools/tests/test/visualization/config.json
Labels: bug, materials, breaking change

#16342 Fix selection regression for links
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
Labels: skip changelog

#16343 FrameGraph: various corrections and additions
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/ssrPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/geometryRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/objectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/taaObjectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/utilityLayerRendererBlock.ts
  packages/dev/core/src/FrameGraph/Tasks/Layers/baseLayerTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/bloomTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/ssrRenderingPipelineTask.ts
  packages/tools/nodeRenderGraphEditor/public/index.js
  packages/tools/nodeRenderGraphEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/components/preview/previewManager.ts
  packages/tools/nodeRenderGraphEditor/src/components/propertyTab/propertyTabComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/globalState.ts
  packages/tools/nodeRenderGraphEditor/src/graphSystem/properties/genericNodePropertyComponent.tsx
Labels: bug, enhancement, skip changelog, frame graph

#16349 Skip audio engine v2 auto resume after `pause()`
  packages/dev/core/src/AudioV2/webAudio/webAudioEngine.ts
Labels: bug, audio

#16347 Allow custom target for readPixels
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: enhancement

#16348 Add audio engine v2 unmute UI
  packages/dev/core/src/AudioV2/webAudio/webAudioEngine.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioUnmuteUI.ts
Labels: audio, skip changelog

#16353 Node editors: Better message and properties when a port is AutoDetect
  packages/dev/sharedUiComponents/src/nodeGraphSystem/tools.ts
  packages/tools/nodeEditor/src/graphSystem/connectionPointPortData.ts
  packages/tools/nodeEditor/src/graphSystem/properties/nodePortPropertyComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/connectionPointPortData.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/nodePortPropertyComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/graphSystem/connectionPointPortData.ts
  packages/tools/nodeRenderGraphEditor/src/graphSystem/properties/nodePortPropertyComponent.tsx
Labels: skip changelog

#16360 PBR materials: fix sub-surface scattering
  packages/dev/core/src/Shaders/ShadersInclude/fibonacci.fx
  packages/dev/core/src/Shaders/subSurfaceScattering.fragment.fx
  packages/tools/tests/test/visualization/ReferenceImages/SubSurface-Scattering.png
  packages/tools/tests/test/visualization/config.json
Labels: bug, materials

#16363 Sub-Surface Scattering post-process: fix bug in shader + port to WGSL
  packages/dev/core/src/PostProcesses/subSurfaceScatteringPostProcess.ts
  packages/dev/core/src/Rendering/subSurfaceConfiguration.ts
  packages/dev/core/src/Shaders/subSurfaceScattering.fragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/diffusionProfile.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/fibonacci.fx
  packages/dev/core/src/ShadersWGSL/subSurfaceScattering.fragment.fx
  packages/tools/tests/test/visualization/ReferenceImages/SubSurface-Scattering.png
  packages/tools/tests/test/visualization/config.json
Labels: bug, WebGPU, breaking change, post-process

#16364 Ramp audio parameter values to avoid audible discontinuities
  packages/dev/core/src/AudioV2/abstractAudio/audioEngineV2.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/spatialWebAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/stereoWebAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/volumeWebAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subProperties/spatialWebAudioListener.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioEngine.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioMainOut.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioStaticSound.ts
Labels: audio, new feature

#16365 FrameGraph: update icons and colors + use AutoDetect inputs whenever possible
  packages/dev/core/src/FrameGraph/Node/Blocks/Layers/glowLayerBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Layers/highlightLayerBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/anaglyphPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/basePostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/ssrPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/baseObjectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/geometryRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/utilityLayerRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/clearBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/copyTextureBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/generateMipmapsBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/executeBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/resourceContainerBlock.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraphBlock.ts
  packages/tools/nodeRenderGraphEditor/src/blockTools.ts
  packages/tools/nodeRenderGraphEditor/src/graphSystem/registerNodePortDesign.ts
Labels: skip changelog, frame graph

#16366 Update node port colors when optional (NME, NGE, NRGE)
  packages/dev/sharedUiComponents/src/nodeGraphSystem/frameNodePort.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphCanvas.tsx
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.module.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/tools/nodeEditor/src/blockTools.ts
  packages/tools/nodeEditor/src/graphSystem/registerNodePortDesign.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/registerNodePortDesign.ts
  packages/tools/nodeRenderGraphEditor/src/blockTools.ts
  packages/tools/nodeRenderGraphEditor/src/graphSystem/registerNodePortDesign.ts
Labels: new feature, nme, nge, nrge

#16368 Improve the material inspector display with a way to link channel to existing textures
  packages/dev/inspector/src/components/actionTabs/actionTabs.scss
  packages/dev/inspector/src/components/actionTabs/lines/textureLinkLineComponent.tsx
  packages/dev/sharedUiComponents/src/lines/textureButtonLineComponent.tsx
Labels: new feature

#16371 Fix debug node size update
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
Labels: skip changelog

#16367 PBR: Fix IBL intensity
  packages/dev/core/src/Loading/Plugins/babylonFileLoader.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Misc/sceneSerializer.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockReflection.fx
  packages/dev/core/src/scene.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/scenePropertyGridComponent.tsx
Labels: bug, materials

#16373 Remove unused `audioContext` properties from audio bus classes
  packages/dev/core/src/AudioV2/webAudio/webAudioBus.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioMainBus.ts
Labels: audio, skip changelog

#16372 AbstractEngine and Viewer v2 resize fixes
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/tools/viewer-configurator/src/App.scss
  packages/tools/viewer/src/viewer.ts
Labels: bug

#16375 Add underscore to audio engine v2 public internal class members
  packages/dev/core/src/AudioV2/abstractAudio/subNodes/spatialAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/spatialWebAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/stereoWebAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/volumeWebAudioSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/webAudioAnalyzerSubNode.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/webAudioBaseSubGraph.ts
  packages/dev/core/src/AudioV2/webAudio/subNodes/webAudioBusAndSoundSubGraph.ts
  packages/dev/core/src/AudioV2/webAudio/subProperties/spatialWebAudioListener.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioBus.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioEngine.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioMainBus.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioMainOut.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioNode.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioStaticSound.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioStreamingSound.ts
Labels: audio, skip changelog

#16378 Set the audio engine unmute button relative to its parent element
  packages/dev/core/src/AudioV2/webAudio/webAudioUnmuteUI.ts
Labels: bug, audio

#16379 Fix sound and audio bus `analyzer` property return type
  packages/dev/core/src/AudioV2/abstractAudio/abstractAudioBus.ts
  packages/dev/core/src/AudioV2/abstractAudio/abstractSound.ts
Labels: audio, skip changelog

#16377 Fix audio bus connections
  packages/dev/core/src/AudioV2/webAudio/webAudioBus.ts
Labels: bug, audio

#16383 Fix Viewer toolbar width regression
  packages/tools/viewer-configurator/src/App.scss
  packages/tools/viewer/src/viewer.ts
  packages/tools/viewer/src/viewerElement.ts
Labels: bug

#16385 WebGPU: Fix various problems with WGSL and node materials
  packages/dev/core/src/Materials/Node/Blocks/Dual/reflectionTextureBaseBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/perturbNormalBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Fragment/shadowMapBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/Input/inputBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildState.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildStateSharedData.ts
  packages/dev/core/src/Shaders/imageProcessing.fragment.fx
  packages/dev/core/src/Shaders/motionBlur.fragment.fx
  packages/dev/core/src/Shaders/screenSpaceReflection2.fragment.fx
  packages/dev/core/src/ShadersWGSL/imageProcessing.fragment.fx
  packages/dev/core/src/ShadersWGSL/motionBlur.fragment.fx
  packages/dev/core/src/ShadersWGSL/screenSpaceReflection2.fragment.fx
  packages/tools/testTools/src/visualizationUtils.ts
  packages/tools/tests/test/playwright/visualizationPlaywright.utils.ts
  packages/tools/tests/test/visualization/ReferenceImages/Screen-Space-Reflections-2.png
  packages/tools/tests/test/visualization/ReferenceImages/motionBlur.png
  packages/tools/tests/test/visualization/ReferenceImages/terrain-erosion.png
  packages/tools/tests/test/visualization/config.json
Labels: bug, materials, WebGPU

#16388 Arc rotate restore stop
  packages/dev/core/src/Cameras/arcRotateCamera.ts
  packages/dev/core/src/Maths/math.vector.ts
Labels: bug, viewer

#16393 Fix adaptive scaling setting in AdvancedDynamicTexture's CreateFullscreenUI
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
Labels: bug

#16394 Fix ace items not being pickable
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.module.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.ts
Labels: bug, skip changelog

#16395 Use correct options type for `_WebAudioEngine.createSoundBufferAsync`
  packages/dev/core/src/AudioV2/webAudio/webAudioEngine.ts
Labels: skip changelog

#16396 Change static sound `playbackRate` and `pitch` settings API
  packages/dev/core/src/AudioV2/abstractAudio/staticSound.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioStaticSound.ts
Labels: skip changelog

#16391 Some fixes before release for glTF interactivity
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_interactivity/declarationMapper.ts
  packages/dev/loaders/src/glTF/2.0/Extensions/objectModelMapping.ts
Labels: skip changelog

#16399 Playground: Fix crash in 4.2.1
  packages/tools/playground/src/components/rendererComponent.tsx
Labels: bug, Playground, skip changelog

#16400 NME: Make the iridescence block available in menus
  packages/dev/core/src/Materials/Node/Blocks/PBR/index.ts
  packages/tools/nodeEditor/src/blockTools.ts
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
Labels: nme, skip changelog

#16401 NME: Fix crash when iridescence and clearcoat are used at the same time
  packages/dev/core/src/Materials/Node/Blocks/PBR/clearCoatBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/iridescenceBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockIridescence.fx
  packages/dev/core/src/Shaders/pbr.fragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockIridescence.fx
  packages/dev/core/src/ShadersWGSL/pbr.fragment.fx
Labels: bug, nme

#16397 FrameGraph: make frame graphs available in the inspector
  packages/dev/core/src/Debug/debugLayer.ts
  packages/dev/core/src/Engines/constants.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/baseObjectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/geometryRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/objectRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Textures/clearBlock.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraph.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/objectRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/taaObjectRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Texture/clearTextureTask.ts
  packages/dev/core/src/FrameGraph/frameGraph.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/Rendering/objectRenderer.ts
  packages/dev/core/src/scene.ts
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGridTabComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/frameGraphs/frameGraphPropertyGridComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/entities/frameGraphTreeItemComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/entities/ic_fluent_flow_24_filled.svg
  packages/dev/inspector/src/components/sceneExplorer/sceneExplorer.scss
  packages/dev/inspector/src/components/sceneExplorer/sceneExplorerComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/treeItemLabelComponent.tsx
  packages/dev/inspector/src/components/sceneExplorer/treeItemSpecializedComponent.tsx
  packages/dev/loaders/src/glTF/2.0/Extensions/KHR_materials_transmission.ts
  packages/tools/nodeRenderGraphEditor/src/main.scss
Labels: enhancement, skip changelog, frame graph

#16404 Replace pure SVG by img svg for perf
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.module.scss
  packages/dev/sharedUiComponents/src/nodeGraphSystem/nodePort.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/tools/nodeEditor/src/graphSystem/registerNodePortDesign.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/registerNodePortDesign.ts
  packages/tools/nodeRenderGraphEditor/src/graphSystem/registerNodePortDesign.ts
Labels: skip changelog

#16405 Add `Async` suffix to audio engine functions that return a promise
  packages/dev/core/src/AudioV2/abstractAudio/audioEngineV2.ts
  packages/dev/core/src/AudioV2/abstractAudio/streamingSound.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/abstractAudioAnalyzer.ts
  packages/dev/core/src/AudioV2/abstractAudio/subProperties/audioAnalyzer.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioEngine.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioStreamingSound.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioUnmuteUI.ts
Labels: audio, skip changelog

#16398 Mesh picking: Fix calculation of the world normal when picking thin instances
  packages/dev/core/src/Collisions/pickingInfo.ts
Labels: bug, picking

#16406 Increase effect compilation timeout
  packages/dev/core/src/Materials/effect.ts
Labels: skip changelog

#16407 Fix dynamicTexture resize losing track of readiness state
  packages/dev/gui/src/2D/advancedDynamicTexture.ts
Labels: bug

#16410 PBR sub-surface: Add switch for back compatibility
  packages/dev/core/src/Materials/Node/Blocks/PBR/subSurfaceBlock.ts
  packages/dev/core/src/Materials/PBR/pbrSubSurfaceConfiguration.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockFinalLitComponents.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockFinalLitComponents.fx
Labels: enhancement, materials

#16411 Remove weird loop
  packages/dev/core/src/Cameras/Inputs/arcRotateCameraMouseWheelInput.ts
Labels: bug, skip changelog

#16416 FrameGraph: Fix code generated for input blocks by NRGE
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraphBlock.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraphBlockConnectionPoint.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlockConnectionPoint.ts
  packages/dev/core/src/Meshes/Node/nodeGeometryBlockConnectionPoint.ts
Labels: bug, frame graph

#16417 Fix pbr mirror
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockNormalFinal.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockNormalFinal.fx
  packages/tools/tests/test/visualization/ReferenceImages/pbr-mirror.png
  packages/tools/tests/test/visualization/config.json
Labels: bug

#16419 Fix bug when update sampling was not taking mip map generation in acc…
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Materials/Textures/thinTexture.ts
  packages/tools/tests/test/visualization/config.json
Labels: bug

#16423 PBR: Fix wrong diffuse from hemispherical/area lights when translucency is enabled
  packages/dev/core/src/Shaders/ShadersInclude/lightFragment.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockDirectLighting.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockFinalUnlitComponents.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrDirectLightingFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/lightFragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockDirectLighting.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockFinalUnlitComponents.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrDirectLightingFunctions.fx
  packages/tools/tests/test/visualization/ReferenceImages/fluidParticleSystem.png
  packages/tools/tests/test/visualization/ReferenceImages/nme-multi-build.png
  packages/tools/tests/test/visualization/ReferenceImages/node-material-pbr-1.png
  packages/tools/tests/test/visualization/ReferenceImages/node-material-pbr-2.png
  packages/tools/tests/test/visualization/ReferenceImages/pbr-codecoverage1.png
  packages/tools/tests/test/visualization/ReferenceImages/pbr-codecoverage2.png
  packages/tools/tests/test/visualization/ReferenceImages/pbr-codecoverage3.png
  packages/tools/tests/test/visualization/config.json
Labels: bug, materials

#16428 Cloning instanced meshes: don't try to clone the geometry object
  packages/dev/core/src/Meshes/instancedMesh.ts
Labels: bug, rendering engine

#16427 Viewer: Fix trying to use a disposed env texture in a PBR material
  packages/dev/core/src/Engines/WebGPU/webgpuCacheBindGroups.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/tools/viewer/src/viewer.ts
Labels: bug, viewer
