Repository BabylonJS/Babylon.js, pull requests merged in 2025-02, with the labels that each got.

#16135 move timer stats to thinEngine
  packages/dev/core/src/Engines/AbstractEngine/abstractEngine.query.ts
  packages/dev/core/src/Engines/AbstractEngine/abstractEngine.timeQuery.ts
  packages/dev/core/src/Engines/AbstractEngine/index.ts
  packages/dev/core/src/Engines/Extensions/engine.query.ts
Labels: skip changelog

#15960 Physics Constraints debug viewer
  packages/dev/core/src/Debug/physicsViewer.ts
  packages/dev/core/src/Physics/v2/ragdoll.ts
Labels: physics, new feature, debug tool

#16138 Add debug Node to GS, procedural, particles and PP
  packages/dev/core/src/Materials/Node/Blocks/Particle/particleRampGradientBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/debugBlock.ts
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
  packages/tools/nodeEditor/src/graphSystem/properties/debugNodePropertyTabComponent.tsx
Labels: skip changelog

#16139 Fix missing conversion
  packages/dev/core/src/ShadersWGSL/particles.vertex.fx
Labels: bug

#16140 Add Basis Universal WASM to public
  packages/tools/babylonServer/public/basis_encoder.js
  packages/tools/babylonServer/public/basis_encoder.wasm
Labels: skip changelog

#16141 Fix flipped camera on export
  packages/dev/serializers/src/glTF/2.0/glTFUtilities.ts
Labels: skip changelog

#16146 Fixed issue when using SSAO2 with viewports
  packages/dev/core/src/Shaders/ssaoCombine.fragment.fx
  packages/dev/core/src/ShadersWGSL/ssaoCombine.fragment.fx
Labels: bug

#16144 Rendering Engine: Fix alpha support
  packages/dev/core/src/Layers/thinEffectLayer.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Materials/Background/backgroundMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/material.ts
  packages/dev/core/src/Materials/shaderMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
  packages/dev/core/src/PostProcesses/volumetricLightScatteringPostProcess.ts
  packages/dev/core/src/Rendering/depthRenderer.ts
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/core/src/Rendering/outlineRenderer.ts
  packages/dev/core/src/Rendering/renderingGroup.ts
  packages/dev/materials/src/cell/cellMaterial.ts
  packages/dev/materials/src/fur/furMaterial.ts
  packages/dev/materials/src/gradient/gradientMaterial.ts
  packages/dev/materials/src/lava/lavaMaterial.ts
  packages/dev/materials/src/mix/mixMaterial.ts
  packages/dev/materials/src/normal/normalMaterial.ts
  packages/dev/materials/src/shadowOnly/shadowOnlyMaterial.ts
  packages/dev/materials/src/simple/simpleMaterial.ts
  packages/dev/materials/src/terrain/terrainMaterial.ts
  packages/dev/materials/src/triPlanar/triPlanarMaterial.ts
  packages/dev/materials/src/water/waterMaterial.ts
  packages/tools/tests/test/visualization/config.json
Labels: rendering engine, breaking change

#16147 Fix misuse of offset in updatedynamicbuffer
  packages/dev/core/src/Engines/Extensions/engine.dynamicBuffer.ts
Labels: bug

#16149 Add Irradiance texture support in Env format
  packages/dev/core/src/Engines/Extensions/engine.rawTexture.ts
  packages/dev/core/src/Engines/nativeEngine.ts
  packages/dev/core/src/Misc/environmentTextureTools.ts
  packages/dev/inspector/src/components/actionTabs/tabs/toolsTabComponent.tsx
  packages/tools/sandbox/src/tools/environmentTools.ts
Labels: materials, new feature

#16153 Preserve vertex buffer types in DracoEncoder
  packages/dev/core/src/Buffers/bufferUtils.ts
  packages/dev/core/src/Meshes/Compression/dracoCompressionWorker.ts
  packages/dev/core/src/Meshes/Compression/dracoEncoder.ts
  packages/dev/core/src/Meshes/Compression/dracoEncoder.types.ts
  packages/dev/serializers/src/glTF/2.0/Extensions/KHR_draco_mesh_compression.ts
Labels: optimizations, skip changelog

#16156 Fix pointerId leak when a pen is lifted off the digitizer
  packages/dev/core/src/DeviceInput/webDeviceInputSystem.ts
Labels: bug

#16158 Fix tests after alpha changes
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#16160 Fix HDR irradiance filtering not rendering if scene not rendering yet
  packages/dev/core/src/Materials/Textures/Filtering/hdrFiltering.ts
  packages/dev/core/src/Materials/Textures/Filtering/hdrIrradianceFiltering.ts
  packages/dev/core/src/Materials/effect.ts
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#16164 Fix nge crash when no data is present for Compute Normals
  packages/dev/core/src/Meshes/Node/Blocks/computeNormalsBlock.ts
Labels: bug

#16165 SnapshotRenderingHelper: Don't force world matrix computation
  packages/dev/core/src/Misc/snapshotRenderingHelper.ts
Labels: enhancement, WebGPU

#16167 Fix OnPickDownTrigger passing along a stale meshUnderPointer value on touch devices
  packages/dev/core/src/Inputs/scene.inputManager.ts
Labels: bug

#16169 UT for processing pointer down triggers, ensuring the meshUnderPointer passed to the handler is up to date
  .vscode/settings.json
  packages/dev/core/test/unit/DeviceInput/babylon.inputManager.test.ts
Labels: tests

#16168 Add support for PointListBlock - Used to manually defines a geometry based on a list of points
  packages/dev/core/src/Meshes/Node/Blocks/Sources/pointListBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/dev/sharedUiComponents/src/lines/vector3LineComponent.tsx
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTab.scss
  packages/tools/nodeGeometryEditor/src/graphSystem/properties/pointListNodePropertyComponent.tsx
  packages/tools/nodeGeometryEditor/src/graphSystem/registerToDisplayLedger.ts
  packages/tools/nodeGeometryEditor/src/graphSystem/registerToPropertyLedger.ts
Labels: new feature

#16170 Add missing classname
  packages/tools/nodeGeometryEditor/src/components/propertyTab/propertyTab.scss
Labels: skip changelog

#16182 Update manifold to 3.0.1
  packages/dev/core/src/Meshes/csg2.ts
Labels: skip changelog

#16185 FrameGraph: add support for utility layer renderers
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/utilityLayerRendererBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/index.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/utilityLayerRendererTask.ts
  packages/dev/core/src/FrameGraph/frameGraph.ts
  packages/dev/core/src/FrameGraph/frameGraphRenderContext.ts
  packages/dev/core/src/FrameGraph/index.ts
  packages/dev/core/src/Rendering/utilityLayerRenderer.ts
  packages/dev/core/src/scene.ts
  packages/dev/gui/src/2D/FrameGraph/renderGraphGUIBlock.ts
  packages/dev/inspector/src/components/sceneExplorer/entities/sceneTreeItemComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/blockTools.ts
  packages/tools/nodeRenderGraphEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/components/preview/previewManager.ts
Labels: enhancement, frame graph

#16187 Screenshot tool: Use the right mesh list
  packages/dev/core/src/Misc/screenshotTools.ts
Labels: bug, rendering engine

#16191 NME: Add support for velocity to prepass output block
  packages/dev/core/src/Materials/Node/Blocks/Fragment/prePassOutputBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
Labels: enhancement, nme

#16190 NME: Fix global worldPos and worldNormal not declared in "Generate only fragment code" mode
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
Labels: bug, nme

#16193 Engine: Move the CreateAlignedTypedArray function from engine to bufferUtils
  packages/dev/core/src/Buffers/bufferUtils.ts
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: skip changelog

#16194 Fix script error when no mesh is in the scene for camera framing behavior
  packages/dev/core/src/Behaviors/Cameras/framingBehavior.ts
Labels: bug

#16196 Set SPZ Niantic Sample as reference
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
  packages/dev/loaders/src/SPLAT/splatLoadingOptions.ts
Labels: skip changelog

#16198 Add offset to instantiate nodes
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnFacesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVerticesBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Instances/instantiateOnVolumeBlock.ts
  packages/dev/core/src/Meshes/csg2.ts
Labels: new feature

#16202 Add support for subdivide modifier for NGE and VertexData
  packages/dev/core/src/Meshes/Node/Blocks/Sources/boxBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/gridBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/Sources/planeBlock.ts
  packages/dev/core/src/Meshes/Node/Blocks/subdivideBlock.ts
  packages/dev/core/src/Meshes/Node/index.ts
  packages/dev/core/src/Meshes/index.ts
  packages/dev/core/src/Meshes/mesh.vertexData.subdivide.ts
  packages/dev/core/src/Meshes/mesh.vertexData.ts
  packages/tools/nodeGeometryEditor/src/blockTools.ts
  packages/tools/nodeGeometryEditor/src/components/nodeList/nodeListComponent.tsx
Labels: new feature, geometry, nge

#16208 WebGPU: Fix crash when using clear coat bump
  packages/dev/core/src/ShadersWGSL/pbr.fragment.fx
Labels: bug, WebGPU

#16212 Fix Geometry update with smaller buffer
  packages/dev/core/src/Meshes/geometry.ts
Labels: bug

#16215 Fix empty runOriginalID for CSG2 toMesh
  packages/dev/core/src/Meshes/csg2.ts
Labels: skip changelog

#16214 PBR: Fix calculation of transmittance
  packages/dev/core/src/Shaders/ShadersInclude/lightFragment.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockFinalUnlitComponents.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrDirectLightingFunctions.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/lightFragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockFinalUnlitComponents.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrDirectLightingFunctions.fx
  packages/tools/tests/test/visualization/ReferenceImages/nme-multi-build.png
  packages/tools/tests/test/visualization/ReferenceImages/node-material-pbr-1.png
  packages/tools/tests/test/visualization/ReferenceImages/node-material-pbr-2.png
  packages/tools/tests/test/visualization/ReferenceImages/pbr-codecoverage1.png
  packages/tools/tests/test/visualization/ReferenceImages/pbr-codecoverage2.png
  packages/tools/tests/test/visualization/ReferenceImages/pbr-codecoverage3.png
Labels: bug, materials

#16224 Screenshots: Add a customDumpData function parameter to CreateScreenshotUsingRenderTarget
  packages/dev/core/src/Misc/screenshotTools.ts
Labels: enhancement, rendering engine

#16225 CC Acceleration/max acceleration exposed
  packages/dev/core/src/Physics/v2/characterController.ts
Labels: physics

#16227 Fix is32Bits detection in geometry setIndexBuffer
  packages/dev/core/src/Meshes/geometry.ts
Labels: bug, rendering engine

#16229 PBR: Fix refraction transmittance
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockSubSurface.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockSubSurface.fx
Labels: bug, materials, breaking change

#16235 Core Engine: Misc fixes related to index buffer management
  packages/dev/core/src/Buffers/bufferUtils.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Meshes/geometry.ts
  packages/dev/core/src/Meshes/mesh.ts
  packages/dev/serializers/src/glTF/2.0/glTFExporter.ts
Labels: bug, rendering engine

#16239 Fix a problem when the user is fast enough to generate many models be…
  packages/tools/nodeGeometryEditor/src/components/preview/previewManager.ts
Labels: skip changelog
