Repository BabylonJS/Babylon.js, pull requests merged in 2025-01, with the labels that each got.

#16034 FrameGraph: Add support for node materials to the frame graph geometry renderer
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
Labels: enhancement, frame graph

#16036 Morph target manager: Don't recreate texture if not needed when updates are re-enabled
  packages/dev/core/src/Morph/morphTargetManager.ts
Labels: enhancement, rendering engine

#16042 SPZ splat orientation
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: skip changelog

#16038 Mesh: fix LOD management
  packages/dev/core/src/Engines/Extensions/engine.multiRender.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/baseShadowGeneratorBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/csmShadowGeneratorBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/shadowGeneratorBlock.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/bloomTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldMergeTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/csmShadowGeneratorTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/geometryRendererTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/shadowGeneratorTask.ts
  packages/dev/core/src/FrameGraph/frameGraph.ts
  packages/dev/core/src/FrameGraph/frameGraphTask.ts
  packages/dev/core/src/Lights/Shadows/shadowGenerator.ts
  packages/dev/core/src/Materials/Textures/renderTargetTexture.ts
  packages/dev/core/src/Meshes/abstractMesh.ts
  packages/dev/core/src/Rendering/objectRenderer.ts
  packages/dev/core/src/scene.ts
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-custom-rendering.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-gui-bloom.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-nrg-glow-layer.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-nrg-gui-bloom.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-nrge-csm-shadows.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-nrge-custom-rendering.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-nrge-depth-of-field.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-nrge-glow-layer.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-nrge-shadows.png
  packages/tools/tests/test/visualization/config.json
Labels: bug, rendering engine, frame graph

#16043 Fix lineMesh cloned alpha values
  packages/dev/core/src/Meshes/linesMesh.ts
Labels: bug

#16045 WebGPU: fix crashes in Firefox and Safari
  packages/dev/core/src/Engines/WebGPU/webgpuCacheRenderPipeline.ts
  packages/dev/core/src/Engines/WebGPU/webgpuTextureManager.ts
  packages/dev/core/src/Materials/Node/Blocks/Input/inputBlock.ts
  packages/dev/core/src/Meshes/GreasedLine/greasedLineBaseMesh.ts
Labels: bug, WebGPU

#16046 Mesh: Make cloning thin instances optional
  packages/dev/core/src/Meshes/mesh.ts
Labels: enhancement, rendering engine

#16047 SPZ color conversion
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: skip changelog

#16050 Gizmo Rotation plane + pivot fix
  packages/dev/core/src/Gizmos/planeRotationGizmo.ts
Labels: bug

#16057 Fix recursive loop in onPointerOutAction
  packages/dev/core/src/Inputs/scene.inputManager.ts
Labels: bug

#16058 Morph: Fix morph not updated when updates are unfrozen
  packages/dev/core/src/Morph/morphTargetManager.ts
Labels: bug, rendering engine

#16052 Allow for creating a zero size plane
  packages/dev/core/src/Meshes/Builders/planeBuilder.ts
Labels: breaking change

#16068 FIx wrong links for bbhelper
  packages/dev/core/src/Culling/Helper/boundingInfoHelper.ts
Labels: skip changelog

#16071 standardMaterial: remove _worldViewProjectionMatrix
  packages/dev/core/src/Materials/standardMaterial.ts
Labels: bug

#16070 Use same configuration between DracoCompression and DracoDecoder
  packages/dev/core/src/Meshes/Compression/dracoCompression.ts
  packages/dev/core/src/Meshes/Compression/test/integration/draco.test.ts
  packages/tools/tests/test/playwright/visualizationPlaywright.utils.ts
Labels: skip changelog

#16077 Fix unwanted reset of values for splitters
  packages/dev/sharedUiComponents/src/split/splitContainer.tsx
  packages/dev/sharedUiComponents/src/split/splitter.tsx
  packages/tools/playground/test/interactions.playground.test.ts
Labels: bug, skip changelog

#16075 Allow the users to control the max fps of the engine
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/engine.ts
  packages/dev/core/src/Misc/screenshotTools.ts
Labels: new feature

#16080 Enable effect to be persistent
  packages/dev/core/src/Engines/abstractEngine.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/Engines/webgpuEngine.ts
  packages/dev/core/src/Materials/effect.ts
  packages/dev/core/src/Particles/webgl2ParticleSystem.ts
Labels: new feature

#16081 Fix ScreenshotTools
  packages/dev/core/src/Meshes/csg.ts
  packages/dev/core/src/Misc/screenshotTools.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssao2RenderingPipeline.ts
Labels: bug

#16079 Better inspector open/close management
  packages/dev/core/src/Debug/debugLayer.ts
  packages/dev/inspector/src/inspector.ts
  packages/tools/playground/src/components/commandBarComponent.tsx
  packages/tools/playground/src/components/hamburgerMenu.tsx
  packages/tools/playground/src/components/rendererComponent.tsx
  packages/tools/playground/src/globalState.ts
Labels: skip changelog

#16082 Factorize intersectionFunctions
  packages/dev/core/src/Shaders/ShadersInclude/intersectionFunctions.fx
  packages/dev/core/src/Shaders/background.fragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/intersectionFunctions.fx
  packages/dev/core/src/ShadersWGSL/background.fragment.fx
Labels: skip changelog

#16084 reset ideal width and height on serialization
  packages/dev/gui/src/2D/controls/control.ts
Labels: breaking change

#16072 Update Recast.js 1.6.4
  packages/tools/babylonServer/public/recast.js
Labels: navigation

#16091 fix race condition with meshopt compression
  packages/dev/core/src/Meshes/Compression/meshoptCompression.ts
Labels: bug

#16090 Inspector when using older versions
  packages/tools/playground/src/components/rendererComponent.tsx
Labels: skip changelog

#16099 WebGPU: Fixed shader crashes using "discard"
  packages/dev/core/src/ShadersWGSL/glowMapGeneration.fragment.fx
  packages/dev/core/src/ShadersWGSL/layer.fragment.fx
Labels: bug, WebGPU

#16094 SH view space
  packages/dev/core/src/Shaders/gaussianSplatting.vertex.fx
Labels: skip changelog

#16102 Add missing argument when exporting glTF animation
  packages/dev/serializers/src/glTF/2.0/glTFExporter.ts
Labels: skip changelog

#16106 Sprites: Fixed crash when deleting/creating two sprite managers in succession
  packages/dev/core/src/Sprites/spriteRenderer.ts
Labels: bug, rendering engine, sprite

#16096 FrameGraph: optimize texture allocation
  packages/dev/core/src/Engines/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/WebGL/webGLRenderTargetWrapper.ts
  packages/dev/core/src/Engines/WebGPU/Extensions/engine.renderTarget.ts
  packages/dev/core/src/Engines/renderTargetWrapper.ts
  packages/dev/core/src/Engines/thinEngine.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraph.ts
  packages/dev/core/src/FrameGraph/Node/nodeRenderGraphBlock.ts
  packages/dev/core/src/FrameGraph/Passes/renderPass.ts
  packages/dev/core/src/FrameGraph/Tasks/Layers/baseLayerTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Layers/highlightLayerTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/bloomMergeTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/bloomTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/circleOfConfusionTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldBlurTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldMergeTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/depthOfFieldTask.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/postProcessTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Texture/copyToBackbufferColorTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Texture/copyToTextureTask.ts
  packages/dev/core/src/FrameGraph/frameGraph.ts
  packages/dev/core/src/FrameGraph/frameGraphTask.ts
  packages/dev/core/src/FrameGraph/frameGraphTextureManager.ts
  packages/dev/core/src/Materials/Textures/internalTexture.ts
  packages/dev/core/src/Materials/Textures/textureHelper.functions.ts
  packages/dev/core/src/Misc/timingTools.ts
  packages/tools/nodeRenderGraphEditor/src/components/preview/previewManager.ts
  packages/tools/nodeRenderGraphEditor/src/components/propertyTab/inputsPropertyTabComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/components/propertyTab/propertyTabComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/components/propertyTab/textureMemoryUsagePropertyTabComponent.tsx
  packages/tools/nodeRenderGraphEditor/src/graphSystem/properties/framePropertyComponent.tsx
  packages/tools/playground/test/interactions.playground.test.ts
  packages/tools/sandbox/test/interaction.sandbox.test.ts
  packages/tools/tests/test/playwright/interaction.tools.test.ts
Labels: enhancement, frame graph

#16085 Add OpenPBR's base_weight material parameter
  packages/dev/core/src/Materials/Node/Blocks/PBR/pbrMetallicRoughnessBlock.ts
  packages/dev/core/src/Materials/PBR/pbrBaseMaterial.ts
  packages/dev/core/src/Materials/PBR/pbrMaterial.ts
  packages/dev/core/src/Materials/materialFlags.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockAlbedoOpacity.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrFragmentDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrFragmentSamplersDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrUboDeclaration.fx
  packages/dev/core/src/Shaders/ShadersInclude/pbrVertexDeclaration.fx
  packages/dev/core/src/Shaders/pbr.fragment.fx
  packages/dev/core/src/Shaders/pbr.vertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockAlbedoOpacity.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrFragmentSamplersDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrUboDeclaration.fx
  packages/dev/core/src/ShadersWGSL/pbr.fragment.fx
  packages/dev/core/src/ShadersWGSL/pbr.vertex.fx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/materials/pbrMaterialPropertyGridComponent.tsx
  packages/tools/tests/test/visualization/ReferenceImages/openpbr-base-weight.png
  packages/tools/tests/test/visualization/config.json
Labels: new feature

#16108 Add support for manualEmitCount for GPUParticles
  packages/dev/core/src/Particles/gpuParticleSystem.ts
Labels: new feature

#16111 Material: Export the PBRBRDFConfiguration class
  packages/dev/core/src/Materials/PBR/index.ts
Labels: skip changelog

#16109 Move TypedArray utilities
  packages/dev/core/src/Buffers/bufferUtils.ts
  packages/dev/core/src/Meshes/Compression/dracoCompressionWorker.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: skip changelog

#16120 Improved Immediate queue management
  packages/dev/core/src/Misc/timingTools.ts
Labels: skip changelog

#16104 Add method to get vertex data as component type
  packages/dev/core/src/Buffers/bufferUtils.ts
  packages/dev/core/test/unit/Buffers/babylon.buffer.test.ts
Labels: skip changelog

#16122 Add Epsilon for GS lambdas
  packages/dev/core/src/Shaders/ShadersInclude/gaussianSplatting.fx
Labels: skip changelog

#16124 NME debug block
  packages/dev/core/src/Materials/Node/Blocks/Fragment/fragmentOutputBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/debugBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/index.ts
  packages/dev/core/src/Materials/Node/nodeMaterial.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBlock.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/interfaces/nodeData.ts
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/tools/nodeEditor/src/blockTools.ts
  packages/tools/nodeEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
  packages/tools/nodeEditor/src/graphSystem/blockNodeData.ts
  packages/tools/nodeEditor/src/graphSystem/display/debugDisplayManager.module.scss
  packages/tools/nodeEditor/src/graphSystem/display/debugDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/registerToDisplayLedger.ts
Labels: new feature

#15864 Viewer auto suspend rendering when scene is idle
  packages/dev/core/src/Engines/WebGPU/webgpuSnapshotRendering.ts
  packages/dev/core/src/Misc/snapshotRenderingHelper.ts
  packages/tools/viewer/src/viewer.ts
  packages/tools/viewer/src/viewerElement.ts
  packages/tools/viewer/src/viewerFactory.ts
  packages/tools/viewer/test/apps/web/index.html
  packages/tools/viewer/tsconfig.build.json
  packages/tools/viewer/tsconfig.json
  packages/tools/viewer/tsconfig.viewer.json
Labels: stale

#16130 Quick fix to remove render graph
  .build/config.json
  packages/tools/nodeEditor/src/components/preview/previewManager.ts
  packages/tools/nodeEditor/src/globalState.ts
  packages/tools/nodeEditor/src/graphSystem/display/debugDisplayManager.module.scss
  packages/tools/nodeEditor/src/graphSystem/display/debugDisplayManager.ts
Labels: skip changelog

#16131 WebGPU: Fix anisotropy
  packages/dev/core/src/Engines/WebGPU/webgpuCacheSampler.ts
Labels: bug, WebGPU

#16133 New "Refresh all" button
  packages/dev/sharedUiComponents/src/nodeGraphSystem/stateManager.ts
  packages/tools/nodeEditor/src/globalState.ts
  packages/tools/nodeEditor/src/graphSystem/display/debugDisplayManager.ts
  packages/tools/nodeEditor/src/graphSystem/properties/debugNodePropertyTabComponent.tsx
  packages/tools/nodeEditor/src/graphSystem/registerToPropertyLedger.ts
Labels: skip changelog

#16134 Fix feedback loop rendering that was writing to the depth buffer
  packages/dev/core/src/Particles/gpuParticleSystem.ts
Labels: bug
