Repository BabylonJS/Babylon.js, pull requests merged in 2025-05, with the labels that each got.

#16552 WebGPU material plugins: Fix arrays declaration
  packages/dev/core/src/Materials/materialPluginManager.ts
Labels: bug, materials, WebGPU

#16554 Fix MeshparticleEmitter bug
  packages/dev/core/src/Particles/EmitterTypes/meshParticleEmitter.ts
Labels: bug, particles

#16558 Get WebAudio working on iOS when ringer switch is turned off
  packages/dev/core/src/AudioV2/webAudio/webAudioEngine.ts
Labels: audio

#16561 Restore failing test
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#16563 WebGPU: Port min/max redux shader to WGSL
  packages/dev/core/src/Misc/minMaxReducer.ts
  packages/dev/core/src/ShadersWGSL/minmaxRedux.fragment.fx
Labels: enhancement, WebGPU

#16573 Try to fix flacky test "IBL radiance roughness"
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#16572 WebGPU: Make sure the depth texture is cleared with the right value at creation time
  packages/dev/core/src/Engines/webgpuEngine.ts
Labels: bug, WebGPU

#16581 Add linear hex value to color picker when color is stored in linear mode
  packages/dev/sharedUiComponents/src/colorPicker/colorPicker.scss
  packages/dev/sharedUiComponents/src/colorPicker/colorPicker.tsx
Labels: inspector, new feature

#16589 Fix animation goToFrame with negative speedRatio
  packages/dev/core/src/Animations/animatable.core.ts
Labels: bug, animations

#16588 Removed hard coded value for cameraGizmo
  packages/dev/core/src/Gizmos/cameraGizmo.ts
Labels: skip changelog

#16593 Fix #16591
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/particleSystemPropertyGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/valueGradientGridComponent.tsx
Labels: bug

#16582 Add new addon to render text using MSDF
  packages/dev/addons/src/index.ts
  packages/dev/addons/src/msdfText/fontAsset.ts
  packages/dev/addons/src/msdfText/index.ts
  packages/dev/addons/src/msdfText/paragraphOptions.ts
  packages/dev/addons/src/msdfText/sdf/bmFont.ts
  packages/dev/addons/src/msdfText/sdf/font.ts
  packages/dev/addons/src/msdfText/sdf/glyph.ts
  packages/dev/addons/src/msdfText/sdf/line.ts
  packages/dev/addons/src/msdfText/sdf/paragraph.ts
  packages/dev/addons/src/msdfText/textRenderer.ts
  packages/dev/addons/src/msdfText/webgl/fragment.ts
  packages/dev/addons/src/msdfText/webgl/vertex.ts
  packages/dev/addons/src/msdfText/webgpu/fragment.ts
  packages/dev/addons/src/msdfText/webgpu/vertex.ts
  packages/tools/tests/test/visualization/ReferenceImages/msdf-billboard.png
  packages/tools/tests/test/visualization/ReferenceImages/msdf.png
  packages/tools/tests/test/visualization/config.json
Labels: new feature

#16598 fix shaders uninitialized members
  packages/dev/core/src/Shaders/ShadersInclude/pbrDirectLightingSetupFunctions.fx
Labels: native

#16596 Add WebAudio node and microphone input sound sources to AudioEngineV2
  packages/dev/core/src/AudioV2/abstractAudio/abstractSound.ts
  packages/dev/core/src/AudioV2/abstractAudio/abstractSoundSource.ts
  packages/dev/core/src/AudioV2/abstractAudio/audioEngineV2.ts
  packages/dev/core/src/AudioV2/webAudio/index.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioEngine.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioSoundSource.ts
  packages/dev/core/src/AudioV2/webAudio/webAudioStaticSound.ts
  packages/tools/babylonServer/public/audiov2-test.js
  packages/tools/tests/test/audioV2/soundSource.spatial.test.ts
  packages/tools/tests/test/audioV2/soundSource.stereo.test.ts
  packages/tools/tests/test/audioV2/soundSource.volume.test.ts
  packages/tools/tests/test/audioV2/utils/audioV2.utils.ts
Labels: audio, new feature

#16602 FrameGraph: add support for motion blur
  packages/dev/core/src/Engines/constants.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/PostProcesses/motionBlurPostProcessBlock.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/index.ts
  packages/dev/core/src/FrameGraph/Passes/renderPass.ts
  packages/dev/core/src/FrameGraph/Tasks/PostProcesses/motionBlurTask.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/geometryRendererTask.ts
  packages/dev/core/src/FrameGraph/index.ts
  packages/dev/core/src/PostProcesses/RenderPipeline/Pipelines/ssrRenderingPipeline.ts
  packages/dev/core/src/PostProcesses/index.ts
  packages/dev/core/src/PostProcesses/motionBlurPostProcess.ts
  packages/dev/core/src/PostProcesses/thinMotionBlurPostProcess.ts
  packages/dev/core/src/PostProcesses/thinSSRPostProcess.ts
  packages/dev/core/src/Rendering/depthRenderer.ts
  packages/dev/core/src/Rendering/geometryBufferRenderer.ts
  packages/dev/core/src/Rendering/prePassRenderer.ts
  packages/dev/core/src/Shaders/ShadersInclude/screenSpaceRayTrace.fx
  packages/dev/core/src/Shaders/motionBlur.fragment.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/bonesDeclaration.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/bonesVertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/prePassVertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/screenSpaceRayTrace.fx
  packages/dev/core/src/ShadersWGSL/geometry.vertex.fx
  packages/dev/core/src/ShadersWGSL/motionBlur.fragment.fx
  packages/tools/nodeRenderGraphEditor/src/blockTools.ts
  packages/tools/nodeRenderGraphEditor/src/components/nodeList/nodeListComponent.tsx
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-motion-blur-object-based.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-motion-blur-screen-based.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-motion-blur-skinned.png
  packages/tools/tests/test/visualization/ReferenceImages/FrameGraph-nrge-motion-blur.png
  packages/tools/tests/test/visualization/config.json
Labels: enhancement, frame graph

#16601 Adding handling of InstacedMesh inside of addAllAssetsToContainer that was missing.
  packages/dev/core/src/assetContainer.ts
Labels: bug

#16599 First installment of the Thin Maths
  packages/dev/addons/src/msdfText/textRenderer.ts
  packages/dev/core/package.json
  packages/dev/core/src/Maths/ThinMaths/index.ts
  packages/dev/core/src/Maths/ThinMaths/thinMath.matrix.functions.ts
  packages/dev/core/src/Maths/ThinMaths/thinMath.matrix.ts
  packages/dev/core/src/Maths/index.ts
  packages/dev/core/src/Maths/math.vector.ts
  packages/public/@babylonjs/core/package.json
Labels: new feature

#16603 Fix #16600
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/particleSystemPropertyGridComponent.tsx
Labels: new feature

#16597 Compensation and kernel size for AA trained SPZ
  packages/dev/core/src/Materials/GaussianSplatting/gaussianSplattingMaterial.ts
  packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
  packages/dev/loaders/src/SPLAT/splatFileLoader.ts
Labels: skip changelog

#16604 Viewer: Fix ignored options bug & camera framing with multiple models
  packages/tools/viewer/src/viewer.ts
  packages/tools/viewer/src/viewerElement.ts
  packages/tools/viewer/src/viewerFactory.ts
Labels: bug

#16610 Remove no AA for 3dCommerce
  packages/tools/sandbox/src/components/renderingZone.tsx
Labels: skip changelog

#16459 Viewer: Add shadow support
  package-lock.json
  packages/public/@babylonjs/viewer/rollup.config.dist.esm.mjs
  packages/public/@babylonjs/viewer/rollup.config.lib.mjs
  packages/tools/viewer-configurator/package.json
  packages/tools/viewer-configurator/src/components/configurator/configurator.tsx
  packages/tools/viewer-configurator/tsconfig.build.json
  packages/tools/viewer-configurator/tsconfig.json
  packages/tools/viewer-configurator/webpack.config.js
  packages/tools/viewer/rollup.config.common.mjs
  packages/tools/viewer/src/Shaders/envShadowGround.fragment.fx
  packages/tools/viewer/src/Shaders/envShadowGround.vertex.fx
  packages/tools/viewer/src/ShadersWGSL/envShadowGround.fragment.fx
  packages/tools/viewer/src/ShadersWGSL/envShadowGround.vertex.fx
  packages/tools/viewer/src/viewer.ts
  packages/tools/viewer/src/viewerElement.ts
  packages/tools/viewer/src/viewerFactory.ts
  packages/tools/viewer/test/apps/web/index.html
Labels: viewer, new feature

#16613 Add inspector tools to debug particle attractors
  packages/dev/inspector/src/components/actionTabs/actionTabs.scss
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/attractorGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/attractorsGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/particleSystemPropertyGridComponent.tsx
Labels: inspector, new feature

#16616 ObjectRenderer: Sanity check
  packages/dev/core/src/Rendering/objectRenderer.ts
Labels: skip changelog

#16618 urgent fix for thin matrices
  .build/config.json
  packages/dev/addons/src/msdfText/textRenderer.ts
  packages/dev/core/src/Maths/ThinMaths/thinMath.matrix.functions.ts
  packages/dev/core/src/Maths/math.vector.ts
Labels: skip changelog

#16622 Add support for strokes for textRenderer
  packages/dev/addons/src/msdfText/sdf/paragraph.ts
  packages/dev/addons/src/msdfText/textRenderer.ts
  packages/dev/addons/src/msdfText/webgl/fragment.ts
  packages/dev/addons/src/msdfText/webgpu/fragment.ts
  packages/tools/tests/test/visualization/ReferenceImages/attractors.png
  packages/tools/tests/test/visualization/ReferenceImages/msdf-billboard.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#16629 Please leave the room exactly as you found it
  packages/dev/addons/src/msdfText/textRenderer.ts
Labels: skip changelog

#16630 Add new test for msdf stroke
  packages/tools/tests/test/visualization/ReferenceImages/msdf-stroke.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#16633 Material: Fix image processing not taken into account when changed
  packages/dev/core/src/Materials/PBR/pbrMaterial.ts
  packages/dev/core/src/Materials/standardMaterial.ts
Labels: bug, materials

#16632 WebGPU: Fix buffer accesses outside of allowed range
  packages/dev/core/src/Engines/WebGPU/webgpuBufferManager.ts
Labels: bug, WebGPU

#16617 Inspector msdf
  package-lock.json
  packages/dev/addons/src/index.ts
  packages/dev/addons/src/msdfText/index.ts
  packages/dev/addons/src/msdfText/sdf/index.ts
  packages/dev/addons/src/msdfText/textRenderer.ts
  packages/dev/addons/src/msdfText/webgl/index.ts
  packages/dev/addons/src/msdfText/webgpu/fragment.ts
  packages/dev/addons/src/msdfText/webgpu/index.ts
  packages/dev/addons/src/msdfText/webgpu/vertex.ts
  packages/dev/inspector/package.json
  packages/dev/inspector/rollup.config.js
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/attractorGridComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/attractorsGridComponent.tsx
  packages/dev/inspector/tsconfig.build.json
  packages/public/@babylonjs/inspector/package.json
  packages/public/umd/babylonjs-inspector/package.json
  packages/tools/babylonServer/public/index.html
  packages/tools/playground/public/index.js
  packages/tools/sandbox/public/index.js
  packages/tools/sandbox/webpack.config.js
  tsconfig.devpackages.json
Labels: inspector, skip changelog

#16635 Add aniso + mipmaps
  packages/dev/addons/src/msdfText/fontAsset.ts
  packages/dev/addons/src/msdfText/paragraphOptions.ts
  packages/dev/addons/src/msdfText/sdf/paragraph.ts
  packages/dev/addons/src/msdfText/textRenderer.ts
  packages/dev/addons/src/msdfText/webgl/fragment.ts
  packages/tools/tests/test/visualization/ReferenceImages/msdf-stroke.png
Labels: skip changelog

#16639 Add a new debug tool for the inspector to display meshes name
  packages/dev/addons/src/msdfText/fontAsset.ts
  packages/dev/addons/src/msdfText/textRenderer.ts
  packages/dev/addons/src/msdfText/webgl/vertex.ts
  packages/dev/addons/src/msdfText/webgpu/vertex.ts
  packages/dev/inspector/src/components/actionTabs/tabs/debugTabComponent.tsx
  packages/dev/inspector/src/components/actionTabs/tabs/propertyGrids/particleSystems/attractorsGridComponent.tsx
Labels: new feature

#16645 Introduce screenProjection for textrenderer
  packages/dev/addons/src/msdfText/textRenderer.ts
  packages/dev/addons/src/msdfText/webgl/vertex.ts
  packages/dev/addons/src/msdfText/webgpu/vertex.ts
  packages/dev/inspector/src/components/actionTabs/tabs/debugTabComponent.tsx
  packages/tools/tests/test/visualization/ReferenceImages/msdf-projected.png
  packages/tools/tests/test/visualization/config.json
Labels: skip changelog

#16649 PBR material: Fix an incorrect #if evaluation in vertex shader
  packages/dev/core/src/Engines/Processors/Expressions/Operators/shaderDefineArithmeticOperator.ts
  packages/dev/core/src/Shaders/ShadersInclude/pbrBRDFFunctions.fx
  packages/dev/core/src/Shaders/pbr.fragment.fx
  packages/dev/core/src/Shaders/pbr.vertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBRDFFunctions.fx
  packages/dev/core/src/ShadersWGSL/pbr.fragment.fx
  packages/dev/core/src/ShadersWGSL/pbr.vertex.fx
Labels: bug, materials

#16652 PBR Sub-Surface Scattering: Fix a performance issue
  packages/dev/core/src/Rendering/prePassEffectConfiguration.ts
  packages/dev/core/src/Rendering/prePassRenderer.ts
  packages/dev/core/src/Rendering/subSurfaceConfiguration.ts
Labels: bug, materials

#16651 Fix the ignoreParentScaling situation for the camera
  packages/dev/core/src/Cameras/targetCamera.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
Labels: bug, breaking change

#16653 Fix goToFrame
  packages/dev/core/src/Animations/animatable.core.ts
Labels: bug

#16657 Min/max reducer: add some documentation
  packages/dev/core/src/Misc/minMaxReducer.ts
Labels: enhancement, rendering engine

#16668 WebGL: Fix flicker on MacOS
  packages/dev/core/src/Shaders/pbr.vertex.fx
Labels: bug, rendering engine

#16675 Fix native build
  packages/dev/core/src/Shaders/pbr.vertex.fx
Labels: skip changelog

#16679 PBRBlockReflectivity: Remove `f` suffix
  packages/dev/core/src/Shaders/ShadersInclude/pbrBlockReflectivity.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/pbrBlockReflectivity.fx
Labels: skip changelog

#16680 Viewer: small fixes to test apps
  packages/public/@babylonjs/viewer/test/apps/web/index.html
  packages/public/@babylonjs/viewer/test/apps/web/published.html
  packages/tools/viewer/vite.config.mjs
Labels: bug

#16682 Frame Graph: make GPU picker work with frame graphs
  packages/dev/core/src/Collisions/gpuPicker.ts
  packages/dev/core/src/FrameGraph/Node/Blocks/Rendering/csmShadowGeneratorBlock.ts
  packages/dev/core/src/FrameGraph/Tasks/Rendering/csmShadowGeneratorTask.ts
  packages/dev/core/src/FrameGraph/frameGraph.ts
  packages/dev/core/src/scene.ts
Labels: enhancement, frame graph

#16685 WebGPU bind groups: Improve error messages
  packages/dev/core/src/Engines/WebGPU/webgpuCacheBindGroups.ts
Labels: skip changelog

#16625 SH support in NME GS
  packages/dev/core/src/Materials/GaussianSplatting/gaussianSplattingMaterial.ts
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/gaussianBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/gaussianSplattingBlock.ts
  packages/dev/core/src/Materials/Node/Blocks/GaussianSplatting/splatReaderBlock.ts
  packages/dev/core/src/Materials/Node/nodeMaterialBuildState.ts
  packages/dev/core/src/Materials/Node/nodeMaterialDefault.ts
  packages/dev/core/src/Shaders/ShadersInclude/gaussianSplatting.fx
  packages/dev/core/src/Shaders/gaussianSplatting.vertex.fx
  packages/dev/core/src/ShadersWGSL/ShadersInclude/gaussianSplatting.fx
  packages/dev/core/src/ShadersWGSL/gaussianSplatting.vertex.fx
Labels: nme

#16691 RH camera fixes
  packages/dev/core/src/Cameras/arcRotateCamera.ts
  packages/dev/core/src/Cameras/targetCamera.ts
  packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
  packages/tools/tests/test/visualization/config.json
Labels: bug, breaking change
